### ISSUE TITLE
Unable to build, read-only file system

### ISSUE THREAD

**Issue by stjohnjohnson** [rtfd/readthedocs.org#2475] opened 2016-10-27 16:13 UTC
## Details

I created a project, it automatically started a build.  That build failed with the error below.  I triggered a new one, that also failed with the same error.

* Project URL: https://readthedocs.org/projects/screwdriver-cd/
* Build URL (if applicable): https://readthedocs.org/projects/screwdriver-cd/builds/4574112/
* Read the Docs username (if applicable): stjohnjohnson

## Expected Result

Documentation is built.

## Actual Result

Got the error `[Errno 30] Read-only file system: '/home/docs/checkouts/readthedocs.org/user_builds/screwdriver-cd'`

**Comment by agjohnson** [comment] 2016-10-28 18:23
Seems one of our build servers went read only due to a provider issue. I'll check on this.

**Comment by agjohnson** [comment] 2016-10-28 18:27
Should be fixed now. Closing this, but be sure to reopen if the problem is still present.

**Closed by agjohnson** 2016-10-28 18:27 UTC
Labels: Operations, Priority: High
