### ISSUE TITLE
Failing builds since 2.5 month ...

### ISSUE THREAD

**Issue by Paebbels** [rtfd/readthedocs.org#2697] opened 2017-03-05 06:28 UTC
I'm waiting since **2.5 month** of a reply why the hell my builds are failing. I see no reaction on my posted issues like #2552 or any improvement in the error reporting for new builds. It would be nice to know that's the reason for a failing build, because I can build everything on my local machine without any problems.

The amount of logged data has even decreased since my last investigation. Right now, even the simple/fast HTML version isn't build anymore!

**Build:** #5106194
**Release:** ab518c84a432dad7a564c083e38a0d627ee14f3f)
**User:** Paebbels
**Project:** PoC-Library
**Build time:** 591 seconds

According to the documentation, we get 15 minutes to build our documentations. The report shows < 10 minutes. The complete compilation (HTML, LaTeX, PDF, without other HTML formats) lasts: 
* HTML: 6:01 min (4:32 reading files; 1:29 writing content)
* LaTeX: 1:45 min (0:56 reading files; 0:49 writing content)
* PDF: 0:57 min (pdflatex)
* **Sum: 8:43 min**
* Used RAM circa. 400 MiB

**So please write a reply and give me ans answer or hint why these builds fail. Tanks.**

It would be a nice start to see the last log entry. Currently, ReadTheDocs doesn't show started but aborted or errored logs of a build tasks.

**Comment by humitos** [comment] 2017-03-08 00:04
@Paebbels hi, I went trough the last 2 pages of your failing building at http://readthedocs.org/projects/poc-library/builds/ and I can say that it's failing because it ran our of time: ~598 seconds. RTD has a limit of time and memory spend on the buildings, and I think the documentation is wrong since it says 15 minutes but it's 10 in the real life :)

We just addressed this on the #readthedocs IRC channel as a bug in production settings that is not setting the 15 minutes properly and it uses the default (10 minutes). I'm trying to work in a solution but I will need to read and learn a couple of things from RTD. Please, be patience.

**Comment by Paebbels** [comment] 2017-03-08 00:24
Hello @humitos,

thanks for looking into that problem. So is 10 or 15 minutes the intended maximum runtime? I remember that the docs somewhere stated it's possible to get more time. What are the criteria to get more resources for an open source project?

Our library documents circa 120 IP cores on circa 300 PDF pages plus a Python helper program that requires circa 350 pages for the internal API documentation (74 Python packages).

I guess that our documentation is at 30-40% of what should be documented.

P.S. I contacted one of the Sphinx extensions providers (autoapi.sphinx) if he or I can improve the runtime. Currently the extension recreates files on every builder run, but that's not required on RTD, because the input data doesn't change between `pickle`, `html`, `singlehtml` and `latex` runs.

**Comment by humitos** [comment] 2017-03-08 01:05
> So is 10 or 15 minutes the intended maximum runtime?

It should be 15 minutes, but there was a bug in the production settings. @agjohnson is working on that

I just wrote a PR that will try to inform the correct error to the user (`Build exited due to time out`) instead of unexpected error when the 15 minutes time limit is reached.

> I remember that the docs somewhere stated it's possible to get more time. What are the criteria to get more resources for an open source project?

Yes, here: http://docs.readthedocs.io/en/latest/builds.html#build-process

I'm not sure what are the criteria, it doesn't say too much :(

> P.S. I contacted one of the Sphinx extensions providers (autoapi.sphinx) if he or I can improve the runtime. Currently the extension recreates files on every builder run, but that's not required on RTD, because the input data doesn't change between pickle, html, singlehtml and latex runs.

Sorry, I don't have the knowledge about this even to say something coherent :)

Anyway, not sure if you are talking about `sphinx-autoapi` (https://github.com/rtfd/sphinx-autoapi) or another extension. The `sphinx-autoapi` is done also by the RTD people and I'm sure they will be very happy if you can contribute by improving that code (it's still a pre-release version).

**Comment by Paebbels** [comment] 2017-03-08 01:09
Unfortunately, there is a seconds (2 years old) extension: https://github.com/carlos-jenkins/autoapi
It has some advantages over the better known autoapi.

**Comment by Paebbels** [comment] 2017-03-10 02:26
Hello,
Now I can see a better error message:
> Build exited due to time out

It also shows:
> Build took 891 seconds

So, now I know what's going on and that I need to save more time when compiling my docs.

**Comment by KelSolaar** [comment] 2017-03-10 02:30
I noticed that my builds are now compiling Numpy which they weren't before. I'll take a deeper look back at that later.

**Comment by KelSolaar** [comment] 2017-03-10 05:20
So by comparing the logs I noticed that _a long time ago in a galaxy far far away_, **Numpy** was actually already installed:

`python setup.py install --force` Section in https://readthedocs.org/projects/colour/builds/4345531/
```
Using /home/docs/checkouts/readthedocs.org/user_builds/colour/envs/develop/lib/python2.7/site-packages
Searching for numpy==1.11.1
Best match: numpy 1.11.1
Processing numpy-1.11.1-py2.7-linux-x86_64.egg
numpy 1.11.1 is already the active version in easy-install.pth
Installing f2py script to /home/docs/checkouts/readthedocs.org/user_builds/colour/envs/develop/bin
```
> Command time: 4s

When builds started to fail however, **Numpy** was getting compiled:

`python setup.py install --force` Section in https://readthedocs.org/projects/colour/builds/5124446/
```
Installed /home/docs/checkouts/readthedocs.org/user_builds/colour/envs/develop/lib/python2.7/site-packages/colour_science-0.3.9-py2.7.egg
Processing dependencies for colour-science==0.3.9
Searching for numpy>=1.8.1
Reading https://pypi.python.org/simple/numpy/
Downloading https://pypi.python.org/packages/0b/84/2b79ab0ca3a95442ae14847b50fc437438df8792dce1adb798695de22845/numpy-1.12.1rc1.zip#md5=091bc6601fe74d0e5a00c22c3d97d9bc
Best match: numpy 1.12.1rc1
Processing numpy-1.12.1rc1.zip
Writing /tmp/easy_install-yDsa3A/numpy-1.12.1rc1/setup.cfg
Running numpy-1.12.1rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yDsa3A/numpy-1.12.1rc1/egg-dist-tmp-rHpRne
Running from numpy source directory.
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/setup.py:366: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  self.calc_info()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  self.calc_info()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
non-existing path in 'numpy/distutils': 'site.cfg'
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable ifort
Could not locate executable ifc
Could not locate executable lf95
Could not locate executable pgfortran
Could not locate executable f90
Could not locate executable f77
Could not locate executable fort
Could not locate executable efort
Could not locate executable efc
Could not locate executable g77
Could not locate executable g95
Could not locate executable pathf95
don't know how to compile Fortran code on platform 'posix'
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
 int exp (void);
     ^
_configtest.o: In function `main':
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
 int exp (void);
     ^
_configtest.c:1:24: fatal error: sys/endian.h: No such file or directory
compilation terminated.
_configtest.c: In function ‘main’:
_configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
     static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) >= 0)];
                ^
```
> Command time: 384s

So this is 4s spent before versus 384s now.

Is it something you noticed? @agjohnson, @humitos?

Cheers,

Thomas

**Comment by Paebbels** [comment] 2017-03-10 10:42
@KelSolaar this is a separate problem. Please create a new issue in GitHub and link it to this issue if required to explain your problem.

**Comment by KelSolaar** [comment] 2017-03-10 18:36
@Paebbels: Mmmmh, I would argue that it is not a separate problem, my builds are failing exactly because of timeout. The root cause on my end is now clear but until the build time was raised again it was hard to say what was the exact reason. I'll create a new issue anyway.

**Comment by humitos** [comment] 2017-03-11 00:38
@Paebbels since you opened a new issue requesting for more building time at https://github.com/rtfd/readthedocs.org/issues/2715 I will close this issue. Besides, the original problem I think was fixed because now it's notified in the proper way.

Feel free to re-open if you consider.

**Closed by humitos** 2017-03-11 00:38 UTC
Labels: Bug, Operations
