### ISSUE TITLE
Support 'base' in ConfigWrapper and Sphinx backend

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2646] opened 2017-02-16 04:04 UTC
As per the spec for https://github.com/rtfd/readthedocs-build, we should support the 'base' configuration element. This logic would need to be moved from the project model and into the sphinx backend, but this makes more sense anyways.

**Comment by Jigar3** [comment] 2018-02-14 07:22
@agjohnson  I want to work on this issue.
Can you give me more details regarding this

**Comment by RichardLitt** [comment] 2018-02-14 20:53
@stsewd Would you be able to help with this?

**Comment by stsewd** [comment] 2018-02-15 08:50
@RichardLitt @Jigar3 I'm not familiar with the https://github.com/rtfd/readthedocs-build project, but what I understand this would be a step for moving the build process to the other library. I'm going to take a look to the other project on the next days, so hope to be more helpful then.

**Comment by stsewd** [comment] 2018-03-07 05:14
@RichardLitt well now I think I have some more experience with the other project (sorry for taking a long time).

@Jigar3 I recommend you reading the spec of the yaml file here https://github.com/rtfd/readthedocs-build/blob/master/docs/spec.rst, also https://docs.readthedocs.io/en/latest/yaml-config.html (#3685 contains more accurate docs) so you have a little more of context of what this issue is about.

From the spec:

> **base**
> The path to the root directory of the documentation that this config is about. That is usually the path that contains the conf.py file. It defaults to the directory that the readthedocs.yml file lives in. **All commands for building the documentation will have the base set as working directory**.

This is what the issue is about, respecting  the `base` setting from the yaml file when executing build commands. Let me know if you need more information about the files that would need to be edited.

**Comment by stsewd** [comment] 2018-03-16 20:45
@Jigar3 are you still interested or working on this issue?

**Comment by stsewd** [comment] 2018-09-24 22:50
I think we can close this in favor of https://github.com/rtfd/readthedocs.org/issues/4354

**Comment by stsewd** [comment] 2018-11-27 22:13
Closing as this isn't on our current schema, and we have the new `install` key which accepts a path for each installation.

**Closed by stsewd** 2018-11-27 22:13 UTC
Labels: Sprintable
