### ISSUE TITLE
Even no error is raised, but it shows failed, however, the site endpoint is really updated!

### ISSUE THREAD

**Issue by MacHu-GWU** [rtfd/readthedocs.org#3346] opened 2017-12-02 22:16 UTC
## Details

* Project URL (https://github.com/MacHu-GWU/mm6doc-project): 
* Build URL (https://readthedocs.org/projects/mm6doc/builds/6352586/): 

## Expected Result

*A description of what you wanted to happen*: Since I didn't see any error message, the build should be passed.

## Actual Result

*A description of what actually happened*: In the admin panel, it shows failed, but able to visit at https://mm6doc.readthedocs.io/index.html. Its really weird!

**Comment by safwanrahman** [comment] 2017-12-02 22:23
As mentioned in the build error log, `There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6352586).`

We will investigate it to come with a proper fix.

**Comment by humitos** [comment] 2017-12-03 19:47
Thanks for your report. We had a couple of build similar to this one and we are researching to know that it's the cause of it.

**Comment by humitos** [comment] 2017-12-03 20:00
I imported this project into my local instance and I was able to reproduce the issue reported here: build with error, but I can see the docs.

The error in the log is

```
Traceback (most recent call last):
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 235, in run_build
    outcomes = self.build_docs()
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 432, in build_docs
    outcomes['localmedia'] = self.build_docs_localmedia()
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 479, in build_docs_localmedia
    return self.build_docs_class('sphinx_singlehtmllocalmedia')
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 507, in build_docs_class
    builder.move()
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/doc_builder/base.py", line 19, in decorator
    return fn(*args, **kw)
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/doc_builder/backends/sphinx.py", line 237, in move
    to_write)
  File "/home/humitos/.pyenv/versions/2.7.14/envs/rtfd/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 11: ordinal not in range(128)
```

We will need to take a deeper look anyway to understand what's happening.

**Comment by MaslovaEV** [comment] 2017-12-04 10:06
It seems I have the same issue:
Build fails with the error: There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6356825). 
But the docs look updated.

**Comment by MacHu-GWU** [comment] 2017-12-05 19:49
Yes, very strange, I think all of doc is utf-8 encoded.

**Comment by stsewd** [comment] 2018-03-13 23:17
I was able to build your docs successfully on my local instance (and also check on the .org site), can you try building again?

**Comment by stsewd** [comment] 2018-06-01 03:12
You can try disabling the pdf and epub generation if you don't need that.

https://readthedocs.org/projects/rtd-test-stsewd-2/builds/7277980/
https://readthedocs.org/projects/rtd-test-stsewd-2/builds/7277959/

**Comment by stsewd** [comment] 2018-06-21 16:58
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also, there are some other issues opened about unicode and pdf generation. And your latest builds are passing.

**Closed by stsewd** 2018-06-21 16:58 UTC
Labels: Bug, Needed: more information
