### ISSUE TITLE
Flyout links incorrect on Mkdocs projects

### ISSUE THREAD

**Issue by dnrce** [rtfd/readthedocs.org#1917] opened 2016-01-12 04:14 UTC
GitHub links in the sidebar footer contain an extraneous path. For example, on http://tracks.readthedocs.org/en/latest/upgrading/ the "View" link points to https://github.com/TracksApp/tracks/blob/master/home/docs/checkouts/readthedocs.org/user_builds/tracks/checkouts/latest/doc/Upgrading.md.

**Comment by marcelstoer** [comment] 2016-02-19 07:33
#1480 was closed even though the root cause seems to be the same. Yet, the flyout links are still incorrect.

**Comment by sahilTakiar** [comment] 2016-03-05 21:01
I was trying to fix this and believe I found the cause, I was able to get a working version for a MkDocs based project.

More info here: https://github.com/rtfd/readthedocs.org/commit/98b5d34316917e0bdb26404c6f3816108ce7f42e

**Comment by sahilTakiar** [comment] 2016-03-09 18:28
@agjohnson any thoughts on my comment in https://github.com/rtfd/readthedocs.org/commit/98b5d34316917e0bdb26404c6f3816108ce7f42e

I have tested the change locally using the directions here: https://docs.readthedocs.org/en/latest/install.html#installing-read-the-docs and it works for a MkDocs and Sphinx based projects.

**Comment by sahilTakiar** [comment] 2016-03-11 20:40
@ericholscher do you have any thoughts on this? If I have a fix that is tested, so I can create the PR. Want to get this fixed as we just went live with our ReadTheDocs integration.

**Comment by ericholscher** [comment] 2016-03-11 20:57
@sahilTakiar Definitely send the PR over!

**Comment by kenorb** [comment] 2016-04-19 17:08
The same here.

Steps to reproduce:

1. Go to [this page](http://docs.drupalvm.com/en/latest/).
1. Click _Read the Docs_ in the bottom, then View or Edit.

The links are like:

    https://github.com/geerlingguy/drupal-vm/blob/master/home/docs/checkouts/readthedocs.org/user_builds/drupal-vm/checkouts/latest/docs/index.md
    https://github.com/geerlingguy/drupal-vm/edit/master/home/docs/checkouts/readthedocs.org/user_builds/drupal-vm/checkouts/latest/docs/index.md

**Comment by laughinghan** [comment] 2016-05-10 08:19
Same here: http://mathquill.readthedocs.io/en/latest/

**Comment by marcelstoer** [comment] 2017-03-05 07:06
#2066 was merged hours ago and thus this should now be closed I guess.

**Comment by dnrce** [comment] 2017-03-05 18:13
Thanks @marcelstoer. I just rebuilt and the issue persists so I don't believe this should be closed until the change is deployed.

**Comment by ericholscher** [comment] 2017-03-06 17:34
Just deployed this, so it should hopefully be fixed.

**Comment by dnrce** [comment] 2017-03-06 17:52
It appears to be. Thanks @sahilTakiar and @ericholscher!

**Comment by marcelstoer** [comment] 2017-03-06 20:18
It works for the OP's project at http://tracks.readthedocs.org but it doesn't work for any other project listed here in the comments: http://docs.drupalvm.com,  http://mathquill.readthedocs.io and http://nodemcu.readthedocs.io (mine) still have this odd ".../docs/checkouts/readthedocs.org/..." URLs. What's the difference between them? I even just built mine again to be sure.

**Comment by markekraus** [comment] 2017-04-30 20:49
same for me. The view and edit URLs have the same '.../docs/checkouts/readthedocs.org/...' in them

I thought maybe it was related to having ```edit_uri``` set in ```mckdocs.yml```, but removing it and rebuilding seems to make no difference. @marcelstoer doesn't even have the set in their mkdcos.yml.

- https://psraw.readthedocs.io/en/latest/
- https://psmsgraph.readthedocs.io/en/latest/
- https://autodocumentsexample.readthedocs.io/en/latest/

**Comment by PowerKiKi** [comment] 2017-05-05 13:07
`edit_uri` is a feature that [appeared in mkdocs 0.16](http://www.mkdocs.org/about/release-notes/#version-016-2016-11-04) and that would help in solving that I think. But it seems RTFD is still using mkdocs 0.15 according to my [build logs](https://readthedocs.org/projects/phpspreadsheet/builds/5380219/).

Is an upgrade to mkdocs 0.16 planed ? Or is it something that could be contributed by someone relatively easily ?

**Comment by stsewd** [comment] 2018-06-06 17:35
I didn't know that this issue was already reported, I'm fixing this in https://github.com/rtfd/readthedocs.org/pull/3525

**Closed** 2018-10-02 16:02 UTC
Labels: Bug

**Comment by ryanpitts** [comment] 2019-01-05 01:04
Sorry to ping in a closed issue, but I'm seeing the same broken "View/Edit on GitHub" links in this project, which is using Mkdocs for the build: http://fieldguide.opennews.org/en/latest/. Both URLs have the ".../docs/checkouts/readthedocs.org/..." path stuff appended.

I just triggered a fresh build to see if that would clear things up (it had been a while), but no luck. Is there a setting I need to update?

**Comment by stsewd** [comment] 2019-01-05 01:18
Links are correct for me

**Comment by ryanpitts** [comment] 2019-01-05 01:36
Hmmm. I hoped maybe it was just a caching thing so I cleared that out, but the links are still broken for me. (See URL at bottom of screenshot)

![screen shot 2019-01-04 at 5 34 06 pm](https://user-images.githubusercontent.com/56477/50718700-2f12e280-1047-11e9-9c48-fae3e11a07cd.png)

**Comment by PowerKiKi** [comment] 2019-01-05 08:55
Links are correct for me too. Might be CDN related cache?

**Comment by stsewd** [comment] 2019-01-05 15:10
Yeah, I think so, CDN or ISP caching

**Comment by ryanpitts** [comment] 2019-01-07 17:40
Hey! Sure enough, those links are correct for me now too. (I promise I tried clearing caches, multiple browsers, etc etc.) Thanks for the response!
