### ISSUE TITLE
Getting build failure: File Exists when trying to create virtualenv

### ISSUE THREAD

**Issue by vmalloc** [rtfd/readthedocs.org#2642] opened 2017-02-14 21:07 UTC
## Details

* Project URL: https://slash.readthedocs.org
* Build URL (if applicable): https://readthedocs.org/projects/slash/builds/5027404/
* Read the Docs username (if applicable): vmalloc

Getting:
```
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/slash/envs/develop/bin/python2.7
Not overwriting existing python script /home/docs/checkouts/readthedocs.org/user_builds/slash/envs/develop/bin/python (you must use /home/docs/checkouts/readthedocs.org/user_builds/slash/envs/develop/bin/python2.7)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1370, in install_python
    os.symlink(py_executable_base, full_pth)
OSError: [Errno 17] File exists
```

**Comment by agjohnson** [comment] 2017-02-14 21:08
Closing as duplicate of #2640

**Closed by agjohnson** 2017-02-14 21:08 UTC
