### ISSUE TITLE
Please provide an option to export the docs on A4 paper

### ISSUE THREAD

**Issue by ufechner7** [rtfd/readthedocs.org#2202] opened 2016-05-10 08:01 UTC
Currently, only export in letter format is supported. Please add an option to export the docs in A4 (European) paper format.

**Comment by agjohnson** [comment] 2016-05-19 16:51
Without having looked into it, is there a latex style for A4 that you can set in your configuration?

**Comment by softgrow** [comment] 2016-05-22 09:53
There is a latex style for A4, in Julia. In Downloads on http://docs.julialang.org/en/release-0.4/ there are three links PDF, HTML & Epub. The PDF linked is for US Letter paper. What is needed is a fourth link making it PDF (US Letter), PDF (A4), HTML and Epub. This would then allow users outside North and Central America to have a PDF download for printing using locally available paper.

**Comment by agjohnson** [comment] 2016-06-04 01:11
Okay, well, if you only need the a4 paper output, you can control this with the Sphinx configuration option `latex_elements`, specifically, `latex_elements['papersize'] = 'a4paper'` (beware: untested). The larger issue is that we need to make some larger design decisions about an overhaul of the versions and/or downloads project page, and we need a pattern for accumulating these arbitrary files while ensuring we get the files we need out of the build process. All of this is a duplicate of #2045 though, so I will close this here.

**Closed by agjohnson** 2016-06-04 01:11 UTC
Labels: Support
