### ISSUE TITLE
Rich text editor on settings page is broken on Chrome & Firefox

### ISSUE THREAD

**Issue by mithro** [rtfd/readthedocs.org#3629] opened 2018-02-17 00:58 UTC
## Details

* Project URL: https://readthedocs.org/dashboard/vtr-verilog-to-routing/edit/
* Read the Docs username (if applicable): mithro

The editor widget for a project description in the settings page seems to be broken on Chrome. I'm unable to get any rich formatting to work.

## Expected Result

Able to use rich text editor on the setting page to add formatting to the description.

## Actual Result

None of the formatting buttons seem to do anything and I get errors in the Chrome console.

I'm using;
 * Google Chrome: 64.0.3282.140 (Official Build) (64-bit)
 * Revision: a06bc1d5e8e285c70078802de990c1719ccc75e8-refs/branch-heads/3282@{#631}
 * OS: Linux
 * JavaScript: V8 6.4.388.41

The errors I'm getting are;
```
VM15804:1 Uncaught TypeError: Cannot read property 'safari' of undefined
    at init (eval at <anonymous> (VM15803 jquery.markitup.pack.js:9), <anonymous>:1:1621)
    at HTMLTextAreaElement.eval (eval at <anonymous> (VM15803 jquery.markitup.pack.js:9), <anonymous>:1:9391)
    at Function.each (jquery.js:1)
    at init.each (jquery.js:1)
    at init.$.fn.markItUp (eval at <anonymous> (VM15803 jquery.markitup.pack.js:9), <anonymous>:1:592)
    at HTMLDocument.<anonymous> ((index):65)
    at f (jquery.js:3)
    at Object.fireWith [as resolveWith] (jquery.js:3)
    at Function.ready (jquery.js:1)
    at HTMLDocument.he (jquery.js:1)
(index):1 The SSL certificate used to load resources from https://bam.nr-data.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
VM15804:1 Uncaught TypeError: Cannot read property 'msie' of undefined
    at fixIeBug (eval at <anonymous> (VM15803 jquery.markitup.pack.js:9), <anonymous>:1:6155)
    at markup (eval at <anonymous> (VM15803 jquery.markitup.pack.js:9), <anonymous>:1:5237)
    at eval (eval at <anonymous> (VM15803 jquery.markitup.pack.js:9), <anonymous>:1:2932)
Navigated to https://readthedocs.org/dashboard/vtr-verilog-to-routing/edit/
VM15863:1 Uncaught TypeError: Cannot read property 'safari' of undefined
    at init (eval at <anonymous> (VM15862 jquery.markitup.pack.js:9), <anonymous>:1:1621)
    at HTMLTextAreaElement.eval (eval at <anonymous> (VM15862 jquery.markitup.pack.js:9), <anonymous>:1:9391)
    at Function.each (VM15853 jquery.js:1)
    at init.each (VM15853 jquery.js:1)
    at init.$.fn.markItUp (eval at <anonymous> (VM15862 jquery.markitup.pack.js:9), <anonymous>:1:592)
    at HTMLDocument.<anonymous> ((index):65)
    at f (VM15853 jquery.js:3)
    at Object.fireWith [as resolveWith] (VM15853 jquery.js:3)
    at Function.ready (VM15853 jquery.js:1)
    at HTMLDocument.he (VM15853 jquery.js:1)
init @ VM15863:1
(anonymous) @ VM15863:1
each @ VM15853 jquery.js:1
each @ VM15853 jquery.js:1
$.fn.markItUp @ VM15863:1
(anonymous) @ (index):65
f @ VM15853 jquery.js:3
fireWith @ VM15853 jquery.js:3
ready @ VM15853 jquery.js:1
he @ VM15853 jquery.js:1
(index):1 The SSL certificate used to load resources from https://bam.nr-data.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
Navigated to https://readthedocs.org/dashboard/vtr-verilog-to-routing/edit/
VM15937:1 Uncaught TypeError: Cannot read property 'safari' of undefined
    at init (eval at <anonymous> (jquery.markitup.pack.js:9), <anonymous>:1:1621)
    at HTMLTextAreaElement.eval (eval at <anonymous> (jquery.markitup.pack.js:9), <anonymous>:1:9391)
    at Function.each (jquery.js:1)
    at init.each (jquery.js:1)
    at init.$.fn.markItUp (eval at <anonymous> (jquery.markitup.pack.js:9), <anonymous>:1:592)
    at HTMLDocument.<anonymous> ((index):65)
    at f (jquery.js:3)
    at Object.fireWith [as resolveWith] (jquery.js:3)
    at Function.ready (jquery.js:1)
    at HTMLDocument.he (jquery.js:1)
init @ VM15937:1
(anonymous) @ VM15937:1
each @ jquery.js:1
each @ jquery.js:1
$.fn.markItUp @ VM15937:1
(anonymous) @ (index):65
f @ jquery.js:3
fireWith @ jquery.js:3
ready @ jquery.js:1
he @ jquery.js:1
(index):1 The SSL certificate used to load resources from https://bam.nr-data.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
VM15937:1 Uncaught TypeError: Cannot read property 'msie' of undefined
    at fixIeBug (eval at <anonymous> (jquery.markitup.pack.js:9), <anonymous>:1:6155)
    at markup (eval at <anonymous> (jquery.markitup.pack.js:9), <anonymous>:1:5237)
    at eval (eval at <anonymous> (jquery.markitup.pack.js:9), <anonymous>:1:2932)
```

I also attempt to edit the description in Firefox and was unable to do so either. Tested with Firefox version: 52.6.0 (64-bit) and I get the following errors in the Firefox console;
```
TypeError: $.browser is undefined[Learn More]  jquery.markitup.pack.js%20line%209%20%3E%20eval:1:1530
	init https://media.readthedocs.org/lib/markitup/jquery.markitup.pack.js%20line%209%20%3E%20eval:1:1530
	$.fn.markItUp/< https://media.readthedocs.org/lib/markitup/jquery.markitup.pack.js%20line%209%20%3E%20eval:1:9391
	require<.jquery</</<.each https://media.readthedocs.org/static/vendor/jquery.js:1:13881
	require<.jquery</</se.prototype.each https://media.readthedocs.org/static/vendor/jquery.js:1:10909
	$.fn.markItUp https://media.readthedocs.org/lib/markitup/jquery.markitup.pack.js%20line%209%20%3E%20eval:1:587
	<anonymous> https://readthedocs.org/dashboard/vtr-verilog-to-routing/edit/:65:7
	require<.jquery</</se.Callbacks/f https://media.readthedocs.org/static/vendor/jquery.js:3:1852
	require<.jquery</</se.Callbacks/p.fireWith https://media.readthedocs.org/static/vendor/jquery.js:3:2664
	require<.jquery</</<.ready https://media.readthedocs.org/static/vendor/jquery.js:1:12200
	require<.jquery</</he https://media.readthedocs.org/static/vendor/jquery.js:1:9829
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery.js:3:21186
TypeError: $.browser is undefined[Learn More]  jquery.markitup.pack.js%20line%209%20%3E%20eval:1:1
	fixIeBug https://media.readthedocs.org/lib/markitup/jquery.markitup.pack.js%20line%209%20%3E%20eval:1:1
	markup https://media.readthedocs.org/lib/markitup/jquery.markitup.pack.js%20line%209%20%3E%20eval:1:5237
	dropMenus/</li</< https://media.readthedocs.org/lib/markitup/jquery.markitup.pack.js%20line%209%20%3E%20eval:1:2932
```

**Comment by stsewd** [comment] 2018-02-17 01:50
I can see the same on my Firefox (58.0.1 64 bits), OS: Fedora 27

**Comment by Jigar3** [comment] 2018-02-17 18:01
I can see the same on Chromium Version 64.0.3282.119 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)

**Comment by aasis21** [comment] 2018-02-18 14:25
Do these editor formatting buttons need to produce rst code or its preview?

**Comment by stsewd** [comment] 2018-03-03 20:29
This was fixed (actually removed) on #3633 (merged).

**Comment by stsewd** [comment] 2018-03-03 23:03
@RichardLitt with the current change (deletion) there isn't a rich editor, just a plain text area.

![screenshot-2018-3-3 edit project read the docs](https://user-images.githubusercontent.com/4975310/36940235-19a71cd0-1f0d-11e8-9cce-a66fb66e1f7c.png)

**Comment by RichardLitt** [comment] 2018-03-03 23:31
Alright. Shall I close this, then?

**Comment by stsewd** [comment] 2018-03-03 23:41
@RichardLitt I think so, I can't see any of those warning on the js console now and this is in-reproducible anyway because there is not buttons to click :smile:.

**Closed** 2018-03-04 16:04 UTC
Labels: Bug, Needed: replication
