### ISSUE TITLE
The wrong commit is being used for latest

### ISSUE THREAD

**Issue by akutz** [rtfd/readthedocs.org#1785] opened 2015-10-22 21:25 UTC
Hi, 

I'm working on http://rexray.readthedocs.org/en/latest/, and for the second time in two days I've had to nuke the entire site and reimport it. What appears to be happening is that `latest` keeps identifying a two month old commit as the latest commit, and that's clearly incorrect. It's the same commit ID each time, https://github.com/emccode/rexray/tree/329311a4826f5f6e78c00cab5736d57407578a28, which is odd, right?

Recreating the project in RTD helps, but it's gone "bad" now twice, and I'd like to prevent it from happening it again. Thoughts? Suggestions?

**Comment by hamiltron** [comment] 2015-12-17 01:45
I am having the same issue.

**Comment by agjohnson** [comment] 2016-02-17 02:15
@hamiltron builds look as I would expect for your project, they are grabbing the correct commits

@akutz same for rexray, though I see the `latest` version in RTD is/was actual a tag at some point? This might be causing issues, or could be a misidentification on RTD

Has this been a problem for either project since reporting?

**Comment by hamiltron** [comment] 2016-02-22 03:46
@agjohnson, I had switched to having the 'master' branch version as the default as a workaround because the 'latest' version was stuck on an earlier commit. To see if the issue still exists, I re-enabled the 'latest' version, built both 'latest' and 'master', committed a small docs change, and built both again. Looks like they're updating correctly now. 

I have noticed however, that the index page for the 'master' version shows a on old commit hash (2909744e) as the version: http://simpleaudio.readthedocs.org/en/master/ - it should be b7c11dd. The 'latest' version doesn't seem to have this problem.

**Comment by jaraco** [comment] 2017-05-01 13:09
I encountered this problem today. I had pushed and built yougov/velociraptor@bbfb3ce, then I force-pushed yougov/velociraptor@bd866b8. I then re-pushed bbfb3ce and subsequent commits such as yougov/velociraptor@1de35d7. Yet RTD [continues to build](https://readthedocs.org/projects/velociraptor/builds/5361018/) bd866b8 over and over again.

**Comment by jaraco** [comment] 2017-05-01 13:18
I tried changing the repo URL to another project and back, but even doing that triggered a build of the same commit.

**Comment by jaraco** [comment] 2017-05-01 13:21
Aha - setting the "Default branch" on the project to `master` seems to have done the trick.

**Comment by stsewd** [comment] 2018-01-16 18:32
I wasn't able to reproduce this issue on my local instance. I think this other issue is related #2032. Probably happens when force a push (commits/tags)?

**Comment by stsewd** [comment] 2018-04-09 05:47
Everyone having this problem, it is a bug (more information on #3887). The current solution is recreating the project (the same name can be used)

**Closed** 2018-06-19 08:10 UTC
Labels: Support
