### ISSUE TITLE
Allow users to change theme

### ISSUE THREAD

**Issue by karai17** [rtfd/readthedocs.org#1191] opened 2015-03-16 01:41 UTC
I would like to try other themes provided by mkdocs but it seems like no matter what I change the theme to, I am forced to use the RTD theme. :(

**Comment by marscher** [comment] 2015-05-13 14:27
you can override this in your sphinx conf.py

**Comment by karai17** [comment] 2015-05-13 14:32
I am not using sphinx, I am using the other one.

**Comment by d0ugal** [comment] 2015-05-27 07:53
This is a duplicate of #978

**Comment by ericholscher** [comment] 2015-05-27 20:56
Closing as dupe.

**Closed by ericholscher** 2015-05-27 20:56 UTC
