### ISSUE TITLE
Document troubleshooting build problems

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#5256] opened 2019-02-08 00:59 UTC
A non-exhaustive list of build issue that users can run into are:

* My build doesn't seem to be updating, what can I do? This is likely a problem on our side, but perhaps wiping the version is a good first step
* My built documentation doesn't look right, what's up? It could be out of sync across our web server, which surfaces in a number of different ways. For instance, if JS or CSS isn't in sync on both webs, you might see the file change every couple of requests, or your documentation site might appear really broken 30%-50% of the time. You should rebuild your project as a first step.
* My builds aren't happening automatically. We can point to webhook docs for this one likely

**Comment by humitos** [comment] 2019-02-12 14:58
Closing this as duplicate of #4729.

**Closed by humitos** 2019-02-12 14:58 UTC
Labels: Accepted, Needed: documentation
