### ISSUE TITLE
Webhook activation failed. Make sure you have permissions to set it.

### ISSUE THREAD

**Issue by Teecloudy** [rtfd/readthedocs.org#4065] opened 2018-05-06 19:27 UTC
I created an srs.rst file on Github. I am trying to import it into readthedocs so the file can be accessed through the readthedocs but im receiving the error below:

This repository doesn't have a valid webhook set up, commits won't trigger new builds for this project. 

Webhook activation failed. Make sure you have permissions to set it.

May you please help me how to get the permission because this account is mine and the project is mine.

Thank you.

**Comment by stsewd** [comment] 2018-05-07 19:15
Please read https://docs.readthedocs.io/en/latest/webhooks.html and https://docs.readthedocs.io/en/latest/getting_started.html

**Comment by stsewd** [comment] 2018-06-15 20:46
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

**Closed by stsewd** 2018-06-15 20:46 UTC
Labels: Needed: more information, Support

**Comment by PollyTikhonova** [comment] 2020-09-02 11:18
@stsewd I followed the instructions in the Docs but still meet with this issue. Please, help me to setup a webhook. Is it even possible if I am trying to setupa webhook for the github repository which owner is not me? but I am a collaborator

**Comment by PollyTikhonova** [comment] 2020-09-02 11:33
Ok, finally, I found out what the problem is.
Only a host of guthub repository can set a webhook, so it is neccesary to add this person to a readthedocs project

**Comment by a-corni** [comment] 2022-09-02 15:37
@stsewd @PollyTikhonova I am a contributor of a readthedoc project with the same rights as its creator (admin). He has a valid and configured webhook and can load the project properly, whereas I get this error when re-synchronising the webhook.
The creator of the readthedoc project is the owner of the github repository, I have the rights to contribute to the repository as well.
Any idea on how to solve this issue ?
