### ISSUE TITLE
browser Accept-Language

### ISSUE THREAD

**Issue by Grummfy** [rtfd/readthedocs.org#3295] opened 2017-11-21 22:59 UTC
Hello,
now when there is someone coming to the documentation of a project, it redirect to /l$project-main-language/version . I think this pattern can be easily improved by using browser language (cf https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html )

I think the redirection is made on this code part in https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/resolver.py#L80

I read something about the way django interpret this code here https://docs.djangoproject.com/en/1.11/topics/i18n/

I think this feature could be configured to keep actual one or move to the new one. In any case, if redirecting to another language that the main project and that this redirection lead to a 404, I would try to see if the default one could exist. But this is extra feature.

thanks

**Comment by safwanrahman** [comment] 2017-11-22 04:04
@Grummfy Are you talking about `<project_name>.readthedocs.io` redirection or `www.readthedocs.org` redirection?

**Comment by Grummfy** [comment] 2017-11-22 07:55
I mean
https://<project_name>.readthedocs.io
->
https://<project_name>.readthedocs.io/<project-main-language>/latest/

**Comment by agjohnson** [comment] 2018-09-17 20:52
Closing as duplicate of #4600

**Closed by agjohnson** 2018-09-17 20:53 UTC
Labels: Improvement
