### ISSUE TITLE
Mkdocs YAML parsing doesn't fail build

### ISSUE THREAD

**Issue by lol768** [rtfd/readthedocs.org#2570] opened 2017-01-02 21:15 UTC
There is a step in the mkdocs backend that will cause the build to stick in a failed state. If YAML parsing fails, this exception is not bubbled up to be displayed to end users. It should be.

## Details

* Project URL: http://kicl.kitteh.org/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/kitteh-irc-client-library/builds/4848266/
* Read the Docs username (if applicable): 

## Expected Result

Build should fail

## Actual Result

Build still appears to be "running" after 26 hours.

**Comment by agjohnson** [comment] 2017-01-05 06:49
Think we covered this in IRC. The issue is that YAML parsing failed and didn't update the build object as failed. I'll update this issue to reflect the underlying issue.

**Comment by lol768** [comment] 2017-01-05 12:14
Ah, interesting! Apologises for the somewhat vague original report

**Comment by lukegb** [comment] 2017-01-05 18:33
This should be fixed by #2573, which makes failures of this sort look like
![image](https://cloud.githubusercontent.com/assets/246745/21692564/5b1f16de-d375-11e6-859a-0b8dacc8a0a9.png)

which is confusing, but at least isn't just the build appearing to hang.

**Comment by lol768** [comment] 2017-01-05 21:47
Tnaks ~lukegb!

**Comment by humitos** [comment] 2017-02-18 01:31
I can confirm that this is working as expected and #2573 fixes this issue

I was able to reproduce the error on my local instance:

```
[17/Feb/2017 19:26:53] ERROR [readthedocs.doc_builder.environments:306] (Build) [kittehircclientlib:issue2570] Your mkdocs.yml could not be loaded, possibly due to a syntax error (line 10, column 5)
Traceback (most recent call last):
  File "/home/humitos/readthedocs/readthedocs.org/readthedocs/projects/tasks.py", line 176, in run
    outcomes = self.build_docs()
  File "/home/humitos/readthedocs/readthedocs.org/readthedocs/projects/tasks.py", line 337, in build_docs
    outcomes['html'] = self.build_docs_html()
  File "/home/humitos/readthedocs/readthedocs.org/readthedocs/projects/tasks.py", line 354, in build_docs_html
    html_builder.append_conf()
  File "/home/humitos/readthedocs/readthedocs.org/readthedocs/doc_builder/backends/mkdocs.py", line 54, in append_conf
    note,))
BuildEnvironmentError: Your mkdocs.yml could not be loaded, possibly due to a syntax error (line 10, column 5)
```

In the _builds_ page I see:

![captura de pantalla_2017-02-17_20-28-15](https://cloud.githubusercontent.com/assets/244656/23088932/ed8155a4-f54f-11e6-85e2-7a160bfe6546.png)

So, I think we can close this issue.

**Comment by ericholscher** [comment] 2017-02-23 18:33
Thanks @humitos :+1:

**Closed by ericholscher** 2017-02-23 18:33 UTC
Labels: Bug, Good First Bug, Mkdocs
