### ISSUE TITLE
Documentation search page subproject display is incorrect

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3826] opened 2018-03-20 19:53 UTC
When searching for a term on our documentation, the search headings now have information from the wrong search index

For example:
![screenshot 2018-03-20 13 48 13](https://user-images.githubusercontent.com/1140183/37679154-bcae8482-2c45-11e8-8c3a-ddc994a5a4aa.png)

The addition of "(from project docs)" should only happen on a superproject search. This text indicates the project slug that the search results came from. Something might have changed with the search JS, or potentially our search index code.

**Comment by stsewd** [comment] 2018-03-20 20:04
Isn't this a duplicate of https://github.com/rtfd/readthedocs.org/issues/3792?

**Comment by agjohnson** [comment] 2018-03-20 20:14
Yup!

**Closed** 2018-03-20 20:14 UTC
Labels: Status: duplicate
