### ISSUE TITLE
No ReadTheDocs theme on one specific page in my documentation

### ISSUE THREAD

**Issue by xKeiro** [rtfd/readthedocs.org#4090] opened 2018-05-14 22:49 UTC
## Details

Project URL:  https://bless-online.readthedocs.io
The Page that hes the Problem: https://bless-online.readthedocs.io/en/stable/community/extreme_guild_specific_content/index.html

Note: When I built the document offline on my machine it worked just fine.

## Expected Result

As every other page in the document to have the Read The Docs theme

## Actual Result

For some reason if I click on the "Extreme guild specific section" the document loses the Read The Docs theme.

**Comment by stsewd** [comment] 2018-05-14 23:09
Duplicate of https://github.com/rtfd/readthedocs.org/issues/3715

There is a PR to try to fix this https://github.com/rtfd/readthedocs.org/pull/4054

**Closed by stsewd** 2018-05-14 23:09 UTC
Labels: Status: duplicate
