### ISSUE TITLE
build static assets

### ISSUE THREAD

**Issue by JrCs** [rtfd/readthedocs.org#4280] opened 2018-06-20 16:13 UTC
I have modified the file `readthedocs/core/static-src/core/js/readthedocs-doc-embed.js` and use the `gulp build`command to regenerate the static assets:

```bash
./node_modules/.bin/gulp build
[18:11:14] Using gulpfile ~/workspace/upstreams/readthedocs.org/gulpfile.js
[18:11:14] Starting 'build'...
[18:11:14] Building source files
(node:4130) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```
The problem is that the `readthedocs/core/static/core/js/readthedocs-doc-embed.js` is not regenerated.

**Comment by stsewd** [comment] 2018-06-20 16:16
I think this was something to do with the node version.

**Comment by JrCs** [comment] 2018-06-20 16:33
Any idea of what version of nodejs to use ?

**Comment by stsewd** [comment] 2018-06-20 16:41
```bash
$ node --version
v10.0.0
```
```bash
$ npm --version
5.6.0
```

**Comment by ericholscher** [comment] 2018-06-20 18:37
I have the same issue, and have had trouble debugging it, so I'd love to see if we find a fix for this.

**Comment by JrCs** [comment] 2018-06-21 08:38
After some investigations, the ``readthedocs/core/static/core/js/readthedocs-doc-embed.js`` is generated if minify is turn off.
In the git log i see that @agjohnson was commit new version of the ``readthedocs/core/static/core/js/readthedocs-doc-embed.js` file. Perhaps he can give us some hints how he do it ?

**Comment by stsewd** [comment] 2018-06-21 16:53
I'm able to build the minified js version with the above node and npm versions btw.

**Comment by JrCs** [comment] 2018-06-22 11:15
@stsewd is the ``readthedocs-doc-embed.js`` correctly minify with all the inclusions in it ?
If yes do you start from a fresh gulp/bower install ?
If yes can you give us informations about on what OS do you made the gulp build ?
I have try in an debian container and it doens't works for the ``readthedocs-doc-embed.js`` file.

**Comment by humitos** [comment] 2018-06-22 15:53
I had some similar problems and I used node 9.2.1 and worked. I don't know the root cause of the issue though.

`nodenv` helped me to setup a different node version in my system.

**Comment by stsewd** [comment] 2018-06-25 15:49
I haven't re-downloaded the dependencies in a long time, so probably the problem is there :thinking:

**Comment by agjohnson** [comment] 2018-06-25 18:41
FWIW, I've tested with 9.2.1 and fresh dependencies and can rebuild without issue.

**Comment by davidfischer** [comment] 2018-06-26 19:43
I am pretty certain this has to do with one of the dependencies and not with node/npm itself. If I clear all the dependencies and rebuild, I see this issue.

    rm -rf node_modules/ bower_components/
    npm i && bower install
    gulp build

I tried both node v8.11.3 (the latest LTS as of this comment) and node v6.9.4 with npm v6.1.0 and I see the issue with both node versions.

I think the `DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead` is not the real issue. If I drop down to node v6.9.4 I don't see the deprecation warning but `readthedocs-doc-embed.js` is still not regenerated.

**Comment by davidfischer** [comment] 2018-06-26 19:52
> After some investigations, the readthedocs/core/static/core/js/readthedocs-doc-embed.js is generated if minify is turn off

I see this as well and it is odd

**Comment by ericholscher** [comment] 2018-06-28 15:41
I get this exception when I run `uglifyjs` directly on the file. It works properly when called with other files, so guessing that might be it?

```
-> ./node_modules/.bin/uglifyjs readthedocs/core/static/core/js/readthedocs-doc-embed.js

/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:204
    throw new JS_Parse_Error(message, line, col, pos);
    ^
Error
    at new JS_Parse_Error (/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:636:9)
    at token_error (/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:644:9)
    at expect_token (/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:657:9)
    at expect (/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:660:36)
    at /Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:1160:44
    at /Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:683:24
    at expr_atom (/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:1117:35)
    at maybe_unary (/Users/eric/projects/readthedocs.org/node_modules/uglify-js/lib/parse.js:1287:19)
```

**Comment by davidfischer** [comment] 2018-06-28 21:42
I believe I have a fix for this issue https://github.com/rtfd/readthedocs.org/pull/4311 any of you folks would be willing to test it.

**Closed** 2018-06-29 18:56 UTC
Labels: Support
