### ISSUE TITLE
rtd doesn't build pdf

### ISSUE THREAD

**Issue by saigkill** [rtfd/readthedocs.org#1753] opened 2015-10-12 05:35 UTC
In this project http://hoe-packaging.readthedocs.org/en/latest rtd renders the index.md correctly. But for the targets html, pdf and epub it says:

Please create a /home/docs/checkouts/readthedocs.org/user_builds/hoe-packaging/checkouts/latest/index.rst or /home/docs/checkouts/readthedocs.org/user_builds/hoe-packaging/checkouts/latest/README.rst file with your own content.

As document type i've set in the settings "Mkdocs". Do i need rst files for rendering to the other targets?

**Comment by saigkill** [comment] 2015-10-17 18:30
Any ideas?

**Comment by agjohnson** [comment] 2015-10-20 01:43
Correct, mkdocs does not support PDF output: http://docs.readthedocs.org/en/latest/builds.html?highlight=pdf#mkdocs

**Comment by ericholscher** [comment] 2016-01-30 00:47
Dupe of #1635

**Closed by ericholscher** 2016-01-30 00:47 UTC
Labels: Triage: Support
