### ISSUE TITLE
Build failed with pip version error

### ISSUE THREAD

**Issue by gregurco** [rtfd/readthedocs.org#4381] opened 2018-07-17 06:35 UTC
## Details

Hello.
I have a problem. Build failed with next message:
```
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command
```
Link: https://readthedocs.org/projects/jobeet-tutorial/builds/7495068/

I tried to require pip with version 10.0.1 and it failed too: https://readthedocs.org/projects/jobeet-tutorial/builds/7496426/
After that I tried to upgrade python to version 3.7 and it failed too: https://readthedocs.org/projects/jobeet-tutorial/builds/7496430/

The last success build: https://readthedocs.org/projects/jobeet-tutorial/builds/7495006/

Yesterday it was ok.
Thanks.

**Comment by Schnitzel** [comment] 2018-07-17 07:42
this is probably a duplicate of https://github.com/rtfd/readthedocs.org/issues/4380

**Comment by gregurco** [comment] 2018-07-17 08:45
One more build: https://readthedocs.org/projects/jobeet-tutorial/builds/7496900/

**Comment by stsewd** [comment] 2018-07-17 16:18
@gregurco this is a bug with mkdocs projects, I'm not sure what is causing this, we are investigating. Closing as duplicate of https://github.com/rtfd/readthedocs.org/issues/4380

**Closed** 2018-07-17 16:30 UTC
