### ISSUE TITLE
Mkdocs missing config argument causes ValidationError

### ISSUE THREAD

**Issue by shravantc** [rtfd/readthedocs.org#1317] opened 2015-06-02 06:54 UTC
I use RTFD service and faced this error in build process>>  mkdocs.config.base.ValidationError: The 'site_dir' can't be within the 'docs_dir'.

 I made indentation changes to a file after the previous passed build, but yet got the above error.

**Comment by d0ugal** [comment] 2015-06-02 07:12
@shravantc Can you show me your config?

Basically, it sounds like you have something like this:

    site_dir: docs/site
    docs_dir: docs

If you do, it will get messy over time. You shouldn't put the site directory within the docs directory (or the other way around).

**Comment by shravantc** [comment] 2015-06-02 07:22
The documentation is hosted in the readthedocs online service and not a local deployment.
This  is the project : gluster.readthedocs.org

**Comment by agjohnson** [comment] 2015-06-02 07:26
This is an error straight from mkdocs, it doesn't seem to be an issue with RTD -- closing this here.

**Comment by d0ugal** [comment] 2015-06-02 07:33
This is actually an issue related to the ReadTheDocs integration. The issue is that `docs_dir` can [default to `.` ](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/base.py#L85) and then the `site_dir` would be `site` and thus relative and within the docs dir. This is an issue because subsequent builds would copy the site dir into itself over and over with each build (MkDocs will copy everything in the docs dir as they are deemed to be static assets). As ReadTheDocs probably does this with a clean env it may not be a problem but in version 0.13, MkDocs stopped users doing this due to the problems people kept seeing.

The quick fix would be to move the `site_dir` outside the project directory here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/mkdocs.py#L136

I'm not sure if that will cause problems however.

**Comment by agjohnson** [comment] 2015-06-02 07:40
Okay, that makes sense. So given the configuration file of:
https://github.com/gluster/glusterdocs/blob/master/mkdocs.yml

the immediate fix would be to add an explicit `docs_dir`?

Is there any reason we need to be setting it in the first place?

**Comment by d0ugal** [comment] 2015-06-02 07:43
I'm going to roll a quick MkDocs release to change this to a warning.

**Comment by d0ugal** [comment] 2015-06-02 07:45
A docs_dir would be a fix, but in this case the Markdown is in the root of the repo. So the files would also need to be moved. Not ideal. I hadn't considered this use case which is common with RTD. Bug release coming in a few minutes.

**Comment by d0ugal** [comment] 2015-06-02 08:05
[Fix in MkDocs](https://github.com/mkdocs/mkdocs/pull/581). Once it passes CI I'll merge and release 0.13.3.

**Closed** 2015-06-02 16:07 UTC
Labels: Mkdocs

**Comment by ericholscher** [comment] 2015-06-02 16:10
Deployed the fix and rebuilt these docs, and they are now passing.

**Comment by shravantc** [comment] 2015-06-03 05:00
Thanks @ericholscher !!
