### ISSUE TITLE
Edit on Github for an md file points to rst extension

### ISSUE THREAD

**Issue by leastprivilege** [rtfd/readthedocs.org#2323] opened 2016-07-20 08:34 UTC
When using 

https://docs.readthedocs.io/en/latest/getting_started.html#in-markdown

The "Edit on Github" links points to `file.rst` where it should be `file.md`.

Is there a workaround for that?

**Comment by berkerpeksag** [comment] 2016-08-17 03:58
This looks like a duplicate of https://github.com/rtfd/readthedocs.org/issues/2130. According to https://github.com/rtfd/readthedocs.org/issues/2130#issuecomment-219825521, upgrading to Sphinx 1.3.6 might be a workaround (haven't tried myself yet.)

**Comment by humitos** [comment] 2017-04-19 01:31
@leastprivilege I'm closing this one due to inactivity. Please, try the workaround suggested in the previous comment and let us know. Also, please provide the URL of your project under RTD so we can see what you are reporting. Feel free to re-open if you consider.

**Closed by humitos** 2017-04-19 01:31 UTC
