### ISSUE TITLE
python ast?

### ISSUE THREAD

**Issue by bannsec** [rtfd/readthedocs.org#2134] opened 2016-04-12 00:57 UTC
I see this project has limitations due to wanting to use epydoc. Is there a reason you can't just use python's built-in AST? So far as I can tell, the process would simply be:

pseudo:
import ast
for file in python files:
   ast.parse(file)

ast will nicely give you a ast.FunctionDef type so you know when you're defining a function/method (class def as well). If the first object of that is a String Expression, that's your comment. Am I missing something?

EDIT: Unable to use Read-the-docs due to current process requiring importing (and thus building Z3... which is way longer than the 5 minutes or whatever. Thus my interest. Sadly, my project is Python 3 and apparently that's still too advanced for much of the world.

**Comment by mgeier** [comment] 2016-04-12 12:21
I guess you are using the Sphinx "autodoc" extension?

If yes, this doesn't really have anything to do with RTD, it's this extension which imports your modules, see http://www.sphinx-doc.org/en/stable/ext/autodoc.html.

You should try the `autodoc_mock_imports` option, see http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autodoc_mock_imports.
If that doesn't work, you can try to manually mock out the imported libraries.

**Comment by agjohnson** [comment] 2016-04-13 00:06
@mgeier I didn't know about the `autodoc_mock_imports` option, that would be great to document if it's a better workaround than asking users to mock manually. This a very common case for us, of course.

@Owlz We're working on bypassing autodoc completely, as it is a bit silly that we need full dependencies and the code needs to be executed to reference docstrings. You should see some of this later this year. The issue is there is no solution for py2 & py3, we'll be working to build AST traversal for both versions, avoiding the headache of project requirements and execution.

For now, the suggestion above by @mgeier should work, otherwise there is an example of manual mocking in our FAQ on our docs.

**Comment by agjohnson** [comment] 2018-09-18 22:21
We have, or will have shortly, more docs on mocking -- both our janky homebrew suggestion and using autodoc_mock_imports.

Also, check out `sphinx-autoapi`, this is our extension that does AST traversal and skips execution entirely.

Closing this issue as it is addressed in auto-api and other places.

**Closed by agjohnson** 2018-09-18 22:21 UTC
Labels: Support
