### ISSUE TITLE
stable build process appears to pick up correct commit, but publishes a stale one

### ISSUE THREAD

**Issue by evildmp** [rtfd/readthedocs.org#2563] opened 2016-12-23 16:47 UTC
## Details

* Project URL: http://docs.django-cms.org/en/stable/
* Build URL (if applicable): https://readthedocs.org/projects/django-cms/builds/4825374/
* Read the Docs username (if applicable): evildmp

## Expected Result

Stable should build the latest release; in fact it correctly (as you can see from the Build URL above) identifies the ``845c5fdd3deed0ead7cc0b7bd19062ceaa8a9589`` commit, https://github.com/divio/django-cms/commit/845c5fdd3deed0ead7cc0b7bd19062ceaa8a9589.

I'd expect http://docs.django-cms.org/en/stable/ to link reflect that commit and link back to it.

## Actual Result

Instead, http://docs.django-cms.org/en/stable/ seems to be based on ``25da45d5d1cd0f48e9e273e23c9a33343addeea4``, a commit that doesn't actually exist (or maybe no longer exists) in the repository: https://github.com/divio/django-cms/edit/25da45d5d1cd0f48e9e273e23c9a33343addeea4/docs/index.rst.

We've wiped, deactivated, rebuilt the version, but to no avail. 

Many thanks for your time.

**Comment by schollii** [comment] 2016-12-28 16:50
I believe my issue is same:  the https://readthedocs.org/projects/pypubsub/versions/ page shows 4 versions, including "stable" which indicates that it points to origin/v4.0.0. However if I click on the stable link, the docs shown are those of the old release, v3.3.0. I tried wipiing, did not help.

**Comment by Peque** [comment] 2017-04-02 13:39
I even tried removing the project from readthedocs.org and recreating it. No luck either. :sweat_smile: 

If you [click on "Edit on GitHub"](http://markdownreveal.readthedocs.io/en/stable/), you will get a [404 error](https://github.com/markdownreveal/markdownreveal/blob/80542c3297b2d9017f00afb5f4a4237d1bbb66cf/docs/source/index.rst).

**Comment by jkroes** [comment] 2017-08-31 19:38
I've got this problem too. Refreshing the url displays the new docs, but viewing the docs always take me to the old home page.

**Comment by Peque** [comment] 2017-09-05 09:54
It seems it is using a valid hash, although it is not the commit hash, but the release (tag) hash. Try to execute `git rev-parse <latest_stable_release_tag>` and see how you get the hash that readthedocs is currently using. You can also actually `git checkout <that_hash>` with no errors, to verify the reference exists.

Unfortunately, the readthedocs-generated GitHub URL that points to the original source code is invalid. To verify this simply go to the "stable" version of the documentation and click on "Edit on GitHub" on the top-right to see the broken link.

@ericholscher Wouldn't it be better to use the actual latest stable tag name when linking to the original source code rather than any hash? It is definitely more readable and would work just as well. Notice that old stable releases all point to the human-readable tag name (i.e.: `mayor.minor.patch` version), the latest version points to a readable name as well (i.e.: `master` branch), but only the stable version points to a non-readable hash (i.e.: ugly `abcdef0123456789...`).

Even though I think changing it to use the more readable tag name is better, if that is not possible, at least it could be great to change it so use the commit hash rather than the release hash, simply to avoid broken links.

**Comment by Wrzlprmft** [comment] 2018-01-11 13:32
Another case of this, unless I am mistaken:

* Project URL: http://jitcode.readthedocs.io/en/v1.1.0/
* Build URL (if applicable): https://readthedocs.org/projects/jitcode/builds/6537796/
* Read the Docs username (if applicable): Wrzlprmft

**Comment by stsewd** [comment] 2018-01-12 22:09
@Wrzlprmft I don't see in your version list http://readthedocs.org/projects/jitcode/versions/ the `stable` version. Did you deactivate it?

**Comment by Wrzlprmft** [comment] 2018-01-12 22:27
@stsewd I protected it so it doesn’t appear in version lists and mislead people. The [direct link](http://jitcode.readthedocs.io/en/stable/) should still work.

**Comment by stsewd** [comment] 2018-01-12 22:27
Also on http://docs.django-cms.org/en/release-3.4.x/ the edit on GitHub is invalid, because rename the branch `release/3.4.x` to `release-3.4.x`

**Comment by stsewd** [comment] 2018-01-12 22:32
@Wrzlprmft the build url you give says it is the latest version, no the stable one.

**Comment by Wrzlprmft** [comment] 2018-01-13 04:30
@stsewd: Indeed, my mistake. Fixed it in the above.

**Comment by Peque** [comment] 2018-01-22 16:12
Cross-linking #3142. In case anybody wants to try it.

**Comment by stsewd** [comment] 2018-05-21 15:59
Closing this as duplicate of https://github.com/rtfd/readthedocs.org/issues/1820. The issue is with annotated tags. #4052 fix this.

**Closed by stsewd** 2018-05-21 15:59 UTC
Labels: Status: duplicate
