### ISSUE TITLE
Delete stale oauth objects on sync

### ISSUE THREAD

**Issue by asachs01** [rtfd/readthedocs.org#1887] opened 2015-12-30 04:35 UTC
Like the title suggests, I'm seeing an organization's repos show up when they shouldn't be. I was formerly a member, and the org has a ton of repos. It's making adding a project a bit of a PITA as I'm having to constantly hit "next" just to get to the repo that I actually need to add. Is there any way to remove those repos via the UI?

**Comment by agjohnson** [comment] 2015-12-31 18:18
Not yet, we don't make any attempt to delete stale objects during oauth syncing yet, we only import/update them. Work I have going on #1850 will delete old remote organizations/repos when the account is reconnected, but this is awful UI for this particular problem. Removing stale objects will require another pass through the database objects, comparing the objects no longer in the oauth object return. This is The Correct Solution, but for now, #1850 will address this problem.

**Comment by humitos** [comment] 2017-12-18 21:41
@asachs01 this issue #3337 (when implemented) don't remove the stale objects but it could help you to filter the repos by your own at least.

**Comment by stsewd** [comment] 2018-05-17 21:35
This is a duplicate of https://github.com/rtfd/readthedocs.org/issues/2412, closing this in favor of the other one.

**Closed by stsewd** 2018-05-17 21:35 UTC
Labels: Bug
