### ISSUE TITLE
Bad build requirement

### ISSUE THREAD

**Issue by JrCs** [rtfd/readthedocs.org#4256] opened 2018-06-18 14:32 UTC
I've create a fresh rtd docker image with this Dockerfile:
```dockerfile
FROM python:2
ARG proxy
ENV http_proxy=$proxy  \
    https_proxy=$proxy \
    no_proxy="localhost,127.0.0.1"

RUN git clone --depth=1 https://github.com/rtfd/readthedocs.org.git

WORKDIR readthedocs.org

RUN pip install -r requirements.txt

# Waiting for PR #4206 to be merged
RUN export DEBIAN_FRONTEND=noninteractive; \
  apt-get update && \
  apt-get -y install vim sed
RUN sed -i 's@--use-wheel@--only-binary=:all:@g' readthedocs/doc_builder/python_environments.py

RUN python manage.py migrate

# Create a superuser account for Django
RUN echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@localhost', 'admin')" | python manage.py shell

RUN python manage.py loaddata test_data

CMD [ "python", "./manage.py", "runserver", "0.0.0.0:8000" ]
```

All is working well but when i try do build the admin-demo i've got:
```
[rtd-command-info] start-time: 2018-06-18T14:30:53.320295, end-time: 2018-06-18T14:30:55.243362, duration: 1, exit-code: 0
python2.7 -mvirtualenv --no-site-packages --no-download /readthedocs.org/user_builds/admin-demo/envs/stable
New python executable in /readthedocs.org/user_builds/admin-demo/envs/stable/bin/python2.7
Also creating executable in /readthedocs.org/user_builds/admin-demo/envs/stable/bin/python
Installing setuptools, pip, wheel...done.

[rtd-command-info] start-time: 2018-06-18T14:30:55.288269, end-time: 2018-06-18T14:30:57.922045, duration: 2, exit-code: 1
python /readthedocs.org/user_builds/admin-demo/envs/stable/bin/pip install --only-binary=:all: --upgrade --cache-dir /readthedocs.org/user_builds/admin-demo/.cache/pip Pygments==2.2.0 setuptools<40 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.7.4 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<0.6
Collecting Pygments==2.2.0
  Downloading https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl (841kB)
Collecting setuptools<40
  Downloading https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl (567kB)
Collecting docutils==0.13.1
  Downloading https://files.pythonhosted.org/packages/5f/6d/e864b3c61b81eec57386ac62082fccfe694c7c3046d8723258a37da6d5fc/docutils-0.13.1-py2-none-any.whl (537kB)
Collecting mock==1.0.1
  Could not find a version that satisfies the requirement mock==1.0.1 (from versions: 1.1.0, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.3.0, 2.0.0)
No matching distribution found for mock==1.0.1
```

Why the requirement (for mock) is not valid ?

**Comment by stsewd** [comment] 2018-06-19 01:20
This is because of a regression. See #4261. Closing this in favor of https://github.com/rtfd/readthedocs.org/issues/4262

**Closed by stsewd** 2018-06-19 01:20 UTC
Labels: Support
