### ISSUE TITLE
Redindex elasticseach?

### ISSUE THREAD

**Issue by zabeloliver** [rtfd/readthedocs.org#2349] opened 2016-08-03 09:27 UTC
Hi, 

i did a manual privat installation of read the docs. I finally succeeded with install elasticsearch and readthedocs can communicate with it. No i get the error that no index is found, and it seems that projects did not get indexed. 

is there a way to force a reindex?

thanks!

**Comment by agjohnson** [comment] 2016-08-07 04:17
This bug is being marked as community effort. The core team will try to facilitate resolution with this issue, but without the resources to support external installations outside of our production environment, we must rely on the community to help.

You can read more information on our philosophy around supporting Read the Docs as an open source and volunteer run effort here:
http://docs.readthedocs.io/en/latest/open-source-philosophy.html

**Comment by zhaown** [comment] 2016-10-06 08:20
@zabeloliver , you don't need to _force a reindex_, every time you rebuild the project, RTD does the reindexing for you.

If you got the error said that _no index is found_, maybe you just didn't setup elasticsearch properly, you can install the ES plugin [head](https://mobz.github.io/elasticsearch-head) to check the ES status/data.

BTW: You need manually run the [script](http://read-the-docs.readthedocs.io/en/latest/rtfd.html#elastic-search-setup) to create an `index` and corresponding `mapping` in ES for RTD, before do any `build`.

**Comment by eldritchsong** [comment] 2017-03-20 18:20
Looks like the documentation for setting up Elastic Search no longer exists.

I'm also setting up a local installation. I'm having some issues with python-elasticsearch communicating with elastic search process.

Which versions of Elastic search and python-elasticsearch should I be using? I'm currently using 1.5 of both, and while this seems to work to a degree, running a reindex errors out still.

**Comment by humitos** [comment] 2017-05-28 19:42
I followed this instructions in Ubuntu 16.04

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-16-04

The problem is that RTD doesn't support elasticsesarch 2.x yet (#2539). Anyway, latest version is 5.4.0 and it's the same version of the python package

**Comment by agjohnson** [comment] 2017-06-08 00:25
Correct that we don't support 2.x currently. We're in the process of overhauling our search functionality, so perhaps could support 2.x+ with that work.

I'm closing this issue either way, I don't think the core development team can offer up much time to resolve this issue. You might have more luck on stackoverflow.

**Closed by agjohnson** 2017-06-08 00:25 UTC
Labels: Community Effort, Support
