### ISSUE TITLE
SSL gnutls_handshake() failed: Handshake failed

### ISSUE THREAD

**Issue by JoeBanks13** [rtfd/readthedocs.org#3062] opened 2017-08-22 02:54 UTC
## Details

* Project URL: https://discoin.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/discoin/builds/5866119/
* Read the Docs username (if applicable): josephbanks

## Expected Result

Cloning repo going fine

## Actual Result

Getting an error https://i.josephbanks.me/i55un.png, this is a legit certificate from Comodo, under a Cloudflare Flexible SSL plan, so it's not a problem with the cert, just wondering what's going on...

**Comment by JoeBanks13** [comment] 2017-08-22 02:57
Forgot to say the GitLab instance is https://gitlab.josephbanks.me/

**Comment by Kobzol** [comment] 2018-03-04 22:34
I'm having the same problem. The docs for my repo worker a week ago, but then my repo server switched to a new certificate (EV certificate from Terena) and now all RTD builds fail on git clone with the gnutls_handshake error.

**Comment by humitos** [comment] 2018-03-06 01:17
@Kobzol could you provide more information?

The report of this issue is several months old and I can't reproduce it locally. So, probably something is fixed with the SSL certificate.

**Comment by Kobzol** [comment] 2018-03-06 07:45
Every build of my project fails with [this](https://readthedocs.org/projects/snailwatch/builds/6844080/) error:
```
git clone --recursive ...
cloning into '.'...
fatal: unable to access '<repo>': gnutls_handshake() failed: Handshake failed
```

I tried several projects that worked with a different certificate just a few weeks ago and all of them fail with the same error, so I'm pretty sure it's caused by the certificate. I know that some other tools that are accessing the website of my repo are having the exact same problem with the handshake. So I guess it's either a badly configured certificate or maybe RTD uses an outdated SSL library that doesn't work with this certificate?  

The certificate is on this site: [https://code.it4i.cz](https://code.it4i.cz). It uses TLS 1.2, ECDHE_RSA with P-256 and AES_256_GCM.

**Comment by humitos** [comment] 2018-03-06 14:34
I can clone the repository without any problem in my computer, so it's definetly something on RTD. I'm not sure what, yet but I will ask to the other folks. Thanks for your report.

**Comment by davidfischer** [comment] 2018-03-06 16:59
I checked the certificate on SSL Labs and it looks good. This issue appears to be an issue with Ubuntu 14.04 issue -- RTD's build servers are still on that -- and when they are upgraded this will resolve itself (see #3615). The same issue does not manifest on later versions.

**Comment by Kobzol** [comment] 2018-03-23 18:10
It works after server upgrade to 16.04 (https://github.com/rtfd/readthedocs.org/pull/3615) :-) Thanks!

**Comment by humitos** [comment] 2018-03-23 18:42
@Kobzol nice! thanks for the update here. I'm closing this issue. Feel free to reopen if you consider ;)

**Closed by humitos** 2018-03-23 18:42 UTC
Labels: Bug, Operations
