### ISSUE TITLE
Being spammed by endless failed build loop

### ISSUE THREAD

**Issue by dlech** [rtfd/readthedocs.org#3180] opened 2017-10-22 17:59 UTC
## Details

* Project URL: https://readthedocs.org/projects/grx/
* Build URL (if applicable): https://readthedocs.org/projects/grx/builds/6159547/ (and 250 more so far!)
* Read the Docs username (if applicable): dlech

## Expected Result

I should not be getting failed build emails every 7 minutes.

Build log should actually show a log instead of only an error message.

## Actual Result

readthedocs.org was emailing me all night long.

I've tried disabling, wiping and clearing all of the related branches/tags but I am still getting error messages for "stable" (the readthedocs.org special feature, not a branch or a tag) even though I disabled, wiped and cleared "stable".

The build "log" says: "An unexpected error occurred" or sometimes "Version locked, retrying in 5 minutes."

I've tried everything I can think of, but I can't seem to break this loop of endless retries.

**Comment by RichardLitt** [comment] 2017-10-22 23:03
@dlech Sorry about this. Is there any way you could set up a temporary filter to ignore those emails in the meantime?

**Comment by RichardLitt** [comment] 2017-10-22 23:27
I'm going to assign this to `priority: high`, because spamming people is a little worse than just having a bug, I think.

**Comment by ericholscher** [comment] 2017-10-23 00:42
Should be fixed. Did you re-tag a version by chance?

**Comment by ericholscher** [comment] 2017-10-23 00:45
I think it's from having two tags with `<string>/3.0.0` and a couple of our builders each remarking the each as the "latest"

**Comment by ericholscher** [comment] 2017-10-23 00:54
Believe the logic that stops new stable builds was also not getting triggered, since it was doing a stream of retry's, instead of new builds :/

**Comment by ericholscher** [comment] 2017-10-23 00:54
Going to leave this open to try and fix this logical fail though! :)

**Comment by dlech** [comment] 2017-10-23 03:46
Thanks! It looks like the emails stopped a few hours ago.

**Comment by agjohnson** [comment] 2017-12-11 08:26
@ericholscher do you know if this would have been fixed by the changes to `stable` last week?

**Comment by ericholscher** [comment] 2017-12-11 15:47
@agjohnson no, this is basically the same bug, but for stable -- and caused by someone re-tagging and two of our builders having different commits for the same tag, and then bouncing back and forth :)

**Comment by agjohnson** [comment] 2018-01-12 09:35
I vaguely remember addressing this. @ericholscher do you know if this is still a valid bug?

**Comment by ericholscher** [comment] 2018-01-13 15:56
We fixed the root cause of this specific bug, but we should really have some kind of failsafe on our notifications and retagging of latest/stable, to stop the general case. We could open a new ticket for that though.

**Closed** 2018-01-13 15:56 UTC
Labels: Bug
