### ISSUE TITLE
support completely removing old versions

### ISSUE THREAD

**Issue by jab** [rtfd/readthedocs.org#1325] opened 2015-06-06 21:47 UTC
When I look at my project's inactive versions under https://readthedocs.org/projects/bidict/versions/ I see a bunch of versions I'd like completely removed from readthedocs.org. I've tried cleaning, wiping, and changing privacy level to "private", but no matter what I do, I can't seem to get them removed from https://bidict.readthedocs.org/en/XYZ.

**Comment by jab** [comment] 2015-06-06 21:50
![screen shot 2015-06-06 at 17 48 03](https://cloud.githubusercontent.com/assets/64992/8021614/3dfdec52-0c74-11e5-8ff5-dff889c3e47e.png)

You can see there I have an "inactive" version v0.2.1 (for example). I've done everything I can to remove it, but still https://bidict.readthedocs.org/en/v0.2.1 remains.

**Comment by gregmuellegger** [comment] 2015-06-29 07:12
Yes, the intend behind this is that we do not want to break existing links into the documentation. That's why there is no way yet to remove the docs for a version.

When setting a version to private, it's taking it out of all the listings in the frontend so that you won't see any new users on the inactive version but only those having the link to it.

**Comment by jab** [comment] 2015-06-29 16:57
Sometimes a docs version can get published mistakenly and should just be deleted. No links to it will break because nobody even has any. Would you consider giving admins the ability to actually delete bad versions?

**Comment by d0ugal** [comment] 2015-06-29 17:02
Maybe there should be a cooling off period. They could be deleted within a hour (or some other arbitrary period) of creation.

**Comment by mboersma** [comment] 2015-07-01 22:06
+1. We would really like to purge some old, mistakenly published versions of docs, and we are not concerned about broken links to these versions.

**Comment by wardi** [comment] 2015-07-03 14:28
We've published docs from development branches that were picked up by google and are now extremely stale but remain high in google search results. This has caused us lots of support problems as more often than not new users are looking at the wrong version of the docs.

I understand not wanting to break old links, how about allowing redirects between versions?

**Comment by tillig** [comment] 2015-07-20 22:33
We moved our docs from one repo to a different repo. The tags remained the same, but I wanted to make sure everything including the old docs are built from the new repo. Can't remove versions, can't re-point versions to different commits... :(

**Comment by ericholscher** [comment] 2015-08-26 07:28
This is a dupe of #1408 -- closing this, and you can watch for a proper solution there. This specific issue has been addressed with #1584 and will be deployed soon.

**Comment by ericholscher** [comment] 2015-08-26 07:29
Bah sorry -- thought this was a different issue. This sounds like a bug in our version syncing code -- which should be deleting old versions.

**Comment by aperezalbela** [comment] 2015-09-02 17:18
Hi, I need to delete two test docs but I can't find the option in the UI. Could you please remove them completely? Their names are: "ScrapinghubTest" and "ScrapinghubTests". They are really messing with our official docs in search engines.

Thanks in advance.

**Comment by gregmuellegger** [comment] 2015-09-07 09:46
@aperezalbela Hi, your request quite different and not related to the bug described in this ticket. Can you please open a new one so we can keep track of your issue separately and address it properly? Thanks!

**Comment by aperezalbela** [comment] 2015-09-15 05:34
@gregmuellegger sure! thanks.

**Comment by jab** [comment] 2015-11-29 14:21
Anything the user community can do to help with this issue? If you have an idea of where the buggy code might be and can point it out, maybe one of us can take a crack at a PR.

**Comment by posita** [comment] 2017-03-02 02:21
Just curious, but does RTD use the `Delete` event to get notified of branch deletions? If so, projects using manual webhooks need to make sure `Delete` events are getting sent from GH to RTD.

If my hypothesis is correct, once you've enabled `Delete` events, if the branch is already deleted on the GH project side, create a new one with the same name and then delete it. That _may_ fix this issue?

**Comment by posita** [comment] 2017-03-03 05:28
One more observation: I've found that sometimes, if one deletes a branch via GitHub's Pull Request interface (by clicking the button after merging), sometimes doing a `git pull --all && git br -a` will show that the branch still exists on GH (and in RTD). In that case, the work-around in my previous comment will likely remove both.

**Comment by ericholscher** [comment] 2017-11-09 19:23
Old versions should now be deleted automatically in at least a couple hours after deletion.

**Closed by ericholscher** 2017-11-09 19:23 UTC
Labels: Bug
