### ISSUE TITLE
Numpy compilation yields excessive build time.

### ISSUE THREAD

**Issue by KelSolaar** [rtfd/readthedocs.org#2717] opened 2017-03-10 18:43 UTC
## Details

I described the issue already in https://github.com/rtfd/readthedocs.org/issues/2697#issuecomment-285581069 but will redo it here:

Comparing the logs between successful builds and failing builds, I noticed that for old successful builds, **Numpy** was actually already installed on the build machine:

`python setup.py install --force` Section in https://readthedocs.org/projects/colour/builds/4345531/
```
Using /home/docs/checkouts/readthedocs.org/user_builds/colour/envs/develop/lib/python2.7/site-packages
Searching for numpy==1.11.1
Best match: numpy 1.11.1
Processing numpy-1.11.1-py2.7-linux-x86_64.egg
numpy 1.11.1 is already the active version in easy-install.pth
Installing f2py script to /home/docs/checkouts/readthedocs.org/user_builds/colour/envs/develop/bin
```
> Command time: 4s

For failing builds however, **Numpy** is getting compiled:

`python setup.py install --force` Section in https://readthedocs.org/projects/colour/builds/5124446/
```
Installed /home/docs/checkouts/readthedocs.org/user_builds/colour/envs/develop/lib/python2.7/site-packages/colour_science-0.3.9-py2.7.egg
Processing dependencies for colour-science==0.3.9
Searching for numpy>=1.8.1
Reading https://pypi.python.org/simple/numpy/
Downloading https://pypi.python.org/packages/0b/84/2b79ab0ca3a95442ae14847b50fc437438df8792dce1adb798695de22845/numpy-1.12.1rc1.zip#md5=091bc6601fe74d0e5a00c22c3d97d9bc
Best match: numpy 1.12.1rc1
Processing numpy-1.12.1rc1.zip
Writing /tmp/easy_install-yDsa3A/numpy-1.12.1rc1/setup.cfg
Running numpy-1.12.1rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yDsa3A/numpy-1.12.1rc1/egg-dist-tmp-rHpRne
Running from numpy source directory.
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/setup.py:366: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  self.calc_info()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  self.calc_info()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
non-existing path in 'numpy/distutils': 'site.cfg'
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable ifort
Could not locate executable ifc
Could not locate executable lf95
Could not locate executable pgfortran
Could not locate executable f90
Could not locate executable f77
Could not locate executable fort
Could not locate executable efort
Could not locate executable efc
Could not locate executable g77
Could not locate executable g95
Could not locate executable pathf95
don't know how to compile Fortran code on platform 'posix'
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
 int exp (void);
     ^
_configtest.o: In function `main':
/tmp/easy_install-yDsa3A/numpy-1.12.1rc1/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
 int exp (void);
     ^
_configtest.c:1:24: fatal error: sys/endian.h: No such file or directory
compilation terminated.
_configtest.c: In function ‘main’:
_configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
     static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) >= 0)];
                ^
```
> Command time: 384s

So this is 4s spent before versus 384s now.

* Project URL: https://readthedocs.org/projects/colour/
* Build URL (if applicable): https://readthedocs.org/projects/colour/builds/5124446/
* Read the Docs username (if applicable): colour-science

## Expected Result

I would like my builds not to timeout.

## Actual Result

My build exit due to timeout.

**Comment by humitos** [comment] 2017-03-11 00:36
The issue is that your project was requesting `numpy==1.11` and now it requires `numpy>=1.8.1`

Nothing has changed in the docker image regarding numpy: https://github.com/rtfd/readthedocs-docker-images/blob/releases/2.x/Dockerfile#L23

The version installed from Ubuntu is the 1.11. That's all.

I think this is not a bug on RTD or something that RTD should do in some way. That said, I would close this issue. Let me know if you have another idea in mind. Thanks.

**Comment by Paebbels** [comment] 2017-03-11 00:46
@KelSolaar You can specify multiple (and recursive) requirement files to specify different versions for different web services.

e.g. a normal requirements file that requires Mumpy >=1.8.1 and a version for RTD that uses the existing version (without version string) or exactly 1.11.

Requirement files can load other requirement files with option -r:
```
-r ../requirements.txt

Numpy==1.11
```

**Comment by KelSolaar** [comment] 2017-03-11 01:03
@humitos: I think it is much more complex than that, there have been no requirements changes on our end from the moment builds were successful and the moment they started to fail or be stuck:

```python
INSTALLATION_REQUIREMENTS = ['six>=1.10.0', 'scipy>=0.16.0']

PLOTTING_REQUIREMENTS = ['matplotlib>=1.3.1']

DOCS_REQUIREMENTS = ['sphinx>=1.2.2']

TESTS_REQUIREMENTS = ['coverage>=3.7.1',
                      'flake8>=2.1.0',
                      'nose>=1.3.4']

if sys.version_info[:2] <= (3, 2):
    TESTS_REQUIREMENTS += ['mock==1.0.1']

if os.environ.get('READTHEDOCS') == 'True':
    INSTALLATION_REQUIREMENTS = ['numpy>=1.8.1', 'mock==1.0.1']
```
For reference here are examples of the three states:

**Passed Build**
- https://readthedocs.org/projects/colour/builds/4345531/
- https://github.com/colour-science/colour/blob/c3f87817b68e9c79d42ad78f12dafd9d8f904f61/setup.py#L48

**Stuck Build**
- https://readthedocs.org/projects/colour/builds/4835613/
- https://github.com/colour-science/colour/blob/b1d82af250122f82919b4c54d06fdf72c069c5af/setup.py#L48

**Failed Build**
- https://readthedocs.org/projects/colour/builds/4961722/
- https://github.com/colour-science/colour/blob/db40bcd7b3ab213b5cadde15ae4a4062200eef1c/setup.py#L48

The thing that puzzle me is that I did tried a build where I was specifying the exact Numpy version I was assuming RTD is using, i.e. 1.11.1 but even for that one Numpy ended up being compiled:

- https://readthedocs.org/projects/colour/builds/5129580/
- https://github.com/colour-science/colour/blob/c12e9956a31b14dc9d8a41e6347d1c47954f4047/setup.py#L48

**Comment by humitos** [comment] 2017-03-11 16:52
I see one thing here that could bring us to the solution.

The build that does not compile numpy says:

```
Searching for numpy==1.11.1
Best match: numpy 1.11.1
Processing numpy-1.11.1-py2.7-linux-x86_64.egg
```

(it seems that uses a pre-compiled `.egg`)

The build that compiles numpy says:

```
Searching for numpy==1.11.1
Reading https://pypi.python.org/simple/numpy/
Downloading https://pypi.python.org/packages/e0/4c/515d7c4ac424ff38cc919f7099bf293dd064ba9a600e1e3835b3edefdb18/numpy-1.11.1.tar.gz#md5=2f44a895a8104ffac140c3a70edbd450
Best match: numpy 1.11.1
Processing numpy-1.11.1.tar.gz
```

So, that's probably the reason. Why it is happening this? I don't know. It seems that the pre-compiled version is not more available at https://pypi.python.org/pypi/numpy/1.11.1 :confused: 

I'm thinking on three possible workarounds:

1. allow `system packages` from your project admin configuration
1. user `pip install .` instead which I think allows wheels packages (and they are in pypi)
1. use a conda environment

**Comment by KelSolaar** [comment] 2017-03-11 19:53
@humitos : I'm quite a fan of `conda`, so **3** would make sense to me, or **2** to a lesser degree because `pip` non deterministic behaviour. **3** would also empower easy installation of *Scipy* thus not have to mock the hell out of it in *conf.py*.

Now regarding the issue at hand, i.e. my inability to get a successful build from RtD in the last 5-6 months, is there a short term solution that could be applied? I'm really keen on getting a new version of our API, there have been multiple object signature changes that require an up to date documentation.

**Comment by humitos** [comment] 2017-03-11 22:35
> is there a short term solution that could be applied?

I would say "no", since if that is the reason (pre-compiled egg doesn't exist anymore) it is out of the scope of RTD. I would try my suggestions in order from 1 to 3 because they go from the easiest one to the _hardest_ one.

**Comment by KelSolaar** [comment] 2017-03-12 00:55
**1** did worked!

![image](https://cloud.githubusercontent.com/assets/99779/23828100/6c25a47c-072b-11e7-987e-a065c6388031.png)

I'm not sure how to perform either **2** or **3** though.

**Comment by humitos** [comment] 2017-03-13 19:21
Great! OK, since this is not an issue on RTD I'm going to close it. Please, feel free to re-open it in case you consider.

**Closed by humitos** 2017-03-13 19:21 UTC

**Comment by humitos** [comment] 2017-03-13 19:33
For *2* there is an option in the admin (I don't remember the name, but is has a good help text) and for *3* there is a documentation page that explains about conda: http://docs.readthedocs.io/en/latest/conda.html

**Comment by Juanlu001** [comment] 2017-03-20 17:11
> It seems that the pre-compiled version is not more available at https://pypi.python.org/pypi/numpy/1.11.1 😕

Eggs are deprecated. There are wheels uploaded for that version, the problem is that `python setup.py install --force` ignores them. If you try that locally:

```
juanlu@nebulae /tmp $ conda create -n test36 python=3.6 -yq
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/juanlu/.miniconda36/envs/test36:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2k-1     
    pip:        9.0.1-py36_1 
    python:     3.6.0-0      
    readline:   6.2-2        
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1      
    zlib:       1.2.8-3      

#
# To activate this environment, use:
# > source activate test36
#
# To deactivate this environment, use:
# > source deactivate test36
#

juanlu@nebulae /tmp $ wget https://github.com/colour-science/colour/archive/develop.zip -q
juanlu@nebulae /tmp $ unzip -q develop.zip 
juanlu@nebulae /tmp $ cd colour-develop/
juanlu@nebulae /tmp/colour-develop $ source activate test36
(test36) juanlu@nebulae /tmp/colour-develop $ READTHEDOCS=True python setup.py install --force
[...lots of output, zip gets selected and compilation starts...]
```

So the solution instead is to use `pip install .` instead.

```
(test36) juanlu@nebulae /tmp/colour-develop :( $ READTHEDOCS=True pip install .
Processing /tmp/colour-develop
Collecting numpy>=1.8.1 (from colour-science==0.3.9)
  Downloading numpy-1.12.1-cp36-cp36m-manylinux1_x86_64.whl (16.8MB)
    100% |████████████████████████████████| 16.8MB 79kB/s 
Collecting mock (from colour-science==0.3.9)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 4.1MB/s 
Collecting pbr>=0.11 (from mock->colour-science==0.3.9)
  Downloading pbr-2.0.0-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 2.0MB/s 
Collecting six>=1.9 (from mock->colour-science==0.3.9)
  Using cached six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: colour-science
  Running setup.py bdist_wheel for colour-science ... done
  Stored in directory: /home/juanlu/.cache/pip/wheels/a7/8f/93/76c1947b9e5b136f45079fc0d858273c2859cc90bb52f42afc
Successfully built colour-science
Installing collected packages: numpy, pbr, six, mock, colour-science
Successfully installed colour-science-0.3.9 mock-2.0.0 numpy-1.12.1 pbr-2.0.0 six-1.10.0
```
