### ISSUE TITLE
How to delete account on readthedocs.org?

### ISSUE THREAD

**Issue by viliam-husar** [rtfd/readthedocs.org#292] opened 2012-11-01 16:17 UTC
I'm sorry for asking here, but there is no contact information on the site. I would like to delete my account , what is the procedure? Thank you.

**Comment by YuliaBishop** [comment] 2015-01-10 11:45
Please, delete my account. Account name YuliaBishop.

**Comment by YuliaBishop** [comment] 2015-01-10 11:49
Please, delete my account. Account name is YuliaBishop.

**Comment by Bachmann1234** [comment] 2015-04-15 21:57
@grampajoe Are you still looking at this? I can't promise anything but I was gonna look into this. I will likely stick to invalidation than full on wipe for a first pass.

**Comment by Bachmann1234** [comment] 2015-04-16 01:03
@grampajoe you still looking at this?

**Comment by Bachmann1234** [comment] 2015-04-16 01:06
@ericholscher do you have any guidance of what delete means in this context? Simply deactivating the user is fine. But for example just doing the easiest thing wont clear out their projects. 

I suspect to do this right I would need to properly I would go though and delete the projects so the docs no longer get built for example. Anything else I may be missing?

**Comment by janmaghuyop** [comment] 2015-06-15 08:37
Please, delete my account. Email is jangmaghuyop@gmail.com. I want my organization's docs not my own.

**Comment by grampajoe** [comment] 2015-06-28 11:49
@Bachmann1234 Unfortunately, I wasn't able to spend enough time on this to do anything meaningful, but I'm happy to support with review and testing.

**Comment by GeminiKLabrie** [comment] 2015-07-18 04:11
Please someone delete the account GeminiDRSoftware.

**Comment by ericholscher** [comment] 2015-08-20 16:54
Closing this as a dupe of #1408 -- we will work on this soon.

**Closed by ericholscher** 2015-08-20 16:54 UTC
Labels: Good First Bug, Sprintable

**Comment by jleclanche** [comment] 2016-01-10 18:51
@ericholscher Could you delete my account as well please? Same username as github.

**Comment by mcohoon** [comment] 2016-04-18 17:10
I would like to change my username, Didn't realize that this would be made public and I used my email address <<github_username>>@gmail.com. Can you either delete my account or help change it to something non PII?

**Comment by van-dang** [comment] 2016-05-04 08:20
Hello,
I would like to close my account in readthedocs with username 'vdnguyen'.
Can you please tell me how to do that?
Thank you very much,
Best regards,
Dang

**Comment by rrmerugu** [comment] 2016-06-06 10:48
@ericholscher  Could you please delete all the projects in my account(rrmerugu). I dont see any option to do that. If needed you may delete my account completely.  I'm worried that these projects appear in the search engines and I seriously dont want that. 

Please do the needful at the earliest .

**Comment by alkchr** [comment] 2016-08-02 10:48
Is there any reason why a new login+password pair is required in the first place? Wouldn't it be way more convenient to use Github/Bitbucket/whatever auth?

**Comment by thiagowfx** [comment] 2016-09-18 17:55
Please delete my readthedocs account! It has the same nickname as my github account.

**Comment by pille1842** [comment] 2016-09-28 22:08
Please delete my account pille1842.

**Comment by cte4X** [comment] 2017-01-30 13:27
Please delete my account. Name: craftbox555

**Comment by nickmccurdy** [comment] 2017-02-14 04:52
Please delete nicolasmccurdy.

**Comment by jleclanche** [comment] 2017-02-14 14:31
Looks like asking here is doing nothing, my account still exists.

**Comment by williamdes** [comment] 2017-02-16 17:31
Please delete WdesLaunchers .

**Comment by opensagecwru** [comment] 2017-09-23 21:14
Please delete opensagecwru@gmail.com account.

**Comment by RichardLitt** [comment] 2017-09-25 16:03
I'm locking this issue, as this is not the best place to ask for deletions. I've opened #3120 to suggest how to improve the account deletion process.
