### ISSUE TITLE
Webhook notifications URL size

### ISSUE THREAD

**Issue by jonathansberry** [rtfd/readthedocs.org#3669] opened 2018-02-23 18:41 UTC
## Details
* Page URL: https://readthedocs.org/dashboard/meerkat-hermes/notifications/
* Username: jonathansberry
* Project: meerkat_hermes

## Expected result:
I want to setup a webhook notification to our software when a readthedocs build fails. I have a url which should do the trick.  When I visit it with a simple GET request in a browser the notification works perfectly. I want to submit the URL as a webhook notification at the page in the details above.

## Actual Result
When I try to submit it as a webhook notification at the page above I get an ascii whale and the error message "Fail.  Check back in a bit!". Some playing around has made me think that my webhook URL is too long, as it is accepted if I cut parts out of it. However, the URL is only approx 530 characters long, which whilst being long, should be acceptable I would think. It is long purely because it has to include a signed access token. If I cut the access token out, the url is accepted. Here is a fairly good mockup of the webhook URL I am trying submit, including a fake access token:

`https://blah.blah.blah.info/notify?message=message_here&subject=DOCS%20FAILIURE&access_tok=DgyppMOXVVJY1I6JlTKFxl7zf2NH0Z8lwcZyy9NlSJnrmZ4AinNfn7nSHGjqGVPiU6UNzjJxDsVSP2IK8tBO-iHjIY2c47ijiN0c5J3Gpj4sPwmns8kWyLLMlNsP0Az29ZOwl3VBAm317jkFiijWJ5bDy.RG3F8Ztdt.20qM7rimwRBxIdQUg6h0-z9iywWK_Cp8DUfiyCAy0KzFgfTuVRJD4YeS57kKDqG_RB6bd_Vtj2dHvOilGmCjMLay9JeCp60xX3Er7PyGMVMcxUMh11xowGFMmhYFVWlOkk0MHLxaG2Ocmgok9I1VHRQbkDN9uJWX2E-vewf84XwGTsiTH-eo3pWiU-c7mweMPF3t9C8XlpHJ1ofpl1dSeqspzHYaDIYvkyhgTxefSNJMuIb2eF1HUQExCyFg22ibbTszDRttRnP01AO`

Are the folk at readthedocs aware of this, or able to explain why the URL won't be accepted? I can't find anything in your docs about it. 

Many thanks.

**Comment by stsewd** [comment] 2018-02-23 19:22
I can't reproduce this on my local instance, but I checked on the .org site and indeed I can see the error page (500 error). Looking the docs for Charfield (also used by UrlField), there isn't a max length, perhaps this is setting up in production? @humitos can you confirm this?

**Comment by humitos** [comment] 2018-02-26 01:16
@stsewd yeah, the same here.

The `max_lenght` by default is 200 (https://docs.djangoproject.com/en/2.0/_modules/django/db/models/fields/#URLField)

So, it should fail when validation the URL. Which is not doing for some reason at https://github.com/rtfd/readthedocs.org/blob/0e1112f96e3ba344271a44305028a811072fd10a/readthedocs/projects/forms.py#L485-L488

In production (PostgreSQL) it fails with the proper error:

    DataError: value too long for type character varying(200)

but I don't know why it doesn't fail in development (SQLite).

I think the solution here is:

* make the validation form to work
* increase the lenght of the URL to something bigger

**Comment by Chirath02** [comment] 2018-02-26 04:53
Hi @humitos I am new here, can I work on this issue?

From your description, I understood that the there the URL length is to increased(maybe 600 characters?) and there should be a form validation error if it goes beyond that.

**Comment by RichardLitt** [comment] 2018-03-02 18:18
That sounds right to me, @Chirath02. We can work out more details in your PR (#3680).

**Comment by stsewd** [comment] 2018-11-28 01:02
This was already done in https://github.com/rtfd/readthedocs.org/pull/3680 (merged)

**Closed by stsewd** 2018-11-28 01:02 UTC
Labels: Bug
