### ISSUE TITLE
redirecting https://jira-python.readthedocs.org to https://jira.readthedocs.org

### ISSUE THREAD

**Issue by ssbarnea** [rtfd/readthedocs.org#1143] opened 2015-02-05 13:28 UTC
Could you please put a permanent redirect from https://jira-python.readthedocs.org to https://jira.readthedocs.org as we ended up having the documentation in two places and this is confusing users. Thanks.

**Comment by ssbarnea** [comment] 2015-03-29 15:41
Hello! Can someone please just remove the  https://jira-python.readthedocs.org ? even without a HTTP redirect, I keep getting reports from people that we do have the same librarty documented in two places.

I already spoken with the Ben Speakmon, the former maintainer of the library and he told me that there is no option in the UI to remove the old address jira-python.readthedocs.org

**Comment by ericholscher** [comment] 2015-05-27 01:14
Seems this got fixed. Closing the issue.

**Comment by ssbarnea** [comment] 2015-07-15 12:27
Need to reopen this as is clearly not fixed.

**Comment by gregmuellegger** [comment] 2015-07-16 09:06
Reopening this based on @ssbarnea feedback.

However I for myself cannot reproduce:
```
$ curl -I https://jira-python.readthedocs.org           
HTTP/1.1 302 FOUND
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 16 Jul 2015 09:04:36 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 229
Connection: keep-alive
Location: https://jira-python.readthedocs.org/en/latest/
X-Served: Flask
X-Redirct-From: Flask
X-Deity: web01

$ curl -I https://jira-python.readthedocs.org/en/latest/
HTTP/1.1 404 OK
Server: nginx/1.4.6 (Ubuntu)
Vary: Accept-Encoding
Vary: Cookie, Accept-Language
Content-Type: text/html; charset=utf-8
Date: Thu, 16 Jul 2015 09:02:47 GMT
Transfer-Encoding: chunked
Content-Language: en
Connection: Keep-Alive
Set-Cookie: ** thpppppt **
```

So it seems that the documentation is no longer there. What responses would you expect?

**Comment by ericholscher** [comment] 2015-07-16 14:34
Sorry, I went ahead and deleted the old files. Not sure how they
reappeared, though we just did a server migration so that might have
somehow done it.

On Thu, Jul 16, 2015 at 2:06 AM, Gregor Müllegger <notifications@github.com>
wrote:

> Reopened #1143 <https://github.com/rtfd/readthedocs.org/issues/1143>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1143#event-357316569>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Closed by ericholscher** 2015-07-16 14:34 UTC
Labels: Support
