### ISSUE TITLE
Does RTD support installing from custom conda channels (e.g. conda-forge?)

### ISSUE THREAD

**Issue by anntzer** [rtfd/readthedocs.org#2446] opened 2016-10-10 18:15 UTC
## Details
- Project URL: https://readthedocs.org/projects/scikit-sparse/
- Build URL (if applicable): https://readthedocs.org/projects/scikit-sparse/builds/4496612/
- Read the Docs username (if applicable): anntzer
## Expected Result

I need to install a package (`suitesparse`) from the conda-forge channel (https://anaconda.org/conda-forge/suitesparse) to build my package (`scikit-sparse`).  `conda env export` marks the custom channel as `conda-forge::suitesparse`, and `conda env create -f environment.yml -n foo` properly installs from it -- so I was hoping the same would happen on RTD.
## Actual Result

The build immediately fails:

```
conda env create --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/scikit-sparse/checkouts/latest/environment.yml
Fetching package metadata: ....
Solving package specifications: .
Error:  Package missing in current linux-64 channels: 
  - conda-forge::suitesparse 4.5.3*
```

Even if RTD cannot afford installing from random channels for security reasons(?), perhaps conda-forge could be whitelisted?

**Comment by mzuehlke** [comment] 2016-10-12 14:05
I'm having the exact same problem:

## Details

* Project URL: https://github.com/CCI-Tools/ect-core
* Build URL (if applicable): https://readthedocs.org/projects/ect-core/builds/4505081/
* readthedocs.yml: https://github.com/CCI-Tools/ect-core/blob/master/readthedocs.yml
* environment.yml: https://github.com/CCI-Tools/ect-core/blob/master/environment.yml

Local the exact same environment.yml files works.

**Comment by mzuehlke** [comment] 2016-10-13 07:16
I have  fixed the problem for my project.
I can confirm channels are supported in the environment.yml file.

* The order is important, "default" has to be first.
* I contrast to what you get from "conda env export" the channel name as a prefix to the package name is not allowed.

**Comment by anntzer** [comment] 2016-10-13 08:22
Awesome, thanks.  I'll leave this open as perhaps the docs should be updated accordingly.

**Comment by humitos** [comment] 2017-03-09 00:51
@anntzer the `environment.yml` isn't it something specific from conda envs? I mean, the `channels` attribute (https://conda.io/docs/using/envs.html#create-environment-file-by-hand).

I'm closing this issue since I think RTD shouldn't duplicate the conda documentation for the `environment.yml` file.

**Closed by humitos** 2017-03-09 00:51 UTC

**Comment by anntzer** [comment] 2017-03-09 01:04
When I initially opened this ticket there was some difference in behavior between conda on my computer and conda on RTD (namely, the default channel needed to be listed first on RTD).  I do not know whether it is still the case though.
