### ISSUE TITLE
xlrd documentation keeps vanishing.

### ISSUE THREAD

**Issue by cjw296** [rtfd/readthedocs.org#3109] opened 2017-09-18 06:34 UTC
## Details

* Project URL: https://github.com/python-excel/xlrd
* Build URL (if applicable): https://readthedocs.org/projects/xlrd/
* Read the Docs username (if applicable): chris@python.org

## Expected Result

http://xlrd.readthedocs.io/en/latest/ should show the documentation for xlrd

## Actual Result

Shows a maze page / 404 for some users in some locations. Rebuild helped for a bit but the problem keeps coming back.

**Comment by cjw296** [comment] 2017-09-18 06:35
See: 

* #3034
* https://github.com/python-excel/xlrd/issues/229
* https://github.com/python-excel/xlrd/issues/226
* https://github.com/python-excel/xlrd/issues/222

**Comment by humitos** [comment] 2017-12-26 19:18
Hi @cjw296! It seems the problem is already solved. I'm closing this issue. Please, feel free to reopen it if you consider.

**Closed by humitos** 2017-12-26 19:18 UTC
Labels: Support

**Comment by cjw296** [comment] 2017-12-27 16:23
@humitos - what was done to solve it? Did anyone check in with the reporters above?

**Comment by humitos** [comment] 2017-12-28 00:46
@cjw296 I'm not sure, actually. A couple of changes to RTD where done and deployed since this issue was reported and I wasn't able to reproduce it again.

**Comment by cjw296** [comment] 2017-12-28 10:06
Okay, well, I'll ask people to post here and then you can re-open if there are further problems. Thanks for taking a look!

**Comment by DavidLutton** [comment] 2017-12-31 17:09
Not an issue at this time
