### ISSUE TITLE
Documentation stuck in 'cloning' state

### ISSUE THREAD

**Issue by virtuald** [rtfd/readthedocs.org#2795] opened 2017-04-14 13:38 UTC
## Details

* Project URL: exaile.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/exaile/builds/
* Read the Docs username (if applicable): virtuald

## Expected Result

Build to... build.

## Actual Result

4 builds appear to be stuck in 'cloning' state.... which is strange, because a builds were working fine earlier.

**Comment by bwohlberg** [comment] 2017-04-14 15:15
I'm experiencing the same problem with the docs for project [sporco](http://sporco.readthedocs.io). One of the builds has been stuck in 'cloning' state for 36 hours.

**Comment by dpdani** [comment] 2017-04-14 17:05
Same here with 5 builds in `Cloning` state. The oldest one being about 3 hours old.
- #5290405
- #5290768
- #5290989
- #5291057
- #5291066

**Comment by virtuald** [comment] 2017-04-16 14:19
New builds are working now, but old builds still stuck in 'cloning' state. Feel free to close.

**Comment by bwohlberg** [comment] 2017-04-16 14:49
Based on previous bug reports it looks as if this problem has occurred previously as well; it's probably worth trying to locate the cause rather than just closing the issue.

**Comment by humitos** [comment] 2017-04-18 17:55
These kind of errors I think are because there was a problem in the `git clone` command, and exception was raised, the process ended and the status wasn't communicated, so it seems that it's still cloning.

Common errors are:
* the repository is private and requires username/password to be cloned
* temporary network error
* wrong git url
* error in `.gitmodules` files

I think that a good enhancement would be that instead of showing `Cloning`, RTD should show the error message returned by the `git clone` command. For example,

    fatal: could not read Username for 'https://bitbucket.org': No such device or address

**Comment by agjohnson** [comment] 2017-04-18 18:30
I agree, we need to be more defensive around the clone stage. We should also be assuming a build has failed after a certain threshold, builds shouldn't be sticking around as "cloning" or any other temporary state.

The first case is easier to catch -- perhaps just some generic exception or exit code handling is all that is needed. It would be best if we can ensure state here, and avoid having to alter this state afterwards.

**Comment by humitos** [comment] 2017-04-18 18:50
Another issue that talks about the ability of killing this blocked in some status: #2471

**Comment by bcb** [comment] 2017-07-14 17:32
This is still a problem. Stuck at "cloning".

![screen shot 2017-07-15 at 03 29 08](https://user-images.githubusercontent.com/134581/28223202-d877cada-690d-11e7-925a-b70023a80823.png)

**Closed** 2017-12-14 20:59 UTC
Labels: Enhancement, Needed: design decision
