### ISSUE TITLE
Navigation is stuck / readthedocs is unusable in latest Chrome

### ISSUE THREAD

**Issue by Fohlen** [rtfd/readthedocs.org#4088] opened 2018-05-14 16:58 UTC
## Details

The site navigation is stuck / scrolling is impossible.
*Any*
*Stable, I assume*

## Expected Result

I should be able to use the site just fine.

## Actual Result

In Chrome readthedocs.org and *any* of it's subdomains is totally unusable for me. The navigation is stuck, meaning that I cannot scroll the page (it is indeed frozen). This occurs on `Version 66.0.3359.139 (Official Build) (64-bit), OSX variant`. It does not occur on my Firefox or my Safari.
I already tried clearing cache on `*.readthedocs.org` with no sufficient changes. Any idea what could be done here? I also attached a [vimeo video](https://vimeo.com/269680523). I am actually trying to scroll with mouse and UP/DOWN keys, but QuickTime wouldn't capture that.

**Comment by stsewd** [comment] 2018-05-14 17:04
Duplicate of https://github.com/rtfd/readthedocs.org/issues/4066

**Closed by stsewd** 2018-05-14 17:04 UTC
