### ISSUE TITLE
Linking multiple projects to the same repo causing significant version problems

### ISSUE THREAD

**Issue by mradamcox** [rtfd/readthedocs.org#3763] opened 2018-03-10 22:16 UTC
_I'll preface this by saying that having two projects built from the same repo is not ideal, but it seemed like a clean workaround for not being able to do a full domain redirect from one (the original docs) to the new one._

## Details

* Project URL: arches.readthedocs.org
* Project URL: arches4.readthedocs.org
* Build URL (if applicable):
* Read the Docs username (if applicable): mradamcox 

## Expected Result

I'm having trouble with two projects: `arches` used to be pointed at a bitbucket repo, and `arches4` points to the current code base: https://github.com/archesproject/arches. I want both projects to be identical, now building from a new repo where I have consolidated all documentation into one place, with branches for each release: https://github.com/archesproject/arches-docs.

## Actual Result

The problem is that even after I change the URL to the new repo, deactivate all of versions (and wipe them), disable any previous github integrations, and make new webhooks, the tag release SHAs are still associated with many versions in each repo. Most strangely, the new project `arches` now has versions designated for the tags from the original code base, from which that project was never built in the first place. This causes a failed build on `stable` like this https://readthedocs.org/projects/arches/builds/6867530/ because in reality that SHA does not exist in the arches-docs repo.

It seems to me that this may be related to https://github.com/rtfd/readthedocs.org/issues/3743, because ultimately what I really need is to just wipe all of the version-related metadata (SHA, name, etc) in both of these projects and start brand new. Based on this ticket https://github.com/rtfd/readthedocs.org/issues/3192 I have deleted and recreated the webhooks (and waited a day) but the weirdness remains.

**Comment by stsewd** [comment] 2018-03-11 06:41
mmm, I think this is related to #3729 and #3714, both users were able to solve this recreating the rtd project.

@humitos probably a bug caused by a recently regression or just coincidence? Three similar reports this week.

**Comment by mradamcox** [comment] 2018-03-13 18:08
Deleting and recreating the projects solved the problems I was having. I'll leave closing this ticket up to others, as I'm not sure if it actually points to a new or known bug.

**Comment by stsewd** [comment] 2018-04-09 05:46
I think this was because of this bug #3887.

**Comment by humitos** [comment] 2018-04-09 16:44
Great! I'm closing this one since the original issue is already fixed and we have a fix proposal for the general rule. Thanks for reporting and help us to debug!

**Closed by humitos** 2018-04-09 16:44 UTC
Labels: Support
