### ISSUE TITLE
Site not serving under custom domain: PhpSpec.net

### ISSUE THREAD

**Issue by ciaranmcnulty** [rtfd/readthedocs.org#2067] opened 2016-03-13 11:28 UTC
Hi

Hitting phpspec.net gives the 'maze' 404 page.

I haven't edited our RTD settings, although I noticed there's no custom domain.

Our DNS is handled by CloudFlare who CNAME to RTD, again I'm not aware of anything changing there.

* Project: phpspec

**Comment by ciaranmcnulty** [comment] 2016-03-13 11:38
I've resolved this now by adding a 'custom domain' in our project's settings.

Possibly something changed in the readthedocs config? I have a memory of adding this when we first set up the docs, but can't be 100% sure.

I can give more feedback on our DNS setup if it helps debug - possibly the fact we use a CDN is part of it?

**Comment by agjohnson** [comment] 2016-03-14 18:03
Correct, a custom domain is the way to solve this. We were trying to infer this using a slug lookup previously, but have just recently removed the code recently as it was buggy. My guess is your subdomain was resolving due to the buggy behavior.

**Comment by ericholscher** [comment] 2016-03-14 22:17
The issue is that you were using a CDN in front of the page. This wasn't an officially supported method of using a CNAME. Our old hosting infrastructure had cached your domain name, so it continued to work. When we migrated to a new way of hosting CNAME's, the old record was lost, and there was no way to for us to track this down.

Now that we have proper Domain objects, this will work properly with CDN's and SSL hosts sitting in front, which is what you have with Cloudflare.

**Closed** 2016-03-14 22:18 UTC
Labels: Support
