### ISSUE TITLE
Malformatted bottom navigation section

### ISSUE THREAD

**Issue by bwohlberg** [rtfd/readthedocs.org#4064] opened 2018-05-06 15:27 UTC
## Details

* Read the Docs project URL: http://sporco-cuda.readthedocs.io/en/latest/index.html

The bottom navigation section that is usually collapsed into a small box with the text "v: latest" is displayed in expanded form at the bottom of the page, without any of the usual styling. Comparing the html source of this page and for those that are displayed correctly, the only obvious differences seem to be a missing stylesheet 

> \<link rel="stylesheet" href="https://media.readthedocs.org/css/badge_only.css" type="text/css" />

and a missing script section

>  \<script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     '0.1.9b1',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true,
        SOURCELINK_SUFFIX: '.txt'
      };
    </script>

that are present in all of the pages that are displayed correctly. There is nothing obviously unusual in the docs configuration file that might be responsible for these being omitted.

**Comment by davidfischer** [comment] 2018-05-08 20:25
I'm investigating...

I can see that the problem is on the index page: http://sporco-cuda.readthedocs.io/en/latest/index.html
But not on any other pages: http://sporco-cuda.readthedocs.io/en/latest/install.html

This is pretty bizarre and I haven't found out why. That CSS should be added to all the pages.

**Comment by stsewd** [comment] 2018-05-08 20:44
@davidfischer this is the same issue as #3715, I have a patch that fixes this https://github.com/rtfd/readthedocs.org/pull/4054

**Comment by davidfischer** [comment] 2018-05-08 21:00
I can confirm that this is duplicate of that issue. The workaround in that ticket or removing the `sphinx_tabs` extension will do the trick. Hopefully we can get that fix merged soon.

**Comment by bwohlberg** [comment] 2018-05-09 03:45
@davidfischer: Thanks for the very fast response. Unfortunately the workaround in #3715 doesn't work: it fixes the problem reported here, but corrupts other aspects of the page style. No problem, though, since it looks as if this will be fixed soon.

**Comment by stsewd** [comment] 2018-05-09 04:12
@bwohlberg since the affected page is the index page of your docs, you can create a page with a name previous to `index` like `a_foo.rst` in the meantime, the problem only affects to the first page (alphabetically ordered) of the docs.

**Comment by bwohlberg** [comment] 2018-05-10 00:59
@stsewd: Thanks for the suggestion - I'll give it a try.

**Comment by stsewd** [comment] 2018-05-10 18:40
Closing this as a duplicate of #3715 I hope the fix will be merged soon.

**Closed by stsewd** 2018-05-10 18:40 UTC
