### ISSUE TITLE
python3.5 ?

### ISSUE THREAD

**Issue by parmentelat** [rtfd/readthedocs.org#2523] opened 2016-11-20 17:24 UTC
## Details

* Project URL: https://github.com/parmentelat/asynciojobs
* Build URL (if applicable): https://readthedocs.org/projects/asynciojobs/builds/
* Read the Docs username (if applicable): parmentelat

## Expected Result

*A description of what you wanted to happen*

My code is based on `asyncio` and uses a lot of `async def foo()` and `await coro()` syntax that was introduced in python3.5; so for sphinx to be able to autodoc this code, it needs to run at least python3.5.

## Actual Result

*A description of what actually happened*

At first I have struggled a bit to find about [the advanced settings page](https://readthedocs.org/dashboard/asynciojobs/advanced/) where I chose CPython3.x, but this now seems to give me 3.4.

As a result of course, sphinx crashes when trying to build. 

Is there anything I can do with the settings of my project to get a python3.5 instead ?
Or does this necessarily require an upgrade from on platform side ?

Thanks and my apologies if this is not the right channel for this question.

**Comment by kdelwat** [comment] 2017-01-04 00:06
Any update on this issue? I'm also trying to document a project with `async` and `await`.

**Comment by agjohnson** [comment] 2017-01-05 06:47
Closing this as a duplicate of #1990, feel free to watch there for updates.

**Closed by agjohnson** 2017-01-05 06:47 UTC
