### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by leastprivilege** [rtfd/readthedocs.org#2915] opened 2017-05-27 18:26 UTC
https://readthedocs.org/projects/identityserver4/builds/5478795/

that's all I got...

**Comment by vmalloc** [comment] 2017-05-30 14:30
Could be related to my issue https://github.com/rtfd/readthedocs.org/issues/2849

**Comment by agjohnson** [comment] 2017-05-30 23:35
Duplicate of #2849 and others. Closing this here, but the issue was a server issue that has been resolved.

**Closed by agjohnson** 2017-05-30 23:35 UTC
