### ISSUE TITLE
Browsing the PRAW page, it's not indexed

### ISSUE THREAD

**Issue by jokoon** [rtfd/readthedocs.org#1897] opened 2016-01-05 12:58 UTC
I have tried to find stuff in this doc, and honestly it's completely unusable, because there is no clear list of what is available.

Why isn't there some concise class list and method list at the beginning? The page is 3 stories long.

Maybe it's the responsibility of the people posting the doc ? I don't know, but couldn't it be fixed by readthedocs ?

**Comment by agjohnson** [comment] 2016-01-06 03:29
Not exactly sure what the issue is here. I see API reference documentation at http://praw.readthedocs.org/en/stable/pages/code_overview.html

Either way, we only generate what we're given, projects are free to author their docs however they wish.

Closing this as this isn't an issue with Read the Docs.

**Closed by agjohnson** 2016-01-06 03:29 UTC
