### ISSUE TITLE
Build fail without any error in mkdocs projects

### ISSUE THREAD

**Issue by SongChiYoung** [rtfd/readthedocs.org#4380] opened 2018-07-17 04:32 UTC
## Details

* Read the Docs project URL: https://readthedocs.org/projects/deep-learning-basic
* Build URL (if applicable): https://readthedocs.org/projects/deep-learning-basic/builds/7496145/
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*
Build

## Actual Result

*A description of what actually happened*

When I was re-build my projects, but it cannot build with error
```
Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7496145).
```

But, my git wasnot change anything after success to build(https://readthedocs.org/projects/deep-learning-basic/builds/7446956/).
I did that, only change to CPython 3 from 2. but, re-change to CPython2 but it still fail.

**Comment by SongChiYoung** [comment] 2018-07-17 04:38
I was check other project (I have commit permissions), and change only one char.

But it was build-fail too..

both mkdocs version.
http://readthedocs.org/projects/ybigta-data-science/

maybe.. It is global mkdocs system error in the ReadTheDocs.org

**Comment by stsewd** [comment] 2018-07-17 04:42
I was able to build your project in my local instance, I'm not sure what the problem is :/.

**Comment by SongChiYoung** [comment] 2018-07-17 04:49
@stsewd If you can, check other projects by mkdocs. (with readthedocs.org)
I think.. maybe... all of them cannot build now...
(I was double(triple?) check other project too. and it cannot build with same log)

**Comment by stsewd** [comment] 2018-07-17 04:54
The only thing I can see in my local environment: the step that fails on rtd is `cat mkdocs.yml`. I checked your repo and it has a `mkdocs.yaml` file (note the extension). Not sure why it doesn't fail locally.

**Comment by SongChiYoung** [comment] 2018-07-17 05:00
Here with nice `mkdocs.yml` file version.

https://github.com/PrivateOrganizationDeepLearning/DeepLearning
https://readthedocs.org/projects/poddeeplearning/builds/
https://readthedocs.org/projects/poddeeplearning/builds/7496229/

Yep, It couldnot build now too...

**Comment by SongChiYoung** [comment] 2018-07-17 05:02
And... now change yaml to yml.

But, it couldnot build yet...

https://readthedocs.org/projects/deep-learning-basic/builds/7496237/
https://github.com/YBIGTA/DLB

**Comment by stsewd** [comment] 2018-07-17 05:10
Sorry, I can't help. I'm not able to replicate locally and I don't have access to the logs, we need to wait for a maintainer with access to the logs to know what's happening.

**Comment by Schnitzel** [comment] 2018-07-17 07:42
Got the same problem here: 
https://readthedocs.org/projects/lagoon/builds/7496631/

Worked yesterday without issues:
https://readthedocs.org/projects/lagoon/builds/7489932/

Thanks for fixing :)

**Comment by SongChiYoung** [comment] 2018-07-17 07:51
@Schnitzel Yep, maybe, #4381 is same issue too.

That issue has many other try. But he could not solve the problem either.

Down for the ease view with other issue
> 
> gregurco commented an hour ago • 
> Details
> Hello.
> I have a problem. Build failed with next message:
> 
> You are using pip version 9.0.1, however version 10.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command
> Link: https://readthedocs.org/projects/jobeet-tutorial/builds/7495068/
> 
> I tried to require pip with version 10.0.1 and it failed too: https://readthedocs.org/projects/jobeet-tutorial/builds/7496426/
> After that I tried to upgrade python to version 3.7 and it failed too: https://readthedocs.org/projects/jobeet-tutorial/builds/7496430/
> 
> The last success build: https://readthedocs.org/projects/jobeet-tutorial/builds/7495006/
> 
> Yesterday it was ok.
> Thanks.
>

**Comment by caa06d9c** [comment] 2018-07-17 10:45
I have the same problem: [Broken build](https://readthedocs.org/projects/caa06d9c-datamodels/builds/7497409/). git reset to older  commit not helping.

**Comment by DRamalho92** [comment] 2018-07-17 10:50
Hi,

I have the same problem on my project. Yesterday made a build as normal. Today, it is not working - [https://readthedocs.org/projects/davidtest123/builds/](Build)

**Comment by gregurco** [comment] 2018-07-17 11:08
It can be related to new release: https://github.com/rtfd/readthedocs.org/releases/tag/2.6.0 It was done at the same time as builds started to fail.

**Comment by paulmueller** [comment] 2018-07-17 15:59
Same thing here:
https://readthedocs.org/projects/drymass/builds/7498854/

**Comment by SongChiYoung** [comment] 2018-07-17 16:37
@stsewd exactly, only mkdoc has that issue, right? :(
@paulmueller's project was looks sphinx.

So, now readthedocs.org is only viewer...
It cannot build something, now.

Am I the only person who thinks the situation is serious now?

**Comment by stsewd** [comment] 2018-07-17 16:42
@SongChiYoung the rtd team have identified the problem and are planning a deploy today. The sphinx problem could be related but I haven't check.

**Comment by SongChiYoung** [comment] 2018-07-17 16:45
@stsewd  Thx to your information, I really appreciate it. I really appreciate your work. I really appreciate your help.

**Comment by humitos** [comment] 2018-07-17 16:46
Hi all! We just found one possible issue with yesterday's deploy and we are working to solve it and re-deploy with the fix today.

I'm sorry for the issues you are having. I will let you know when this is done.

**Comment by wwiv** [comment] 2018-07-17 18:03
Thanks for the update and running a great service!

**Comment by grigi** [comment] 2018-07-17 19:55
My Sphinx build is failing with no error. It just appears to stop.
https://readthedocs.org/projects/tortoise-orm/builds/7500692/

**Comment by humitos** [comment] 2018-07-17 20:41
All these issues should be fixed with the new deploy from today. Hope everything goes well in your new builds from now.

I'm closing this issue here after re-triggering a couple of projects linked here and found that they are passing without problems. In any case that you find your project is still failing, please open a new issue with more details.

Thanks you all!

**Closed by humitos** 2018-07-17 20:41 UTC
Labels: Support
