### ISSUE TITLE
HTML build fails and has empty Build Standard Output

### ISSUE THREAD

**Issue by e9t** [rtfd/readthedocs.org#1169] opened 2015-02-27 11:26 UTC
I am trying to build the docs I have at a GitHub repo here: https://github.com/konlpy/konlpy

The docs for the previous version (v0.4.2) built properly
and I have made some very minor adjustments on the docs since then,
but now the builds for the HTML builds are failing while PDF build successes.

The problem is that I am getting [an empty Build Standard Output](https://readthedocs.org/builds/konlpy/2367754/), so it's difficult to figure out a solution.

<pre>
Built: Feb. 27, 2015. 5:04 a.m.
State: Finished
Outcome: Failed (Status Code: 0)
Version: latest
Type: html
Build Standard Output
</pre>

The html build in my local machine works fine as well.
Are there any possible issues here?

**Comment by e9t** [comment] 2015-02-27 11:32
Could this fail be related to my [recent commit](https://github.com/konlpy/konlpy/commit/5e8eb97d4bae5b7cd81132c04294b63fa77dd65c) that changes setup.py to use `extras_require` instead of `install_requires`?

This probably wouldn't relate to creating docs, but the time the build started to fail is about the time I pushed this commit.

**Comment by e9t** [comment] 2015-02-27 11:47
I guess it failed because of the reason I've just stated above.
I checked the option below at https://readthedocs.org/dashboard/konlpy/advanced/, and now the build succeeds!

<pre>
Use virtualenv:
 Install your project inside a virtualenv using setup.py install
</pre>

**Comment by e9t** [comment] 2015-02-27 11:50
But unfortunately, the build for my translation page still fails... :(
Maybe installing via setup.py was not a proper solution?
https://readthedocs.org/builds/konlpy-ko/2367965/

**Comment by e9t** [comment] 2015-02-27 15:42
Yes, I still have the install via setup.py enabled, and the original English is failing again.
https://readthedocs.org/builds/konlpy/2368805/

**Comment by vitaut** [comment] 2015-02-27 17:38
The same issue here: https://readthedocs.org/builds/breathe/2369183/

Standard output is empty and Status Code is 0 (shouldn't it indicate success?)

The docs build fine from the command line.

**Comment by gregmuellegger** [comment] 2015-07-10 13:36
@e9t @vitaut seems like the issue is resolved for your projects, I'm closing this ticket for now.
Please open a new one if you still experience troubles with the builds.

**Closed by gregmuellegger** 2015-07-10 13:36 UTC

**Comment by e9t** [comment] 2015-07-10 13:46
No, I haven't seen the issue these days either. Thanks a ton!
