### ISSUE TITLE
Project import not working

### ISSUE THREAD

**Issue by takluyver** [rtfd/readthedocs.org#1900] opened 2016-01-06 18:42 UTC
Having just filed #1899, I noticed a more serious issue with the new project import page. When I click the big `+` button, nothing happens. There's nothing showing up in the JS console, though I can see there's an event listener in the inspector.

![screenshot from 2016-01-06 18 41 27](https://cloud.githubusercontent.com/assets/327925/12151055/13d0283a-b4a5-11e5-8396-dff681c306b7.png)

This is in Firefox 43 on Linux.

**Comment by agjohnson** [comment] 2016-01-06 20:24
Duplicate of #1773

**Closed by agjohnson** 2016-01-06 20:24 UTC
