### ISSUE TITLE
Deleting and recreating project doesn't clear caches

### ISSUE THREAD

**Issue by ajdavis** [rtfd/readthedocs.org#1264] opened 2015-05-09 16:20 UTC
So I have three problems with RTD's caching. Sorry for the bad bug report, please accept my apology.

One is, I used to mark a "stable" version of my "Motor" project by just force-pushing a tag named "stable". That never worked well with RTD, I tended to have to hit "wipe" and "rebuild" over and over for a while before RTD would notice the tag had moved. I hear I should've used a branch instead, that makes sense but I never tried it.

Recently I heard you were doing semver, so I just deleted the "stable" tag and hoped RTD would parse my latest tag version (currently "0.4.1") instead. After waiting a few minutes to see if that would happen I gave up and just deleted and recreated the whole project.

Now we've got one more caching issue. If you refresh this page a bunch: http://motor.readthedocs.org/en/stable/changelog.html , it often still shows the changelog for version 0.4, the previous release, as if RTD remembers the old "stable" tag. Even though I've deleted that tag from GitHub, deleted and recreated the whole project, and repeatedly hit the "wipe" URL.

I feel like if I force-move a tag in GitHub, wipe the build dir on RTD and rebuild, RTD should see the change. I also think that if I remove the tag, tell RTD to use semver, and build the project, RTD should parse my latest release tag and call it "stable". And finally, if these cache bugs mean that the only way to update RTD is to delete and recreate a project, then I think that deleting a project should clear all related caches, so that recreating the project really starts from a clean slate.

Thanks. =)

**Comment by gregmuellegger** [comment] 2015-07-06 11:23
Yes, currently deleting a project does not remove the actual docs from the servers. The reason is that we do not want to break any existing links to valuable documentation :)

We need to decide what actually should happen when a project or a version is deleted. And regarding semver: we are currently develop a fix for the version parsing. This will honor the version numbers better and fix the detection of what version is the stable one. So stay tuned and watch #1384 for updates on that.

**Comment by ajdavis** [comment] 2015-07-06 11:28
Thanks for the info!

**Comment by ericholscher** [comment] 2015-08-26 07:26
This is a dupe of #1408 -- and it should be fixed with a recent commit that will be deployed soon. Closing it now and you can track #1408 for a proper resolution.

**Closed by ericholscher** 2015-08-26 07:26 UTC
Labels: Bug
