### ISSUE TITLE
Conda build of `environment.yml` broke without changing yml file

### ISSUE THREAD

**Issue by willingc** [rtfd/readthedocs.org#2704] opened 2017-03-08 00:53 UTC
## Details

* Project URL: https://readthedocs.org/projects/jupyterhub/
* Build URL (if applicable): 
     - https://readthedocs.org/projects/jupyterhub/builds/5109237/
     - https://readthedocs.org/projects/jupyterhub/builds/5118463/
* Read the Docs username (if applicable): willingc

## Expected Result

I expected the docs to build without error after adding a new doc source file in Sphinx. The `environment.yml` for conda build was unchanged from yesterday where the docs built correctly.

## Actual Result

Doc build is currently failing since it is unable to import yaml. I made no changes to the `environment.yml` file from the last successful build yesterday.

On a test account, I tried to resolve by adding pyyaml to the `environment.yml` file with no success. 

Was the conda build container changed in the past day or two?

Thanks!

<img width="814" alt="screenshot 2017-03-07 16 22 28" src="https://cloud.githubusercontent.com/assets/2680980/23684837/e2bd64d2-0355-11e7-8613-7b0108e9f253.png">

**Comment by ericholscher** [comment] 2017-03-08 01:41
yep -- this is a dupe of #2651, with a bunch of flailing and back and forth :)

**Closed** 2017-03-08 01:44 UTC

**Comment by willingc** [comment] 2017-03-08 01:47
@ericholscher Thanks! Sorry, I didn't notice the other issue. Ping me if you want me to test in the morning :-)
