### ISSUE TITLE
Needs Fix Overflow-x

### ISSUE THREAD

**Issue by cagataycali** [rtfd/readthedocs.org#4324] opened 2018-07-03 14:13 UTC
## Details

* Read the Docs project URL: *.readthedocs.io

## Expected Result

When I open `*.readthedocs.io` docs my browser can not scroll.

ENV:
Chrome: `Version 67.0.3396.99 (Official Build) (64-bit)`

Device: `Mac OS X`

## Actual Result

![POC](https://media.giphy.com/media/2Wf4AbZlqJvpW1RUQ5/giphy.gif)
I fixed with delete `overflow-x: hidden;` property from html body.

Note: I can scroll other browsers like as Opera, Firefox, Safari but Chrome does not responding scroll event.

**Comment by davidfischer** [comment] 2018-07-03 15:45
I believe this is a dupe of https://github.com/rtfd/readthedocs.org/issues/4066. According to that ticket:

    Disabling 'Experimental Web Platform features' flag at chrome://flags/ seems to fix the issue in Chrome 66.

However also according to that ticket, this was supposed to be fixed in Chrome 67. I am using the identical browser version to you also on MacOS without issue so I think it is related to the experimental feature.

**Comment by cagataycali** [comment] 2018-07-03 15:46
What a good catch, I’ll try this solution and update my issue 🔥

**Comment by davidfischer** [comment] 2018-07-03 15:48
According to the underlying [Chromium ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=838494), the issue is still present in 67.

**Comment by davidfischer** [comment] 2018-07-03 21:33
I'm going to close this out but feel free to re-open if it is still an issue.

**Closed by davidfischer** 2018-07-03 21:33 UTC
Labels: Bug, Design
