### ISSUE TITLE
Builds hang indefinetely in "build" phase

### ISSUE THREAD

**Issue by ankostis** [rtfd/readthedocs.org#2509] opened 2016-11-16 10:13 UTC
## Details
Builds appear to be stuck without any errors reported, but site is generated.
I'm afraid they might be wasting RTD resources.

Is there something I can do to help or debug what is the cause of the deadlock?

* Project URL:  http://co2mpas-ta.readthedocs.io/
* Build URL (if applicable): many, e.g. https://readthedocs.org/projects/co2mpas-ta/builds/4671459/
* Read the Docs username (if applicable): ankostis

## Expected Result
The build to finish, successful or failed

## Actual Result

But instead [all builds](https://readthedocs.org/projects/co2mpas-ta/builds/) are stuck in "building" phase, although the site is visible.
![image](https://cloud.githubusercontent.com/assets/501585/20343072/4c22db84-abed-11e6-8934-0de6859df46f.png)

**Comment by agjohnson** [comment] 2016-11-16 18:30
No need to worry, there is no contention for these build resources. The build simply died. Closing this as a duplicate of a number of issues.

**Closed by agjohnson** 2016-11-16 18:30 UTC
