### ISSUE TITLE
Build passed but unable to see documentation

### ISSUE THREAD

**Issue by RishabhRawat** [rtfd/readthedocs.org#2356] opened 2016-08-05 19:32 UTC
## Details
- Project URL: https://github.com/RishabhRawat/schematicGenerator
- Read the Docs username (if applicable): karnank
## Expected Result

I am trying to build the docs. The build passes successfully and I see the docs...
Docs location: http://schematik.readthedocs.io/en/latest/
## Actual Result

The build passes successfully but at the end I am not able to see anything at the "Docs location"
It says SORRY: This page does not exist yet. 
## More Information

I had earlier made another documentation (http://schematiks.readthedocs.io/en/latest/) with same repository, which had some naming issues so I deleted those and recreated the project with a different naming. 

Even though I had deleted the older project, that documentation link is still active. (Though it doesn't update the older documentation on build either)

**Comment by samuelyeewl** [comment] 2016-08-05 22:57
I'm having the same problem at https://readthedocs.org/projects/specmatch-emp/ where the builds are passing but no docs are appearing.

**Comment by nomatics** [comment] 2016-08-06 00:22
+1

**Comment by brettcannon** [comment] 2016-08-06 04:25
I noticed that at least for http://sans-io.readthedocs.io/ the issue is manifesting itself as having none of the versions listed as not built under Versions in the admin even though Builds doesn't show any errors.

**Comment by Len-PGH** [comment] 2016-08-06 05:02
I have the same problem.  Builds are passing but content is not updating. Build #4268641 was the last time content updated

**Comment by csadorf** [comment] 2016-08-06 05:28
I'm experiencing the same problem.

**Comment by agjohnson** [comment] 2016-08-06 05:35
Yeah, noticing some issues with our sync queue. Looking into the issue now.

**Comment by AnoopAlias** [comment] 2016-08-06 07:24
Changes were not being reflected. I deleted the project and still the html is showing up at http://ndeploy.readthedocs.io/

**Comment by agjohnson** [comment] 2016-08-06 09:48
Web sync queue was backed up and chugging along. I worked to free up the queue, should be back to normal in about an hour. Closing this ticket, feel free to reopen if triggering new builds doesn't work as expected tomorrow.

Thanks for the report everyone!

**Comment by cedwards** [comment] 2016-08-06 22:43
Did this crop up again today? My docs don't seem to be updating...

**Comment by agjohnson** [comment] 2016-08-07 03:57
@cedwards it did, I had to nurse the servers back again this afternoon. Rackspace gave us a potential fix however, so hopefully this is mostly resolved.

**Comment by brettcannon** [comment] 2016-08-07 16:34
Looks like it's happening again; just did an update with a successful build and the changes aren't showing up on the site: https://github.com/brettcannon/sans-io/blob/master/index.rst compared to http://sans-io.readthedocs.io/

**Comment by cedwards** [comment] 2016-08-07 16:40
noticing the same thing again

**Comment by RishabhRawat** [comment] 2016-08-07 19:24
I am also seeing the same issue again

**Comment by agjohnson** [comment] 2016-08-08 03:40
Thanks for the update everyone. Seems the previous fix did not stick, the queue backed up again earlier. I put a more permanent fix in place this time. It seems the root cause was a bug somewhere between systemd and logind, causing file sync operations through ssh to slow to a crawl.

**Comment by KennethNagin** [comment] 2016-08-23 15:52
I am having a similar problem.  My build has passed but I can not view the page.  Its message is "Sorry the page does not exist yet".  The url is http://fiware-docker-container-service.readthedocs.io/en/latest/.

**Comment by jwogrady** [comment] 2016-10-26 18:22
+1 passing build, but getting "this page does not exist error."  Wiping the version and rebuilding did not work.

**Comment by dagit** [comment] 2017-02-22 17:56
I'm having this problem with my project too. Builds are passing, but the I get a 404 when I try to view them. Yet, I can download them as a zip file.

**Comment by redbeard28** [comment] 2017-04-05 05:36
I'm having the same problem with my project to. Builds are passing, but I get the 404 page:
http://install-terraform-packer.readthedocs.io/en/latest/ 
Do you have the same issue?
regards,

**Comment by maciejpolanczyk** [comment] 2017-04-16 10:39
yes, same issue: http://django-business-rules.readthedocs.io/en/latest/?

**Comment by hathix** [comment] 2017-05-10 02:00
Same issue. My builds are passing (and the PDFs are being compiled), but the docs page still shows a 404.

<http://searchbetter.readthedocs.io/en/latest/>

**Comment by akshaynagpal** [comment] 2017-05-18 08:02
Same issue.
My project URL is https://readthedocs.org/projects/w2n/ and the page that should show the docs is http://w2n.readthedocs.io/en/latest/ .

Any help is appreciated.

**Comment by MathMagique** [comment] 2017-06-05 21:35
Same issue, my project URL is http://turbodbc.readthedocs.io/en/latest/

**Comment by dave4jr** [comment] 2017-06-05 22:33
Same issue for me, http://cairn-documentation.readthedocs.io/en/latest/

**Comment by ianseyer** [comment] 2017-07-28 19:57
+1

same issue

**Comment by rfbrondum** [comment] 2017-10-11 10:40
Same issue happening today.

**Comment by agjohnson** [comment] 2017-10-12 22:15
@rfbrondum we'll need more information if this is happening. please open a new ticket.

**Closed by agjohnson** 2017-10-12 22:15 UTC
Labels: Operations, Priority: High

**Comment by dialex** [comment] 2017-11-05 15:26
Same issue today

**Comment by RichardLitt** [comment] 2017-11-06 13:43
@dialex Thanks for letting us know. Please open a new ticket.

**Comment by arkoblog** [comment] 2017-11-07 10:23
Same issue, online documentation doesn't reflect the latest changes.

**Comment by RichardLitt** [comment] 2017-11-07 12:56
@arkoblog We'll need more information if this is happening. Please open a new ticket. Thanks.

**Comment by microprediction** [comment] 2020-02-28 00:24
https://colliderfeed.readthedocs.io/en/latest/.  Not showing. Build is fine.

**Comment by DanEdens** [comment] 2020-08-06 01:31
Sorry I know this is out of comment guidelines but I can't help it after the comments :D 

"they've got their phones and they're like 'ugh, it won't--' GIVE IT A SECOND! It's going to SPACE! Can you give it a second to get back from space?? Is the speed of light too slow for you?!"
-- louis CK

**Comment by PriyanshBordia** [comment] 2020-12-21 06:54
Having the issue maze not foundeven after build passed many times.

**Comment by codebyaryan** [comment] 2021-08-23 11:20
I am also facing the same issue right now.

**Comment by astrojuanlu** [comment] 2021-08-23 13:45
This issue was originally a temporary infrastructure problem that affected our site (see https://github.com/readthedocs/readthedocs.org/issues/2356#issuecomment-238015550 and https://github.com/readthedocs/readthedocs.org/issues/2356#issuecomment-238135468). That problem was already solved and it is unlikely that it is affecting your project now.

If you are experience problems with your project, please [open a new issue](https://github.com/readthedocs/readthedocs.org/issues/new/choose) or send us a support request.
