### ISSUE TITLE
Support iPython nbconvert

### ISSUE THREAD

**Issue by hannorein** [rtfd/readthedocs.org#1498] opened 2015-07-30 04:24 UTC
I'd like to include iPython notebooks in my sphinx documentation. To do that, I can locally just run `ipython nbconvert -to rst` to [produce](http://ipython.org/ipython-doc/1/interactive/nbconvert.html) nicely formatted rst files. 

Unfortunately, readthedocs does currently not have the required packages installed (such as pygments) to do the conversion. Is there any chance `ipython nbconvert` can be supported on the build servers?

**Comment by gregmuellegger** [comment] 2015-07-31 09:53
You can require `ipython[notebook]>=3.0.0` in your project's requirements.txt file. However we currently have a issue that this won't work if your project uses the system site packages as well ... follow #1511 for this.

**Comment by gregmuellegger** [comment] 2015-07-31 09:55
I'm closing this as I think it's either resolved by the comment above (when you don't use the system site packages) or is a duplicate of #1489 when you are using the system site packages :)

Feel free to comment in one of the other issues, or here if you think it's still a separate issue.

**Closed by gregmuellegger** 2015-07-31 09:55 UTC
