### ISSUE TITLE
Cannot connect GitHub account

### ISSUE THREAD

**Issue by chetbox** [rtfd/readthedocs.org#2078] opened 2016-03-18 14:20 UTC
## Details

I just signed up for an account then clicked "Import Project" and then "Connect to GitHub". I was prompted to authorise my GitHub account, which I did, and then I'm redirected to `https://readthedocs.org/accounts/social/signup/`and no longer signed in.

![screen shot 2016-03-18 at 14 17 23](https://cloud.githubusercontent.com/assets/292958/13880485/5e014ffe-ed14-11e5-850d-d42a90847e0b.png)

If I click "Sign up" I get an error:

```
This username is already taken. Please choose another.
```

**Comment by agjohnson** [comment] 2016-03-18 17:31
Sounds like a duplicate of #1875, will reopen there.

**Closed by agjohnson** 2016-03-18 17:31 UTC
