### ISSUE TITLE
"View" or "Edit on GitHub" link doesn't take to the correct repo on Github

### ISSUE THREAD

**Issue by cirospat** [rtfd/readthedocs.org#4708] opened 2018-10-02 21:23 UTC
![image](https://user-images.githubusercontent.com/3757525/46377664-7e88f180-c699-11e8-9ef4-5ac0e864abd7.png)

## "View" or "Edit on GitHub" link doesn't take to the correct repo on Github

* Read the Docs project URL:  [https://cirospat.readthedocs.io](https://cirospat.readthedocs.io)
* Build URL (if applicable): 
* Read the Docs username (if applicable): cirospat

## Expected Result

*A description of what you wanted to happen* = solve the problem giving a correct link on Github repo

## Actual Result

*A description of what actually happened* = "View" or "Edit on GitHub" link doesn't take to the correct repo on Github

I noticed this happens also to [https://docs.readthedocs.io](https://docs.readthedocs.io) and othe project on Read the Docs. Have a try clicking on "edit on GitHub" link (right side up on the page).
![image](https://user-images.githubusercontent.com/3757525/46377822-11c22700-c69a-11e8-861c-c8df5ccdad6d.png).

The link takes to this URL:
https://github.com/rtfd/readthedocs.org/blob/master/home/docs/checkouts/readthedocs.org/user_builds/docs/checkouts/latest/docs/conf.py/index.rst that is a 404 error

**Comment by stsewd** [comment] 2018-10-02 21:36
Thanks for reporting, this is a duplicate of https://github.com/rtfd/readthedocs.org/issues/4671, it's already fixed, but we only need to wait for a deploy

**Closed by stsewd** 2018-10-02 21:36 UTC
