### ISSUE TITLE
Bump Sphinx from 1.3.5 to 1.4.6

### ISSUE THREAD

**Issue by ajdavis** [rtfd/readthedocs.org#2377] opened 2016-08-22 16:00 UTC
The listed Sphinx requirement is outdated.

Pull request: https://github.com/rtfd/readthedocs.org/pull/2378

**Comment by agjohnson** [comment] 2016-08-22 20:06
Closing as duplicate of #1853

**Closed by agjohnson** 2016-08-22 20:06 UTC
