### ISSUE TITLE
Mocking not working for private requirements.

### ISSUE THREAD

**Issue by feluxe** [rtfd/readthedocs.org#2586] opened 2017-01-12 04:39 UTC
## Details

* Project URL: http://omplate.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/omplate/builds/4888126/
* Read the Docs username (if applicable): feluxe

*A description of what actually happened*

The build fails because it tries to install private requirements which are hosted on a registry other than pypi.
I tried to mock the requirements out, with the following snippet in `conf.py`:

	import sys
	from unittest.mock import MagicMock

	class Mock(MagicMock):
	    @classmethod
	    def __getattr__(cls, name):
	        return MagicMock()

	MOCK_MODULES = ['mypackage']
	sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)

I got this from the [FAQ](http://read-the-docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules), but unfortunately it doen't seem to work.

**Comment by humitos** [comment] 2017-02-23 00:35
@feluxe not sure but I think you have to remove the `ompy` from the `requirements.txt` file you are declaring to RTD. Maybe you can have a `rtd_requirements.txt` without this module for RTD plus using the snippet you have mentioned.

Besides, just in case, the `MOCK_MODULES` should be like `['ompy']` in your example.

**Comment by feluxe** [comment] 2017-02-23 12:41
@humitos thanks for your reply!

> not sure but I think you have to remove the ompy from the requirements.txt file you are declaring to RTD. Maybe you can have a rtd_requirements.txt without this module for RTD plus using the snippet you have mentioned.

I guess this would work, but on the same hand maintaining two different versions of `requirements.txt` seems quite cumbersome/hacky IMO. Shouldn't `Mock` be able to mock the dependency out? I'm mean that's what it's for, right?

> Besides, just in case, the MOCK_MODULES should be like ['ompy'] in your example.

Thas's what I currently have:

	class Mock(MagicMock):
	    @classmethod
	    def __getattr__(cls, name):
	        return MagicMock()

	MOCK_MODULES = ['ompy']
	sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)

**Comment by humitos** [comment] 2017-02-23 13:18
> I guess this would work, but on the same hand maintaining two different versions of requirements.txt seems quite cumbersome/hacky (IMHO). 

No, it's not hacky it's a very common practice.

> Shouldn't Mock be able to mock the dependency out? I'm mean that's what it's for, right?

Yes and No. The mock conf is to "mock the python code" but now the requirements. The mock code is executed after all the requirements are installed, if RTD can't install the requirements there is nothing to mock :)

**Comment by feluxe** [comment] 2017-02-23 13:53
You are right it's not hacky. Just found the section in the *Admin* area and added a `rtd_requirements.txt` to the project. :)

But still it adds additional complexity and redundancy to the project, since I have to maintain two (almost) identical files and make sure they stay synced. ;)

**Comment by humitos** [comment] 2017-02-23 14:05
You need this https://pip.pypa.io/en/latest/reference/pip_install/#requirements-file-format

I'm closing this issue since it's not a bug/enhancement in RTD. Feel free to re-open or create a new one if you find something else. Thanks!

**Closed by humitos** 2017-02-23 14:05 UTC
Labels: Support
