### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'traverse'

### ISSUE THREAD

**Issue by SylvainCorlay** [rtfd/readthedocs.org#2458] opened 2016-10-13 20:44 UTC
I have observed the same issue with a bunch of repos in the past 3h.
## Details
- Project URL: ipywidgets
- Build URL (if applicable): https://github.com/ipython/ipywidgets
- Read the Docs username (if applicable): SylvainCorlay
## Expected Result

The doc builds
## Actual Result

_A description of what actually happened_

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/builders/html.py", line 1023, in write
    self.write_doc(self.config.master_doc, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/builders/html.py", line 452, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/builders/html.py", line 803, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/readthedocs_ext/readthedocs.py", line 101, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/sphinx_rtd_theme/layout.html", line 96, in top-level template code
    {% block menu %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/sphinx_rtd_theme/layout.html", line 97, in block "menu"
    {% set toctree = toctree(maxdepth=2, collapse=False, includehidden=True) %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/jinja2/sandbox.py", line 355, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/builders/html.py", line 793, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/builders/html.py", line 955, in _get_local_toctree
    self.fix_refuris(toctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/test-environment/conda/latest/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/builders/html.py", line 940, in fix_refuris
    for refnode in tree.traverse(nodes.reference):
AttributeError: 'NoneType' object has no attribute 'traverse'
```

**Comment by toolness** [comment] 2017-01-30 16:17
This seems to be a duplicate of #2398, where there is more discussion happening, at least.

**Comment by humitos** [comment] 2017-02-23 18:15
Closing because of duplicated of #2398

**Closed by humitos** 2017-02-23 18:15 UTC
Labels: Status: duplicate
