### ISSUE TITLE
stable not picking up latest release

### ISSUE THREAD

**Issue by frontendphil** [rtfd/readthedocs.org#1284] opened 2015-05-21 16:14 UTC
I added a new tag to our repo which is being built by RTD. Now we link to /stable for the current documentation and keep the tags aligned with our product releases. However the latest push didn't update the stable pointer. 

Now, I would push another tag but then I couldn't link to the docs anymore. For on-premise use cases we simply use the product version to link to the correct version of the docs. 

Affected projects: effektif and effektif-de

**Comment by posita** [comment] 2015-05-22 04:56
Similar issue to #1278?

**Comment by frontendphil** [comment] 2015-05-22 09:19
Maybe.. The thing is, that RTD did pick up _all_ tags but the stable pointer did not change.

**Comment by jab** [comment] 2015-05-26 16:34
I've been hitting this too.

**Comment by jab** [comment] 2015-05-26 16:40
(In case it's helpful, my project is https://bidict.readthedocs.org.)

Have you considered adding a "sync" button so maintainers can manually force a re-sync of all branches/tags?

**Comment by jab** [comment] 2015-06-06 21:40
FWIW @GrahamDumpleton posted a workaround [on twitter](https://twitter.com/GrahamDumpleton/status/605271367366397952), but it didn't help in my case. After many permutations of building, cleaning, wiping, and toggling public/private, my "stable" build still refers to an ancient version of my project.

@onewheelskyward Would you be willing to have a look at what's going on here with my project when you get a chance? Thanks in advance for any help.

**Comment by gregmuellegger** [comment] 2015-07-09 11:07
@frontendphil @jab we changed the version parsing to be compliant with PEP 440 so that the version ordering etc gets a lot more reliable. Can you test if this fixes the issue for you when you push a new version?

**Comment by gregmuellegger** [comment] 2015-07-27 07:39
Closing this as I assume that it's fixed. Feel free to open a new ticket if this is still an issue for you.

**Closed by gregmuellegger** 2015-07-27 07:39 UTC
Labels: Bug, Needed: more information

**Comment by fsouza** [comment] 2015-11-03 18:01
I'm facing this issue again :-(

I've just release tsurud 0.12.4: https://github.com/tsuru/tsuru/releases/tag/0.12.4

But stable still points to 0.12.3: http://docs.tsuru.io/en/stable/

Any recommendation on how to proceed?

**Comment by agjohnson** [comment] 2015-11-03 22:37
@fsouza this ticket is closed, you should open a new ticket to track your issue

**Comment by fsouza** [comment] 2015-11-04 01:39
@agjohnson you have a regression and should reopen the issue, because it's clearly not fixed. But ok, your project, your process. The new issue is #1806.
