### ISSUE TITLE
Intermittent "Sorry page does not exist yet" errors

### ISSUE THREAD

**Issue by mrocklin** [rtfd/readthedocs.org#2943] opened 2017-06-10 13:13 UTC
## Details

* Project URL: https://dask.readthedocs.io/en/latest/ and https://distributed.readthedocs.org/en/latest
* Build URL (if applicable): https://readthedocs.org/projects/dask/builds/5536038/ 
* Read the Docs username (if applicable): mine is mrocklin, though I'm not sure if this is relevant in this case

## Actual Result

About half of the time that I visited the page I got a Maze page with a "Sorry the page does not exist yet" error message.  Refreshing would sometimes provide the actual content. Here is a gif provided by one of our users:

![](https://user-images.githubusercontent.com/6053396/26993403-bccb7a78-4d17-11e7-854f-dd4f8e62a1ae.gif)

The problem seems to have gone away on its own.  I did trigger a rebuild.  I don't have strong evidence that this resolved the problem though.  I thought I'd report the experience regardless.

**Comment by mrocklin** [comment] 2017-06-10 13:14
Feel free to close

**Comment by abyrd** [comment] 2017-06-12 07:05
The documentation for OpenTripPlanner is also leading to the "This page does not exist yet" page. The problem has existed each time I check the documentation since 9 June. This can be seen when following the link for the latest version of the documentation at https://readthedocs.org/projects/opentripplanner/versions/

**Comment by abyrd** [comment] 2017-06-12 07:23
I manually re-triggered the documentation build and they are again visible.

**Comment by robertknight** [comment] 2017-06-13 13:25
We (Hypothesis) have been experiencing a similar issue today. I am able to reproduce with curl: https://gist.github.com/robertknight/854a07bff300214a75fd49144ede7501

**Comment by humitos** [comment] 2017-12-27 00:07
Hi! This was probably a temporary error with syncing of the files and should be working properly now. I'm closing it. Please, feel free to reopen if you consider.

**Closed by humitos** 2017-12-27 00:07 UTC

**Comment by dognie** [comment] 2018-07-25 10:11
@humitos I met the same problem "Sorry the page does not exist yet"
Even if I delete the project and rebuild it, it will still be reproduced.
I also have the same problem with the re registration of my account.

**Comment by humitos** [comment] 2018-07-25 14:52
@dognie what's your project URL under Read the Docs?
