### ISSUE TITLE
Search option is case sensitive(?)

### ISSUE THREAD

**Issue by pieterlukasse** [rtfd/readthedocs.org#2328] opened 2016-07-21 07:19 UTC
## Details
- Project URL: http://cbioportal-inodb.readthedocs.io/en/latest/
## Expected Result

I would like the search to be case insensitive. 
## Actual Result

When using the search option, I noticed that it only finds results when the case is matching. This should _not_ be the case. Example: searching for `cbioportalImporter.py` or `cbioportalimporter.py` in the documentation URL above gives different results (in this case only the first one results in matches).

**Comment by smrgit** [comment] 2016-09-01 18:12
I have also experienced this -- is there a way to make searches case-insensitive?  or are there any options for how the search is performed?

**Comment by pieterlukasse** [comment] 2016-09-02 06:28
I have not found one. I hope the developers here can give this some priority...

**Comment by smrgit** [comment] 2016-09-06 17:23
@pieterlukasse within the past couple of days things seem to have changed -- can you confirm that the search now seems to be case-insensitive?  (or could it be a browser issue in some strange way?) another thing I'm noticing it is that partial-word searching doesn't work which was my attempted-work-around to avoid having to choose whether the first letter was upper- or lower-case ...

**Comment by pieterlukasse** [comment] 2016-10-25 09:19
@smrgit no, searching for `cbioportalimporter.py` in referred  documentation still gives no results. When I use only `cbioportalimporter`, then I get some results (also in different case). So maybe it is improved a bit...but not quite there yet.

**Comment by safwanrahman** [comment] 2018-06-15 11:00
@ericholscher If anyone wants to have a case sensitive search, what they will need to do then?

**Comment by ericholscher** [comment] 2018-06-15 12:21
I don't know if we need to support case sensitive, but perhaps we could support it with quotes. ""importedFile" for example.

**Comment by ericholscher** [comment] 2018-06-19 10:06
@safwanrahman would be good to add some tests to confirm this, and then we can call it done, and will catch any regressions if they happen.

**Comment by ericholscher** [comment] 2018-06-19 10:31
So:

* The default search should always return things in any case (case insensitive)

We need to decide if we want to support the ability to search case sensitive, and how it would work. One idea would be to quote things "ImportedFile" -- but I worry, as it would also make "run the tests" not return results for `Run the tests`. So we should think more about how to implement case sensitivity, and perhaps choose not to implement it at all.

**Comment by ericholscher** [comment] 2018-06-21 10:20
This has been fixed in our new search code. It will be deployed in the next month or so, so closing this issue as it's been addressed.

**Closed** 2018-09-28 13:43 UTC
Labels: Improvement, Needed: design decision
