### ISSUE TITLE
restrict stable version to tags

### ISSUE THREAD

**Issue by dschult** [rtfd/readthedocs.org#1881] opened 2015-12-28 01:17 UTC
We create a tagged version of our github repo for each release. But we also have branches and sometimes the branch name parses to a version more recent than our stable tag. So the branch becomes the "stable" release on readthedocs. It'd be nice to restrict the choice of the "stable" release to only be from the github tags instead of including both tags and branches.

We can of course be very careful how we name our branches. But that choice is rarely done with readthedocs in mind and its a surprise when the stable docs suddenly change because we created a branch in the repository.

Perhaps this is just a github issue, but I suspect it has wider impact too. 

[workarounds and other options would be appreciated too]

**Comment by kmike** [comment] 2016-04-28 19:08
This issue affects Scrapy: version names in Scrapy docs don't make any sense now. "Latest" points to 1.0, "stable" points to upcoming 1.1 and "master" points to master (upcoming 1.2). So latest is the oldest, and stable is not released yet. 

I'm not sure how we get there :) It might be an error on our side, but it is not clear how to fix it.

**Comment by humitos** [comment] 2017-12-29 00:24
This logic was implemented at https://github.com/rtfd/readthedocs.org/pull/3331

Please, would you mind confirming if you still have this issue? I think it should have solved now. If the problem is gone, please close the issue :)

**Closed** 2018-01-01 12:55 UTC
Labels: Enhancement, Needed: more information
