### ISSUE TITLE
Bad search results on "latest", working on branch latest points to

### ISSUE THREAD

**Issue by cathalmccabe** [rtfd/readthedocs.org#3257] opened 2017-11-14 11:54 UTC
## Details
Three version of docs are currently being built based on tags v1.3, v1.4, v2.0 (most recent version). 
Latest points to v2.0, so there are 4 links on readthedocs.  

Searching on "latest" version of docs generates links to pages in older branches/versions of docs, but with "latest" in the URL instead of the correct branch name. 
i.e. http://pynq.readthedocs.io/en/<branch name>/*
This generates a bad url. 

Searching on v2.0, works correctly, it does not link to old pages. 

It can be seen that both latest and v2.0 are build from the same commit: c971535a

It seems like "latest" is using the wrong (an old) searchindex.js, but when comparing v2.0 with latest, they are almost identical. 
http://pynq.readthedocs.io/en/v2.0/searchindex.js
http://pynq.readthedocs.io/en/latest/searchindex.js
latest has extra reference in "latest" entry:
latest: [1, 14, 34, 38, 40, 41, 49],
v2.0 has this:
latest: [1, 14, 34, 40, 41],

Wiping and rebuilding latest does not fix this. 

* Project URL: 
github.com/xilinx/pynq

* Build URL (if applicable):
Build for latest:
https://readthedocs.org/projects/pynq/builds/6266967/
Build for v2.0
https://readthedocs.org/projects/pynq/builds/6266968/

* Read the Docs username (if applicable): 
cathalmccabe

## Expected Result
Identical search results when searching from "latest" and "v2.0" where latest points to v2.0 branch, and no bad URLs in "latest" search. 

*A description of what you wanted to happen*
As above.

## Actual Result

Bad search URLs are generated.
*A description of what actually happened*

E.g.
Searching for "pmod_io" gives different results from "v2.0" and "latest"
http://pynq.readthedocs.io/en/v2.0/search.html?q=pmod_io&check_keywords=yes&area=default#
http://pynq.readthedocs.io/en/latest/search.html?q=pmod_io&check_keywords=yes&area=default#

The first result from "latest" is to this link which does not exist
http://pynq.readthedocs.io/en/latest/_modules/pynq/iop/pmod_io.html?highlight=pmod_io

This page does exist in an older version ("v1.4) of the docs
http://pynq.readthedocs.io/en/v1.4/_modules/pynq/iop/pmod_io.html?highlight=pmod_io

**Comment by stsewd** [comment] 2017-12-26 21:19
Thanks for reporting, this is a duplicate of #3108.

**Comment by stsewd** [comment] 2018-05-10 08:42
Closing this in favor of #3108

**Closed by stsewd** 2018-05-10 08:42 UTC
