### ISSUE TITLE
Jquery needs to be included by the theme so the floating footer works

### ISSUE THREAD

**Issue by choldgraf** [rtfd/readthedocs.org#4739] opened 2018-10-08 19:24 UTC
## Details

* Read the Docs project URL: https://bids-specificaion.readthedocs.io/en/latest/
* Read the Docs username (if applicable): choldgraf

## Expected Result

The documentation is built as PDF/EPUB (since those boxes are checked on my advanced settings menu). Also, I expect to see the little floating window in the bottom-right since I'm hosting on readthedocs.

## Actual Result

There is no built file in `/downloads`, nor in the `downloads` tab on the RTD config page. There is also no floating box.

**Comment by stsewd** [comment] 2018-10-08 19:35
PDF and epub formats aren't supported by MkDocs. The floating box is an issue, though.

**Comment by stsewd** [comment] 2018-10-08 19:39
Looks like jquery is missing when injecting the rtd's version selector (floating box)

**Comment by choldgraf** [comment] 2018-10-08 19:42
ahh - it'd be helpful if it were made clear that PDF generation only works for Sphinx builds and not mkdocs...perhaps [here](https://docs.readthedocs.io/en/latest/features.html?highlight=pdf#pdf-generation) :-)

re: the floating box, do we need to specify jquery as a dependency somehow?

**Comment by stsewd** [comment] 2018-10-08 19:49
We mention that here https://docs.readthedocs.io/en/latest/builds.html#mkdocs, I'm not sure if we need to mention that on the features pages, as it's a MkDocs limitation, not rtd.

> re: the floating box, do we need to specify jquery as a dependency somehow?

I think we inject those dependencies somewhere (or maybe we assume that everyone is using jquery?) I need to check the code.

**Comment by choldgraf** [comment] 2018-10-08 19:52
Sure - I'm just giving you some data from my personal path through that documentation...I didn't notice that statement about PDF on that page

**Comment by stsewd** [comment] 2018-10-22 18:48
So, I looked into the code, we inject the code for the floating footer https://github.com/rtfd/readthedocs.org/blob/a4291d17728b8df6b7a9ce57537c5d620416e485/readthedocs/doc_builder/backends/mkdocs.py#L106-L106, but we don't have jquery as an explicit dependency https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/static-src/core/js/readthedocs-doc-embed.js

Not sure if we should add jquery or rely on themes to added it. Going to mark this as a design decision.

**Comment by humitos** [comment] 2019-01-07 17:50
The original project with the issue is no longer public. Also, the floating menu is working for an MkDocs project (https://mkdocs.readthedocs.io/en/stable/) without problem.

I'm closing the issue here. Feel free to reopen if you consider.

**Closed** 2019-01-07 17:50 UTC
Labels: Needed: design decision

**Comment by choldgraf** [comment] 2019-01-07 21:15
That's fine, though just a quick note that the project is still public, we just corrected a typo in the url 

https://bids-specification.readthedocs.io/en/latest/

**Comment by stsewd** [comment] 2019-01-08 00:47
@humitos I was thinking that we could bundle the footer with all the requirements (only jquery here I think), so it works in every theme.
