### ISSUE TITLE
HTTPS with rtfd.org

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [rtfd/readthedocs.org#3059] opened 2017-08-20 20:35 UTC
e.g.
This work
http://backintime.rtfd.org/
but it's HTTPS version doesn't work because of in invalid certificate
https://backintime.rtfd.org/

And IMO http://backintime.rtfd.org/ should not be redirected to http://backintime.readthedocs.io/en/latest/ but to https://backintime.readthedocs.io/en/latest/

**Comment by davidfischer** [comment] 2017-09-04 18:33
The main chunk of this looks like a dupe of #328.

The second half of this seems legitimate.

**Comment by jab** [comment] 2018-03-29 07:36
You could fix this issue right now by making http://foo.readthedocs.io redirect to https://foo.readthedocs.io. Isn't it worth doing that anyway?

It would mean an extra redirect in the foo.rtfd.org case, but the end result would be the same, and you could tackle the 1-step redirect from rtfd.org independently. This would be strictly better than the current behavior, isn't blocked by #328, and seems like a ~1-line change, no?

**Comment by jab** [comment] 2018-03-29 07:38
Just opened #3874 to track this independently.

**Comment by jab** [comment] 2018-08-15 16:35
Looks like https://foo.rtfd.io is working now! 🎉
Close?

**Comment by davidfischer** [comment] 2018-08-15 16:43
> You could fix this issue right now by making http://foo.readthedocs.io redirect to https://foo.readthedocs.io. Isn't it worth doing that anyway?

Yes. We deployed that today.

> Close?

We can close it. I'm working on getting a wildcard cert for `*.rtfd.org` as well although I think fewer people are using that.

**Closed by davidfischer** 2018-08-15 16:43 UTC
Labels: Improvement, Operations

**Comment by davidfischer** [comment] 2018-08-16 19:00
There is now a cert for `*.rtfd.org` as well.
