### ISSUE TITLE
Do not show disable adblocker messages to paying customers

### ISSUE THREAD

**Issue by densh** [rtfd/readthedocs.org#4253] opened 2018-06-16 18:04 UTC
## Details

* Read the Docs project URL: https://scala-native.readthedocs.io/en/latest/
* Read the Docs username (if applicable): densh

## Problem

Our project supports read the docs with 5/mo payments, but it looks like read the docs still shows this to our users:

    Support Read the Docs!

    Please help keep us sustainable by allowing our Ethical Ads in your ad blocker or go ad-free by subscribing.

    Thank you! ❤️

Is there any way to remove this message permanently? The project is in my list of projects under the gold page.

**Comment by stsewd** [comment] 2018-06-16 20:00
Thanks for support rtd, I think this is a duplicate of #4218

**Closed** 2018-06-18 16:33 UTC
