### ISSUE TITLE
Generated links missing trailing slash

### ISSUE THREAD

**Issue by orlade** [rtfd/readthedocs.org#1101] opened 2014-12-17 01:59 UTC
Links generated within the body and the left menu sidebar do not have forward slashes appended to the URL, and URLs without trailing slashes fail.

For example, http://docs.atlas.urbanetic.net/en/latest/features/ works but http://docs.atlas.urbanetic.net/en/latest/features does not. Within that page, the first link points to http://docs.atlas.urbanetic.net/en/latest/design which is broken, but http://docs.atlas.urbanetic.net/en/latest/design/ works.

Docs were generated using MkDocs, and the [Markdown source for the features page is here](https://github.com/urbanetic/atlas/blob/develop/docs/features.md).

**Comment by rkday** [comment] 2015-02-01 11:17
I'm hitting this as well. It looks like part of the problem is https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/views.py#L444, which just appends "index.html" to the URL (which results in a path like `http://docs.atlas.urbanetic.net/en/latest/designindex.html`), but even after fixing that up, it doesn't quite work (relative directory links break, because "." and ".." for `http://docs.atlas.urbanetic.net/en/latest/design` are different than for `http://docs.atlas.urbanetic.net/en/latest/design/`.

Setting `'use_directory_urls': false` in mkdocs.yaml works around this.

@tomchristie, @d0ugal - as the mkdocs maintainers, would you accept a patch to generate all links in the form `section/page/` rather than `section/page`? That feels like the cleanest solution, and then you don't rely on the server treating the two identically.

**Comment by d0ugal** [comment] 2015-02-02 09:01
@rkday I think I'm okay with that, I can't think of any potential issues.

**Comment by d0ugal** [comment] 2015-05-27 07:55
This has been fixed downstream. We just need to update MkDocs in ReadTheDocs - I am tracking my work on that here: https://github.com/mkdocs/mkdocs/issues/554

**Comment by ericholscher** [comment] 2015-05-27 20:45
Closing this in deference to the mkdocs issue. Should be fixed soon.

**Closed by ericholscher** 2015-05-27 20:45 UTC
