### ISSUE TITLE
Documentation URLs without trailing slash redirect from https to http

### ISSUE THREAD

**Issue by toffer** [rtfd/readthedocs.org#714] opened 2014-03-01 05:41 UTC
The redirect should work by just adding a slash:

https://pip.readthedocs.org/en/latest ->  https://pip.readthedocs.org/en/latest/

But, they currently work by adding slash and also redirecting from https to http URL:

https://pip.readthedocs.org/en/latest -> http://pip.readthedocs.org/en/latest/

**Comment by destroyerofbuilds** [comment] 2015-07-20 22:01
@toffer can you please retest. This no longer seems to be the case.

**Comment by ericholscher** [comment] 2015-08-20 16:52
-> curl -sI https://pip.readthedocs.org/en/latest  |grep Location
Location: http://pip.readthedocs.org/en/latest/

**Comment by travcunn** [comment] 2016-10-25 17:37
I believe this can be closed:

``` sh
> curl -sI https://pip.readthedocs.org/en/latest | grep Location
Location: https://pip.readthedocs.io/en/latest
```

**Comment by mgedmin** [comment] 2017-01-20 15:34
@travcunn look closer, your 2nd command shows a redirect from https to http.

**Comment by travcunn** [comment] 2017-01-20 15:47
Whoops!

Could we put the Nginx config files in this repo?

**Comment by humitos** [comment] 2018-02-03 16:27
The nginx config files to handle this lives in a private repository, so I can't share those config files with you. I'm sorry about that.

Answering a comment from #3575 to @ewangi:

I self assigned it to me to take a look when I have some time because I consider this important and I thought it shouldn't be so difficult. Although, I'm new in the operations repository and I'm trying to learn/understand how everything is connected. On the other hand, I know that Eric and Anthony took a look at this a couple of times and this is not solved yet but maybe "new eyes" can make a difference :P (although, with less knowledge, hehe)

**Comment by ewangi** [comment] 2018-02-03 20:37
Can I back up @travcunn 's request that the relevant files are placed in a public repo. I'm very new to this, but I can't understand why an open source project on here should have some files that are hidden from view - it allows less opportunity for bugs to be resolved. This isn't a criticism, it is a request that someone might explain to me why that is the case.

@humitos - I remain at your disposal to help get this bug solved.

**Comment by humitos** [comment] 2018-02-03 21:08
@ewangi I don't have the proper answer, I'm also new here. I'd say that _time_ has been one of the reasons at least. Open source some code it's not trivial: you have to remove all the secrets from the repository and maintain the automated flow working properly.

> Probably contains secrets.

It's what the private repository says in the description :)

Anyway, I think it would be awesome to follow that path.

**Comment by agjohnson** [comment] 2018-04-12 00:16
While Read the Docs itself is open source, we have a number of closed source code/provisioning/etc  that will remain private. We don't benefit from liberally sharing this sort of work. This is not from nginx in fact, it's from another private project that we maintain. Closing here as the issue is duplicated there already.

**Closed by agjohnson** 2018-04-12 00:16 UTC
Labels: Bug, Operations
