### ISSUE TITLE
Links in the RTD footer (fly-out menu) totally borked

### ISSUE THREAD

**Issue by marcelstoer** [rtfd/readthedocs.org#1884] opened 2015-12-28 23:41 UTC
http://nodemcu.rtfd.org/ is a MkDocs/GitHub based RTD project. I noticed recently that the links in the RTD footer (fly-out menu) are totally borked, all 404 there.

I maintain localized `.md` files in the same `docs` directory but I don't know if that's got anything to do with it. GitHub: https://github.com/marcelstoer/nodemcu-firmware/tree/dev-rtd/docs

- on the default page at http://nodemcu.readthedocs.org/en/dev-rtd/ (`docs/index.md`)
 - "Versions dev-rtd" points to http://nodemcu.readthedocs.org/en/dev-rtd/None/, where does "None" come from?
 - "On GitHub View" points to https://github.com/marcelstoer/nodemcu-firmware/blob/dev-rtd/home/docs/checkouts/readthedocs.org/user_builds/nodemcu/checkouts/dev-rtd/docs/None.md
- on http://nodemcu.readthedocs.org/en/dev-rtd/en/ (`docs/en/index.md`)
 - "Versions dev-rtd" points to http://nodemcu.readthedocs.org/en/dev-rtd/Home/, where does "Home" come from
 - "On GitHub View" points to https://github.com/marcelstoer/nodemcu-firmware/blob/dev-rtd/home/docs/checkouts/readthedocs.org/user_builds/nodemcu/checkouts/dev-rtd/docs/Home.md
- on http://nodemcu.readthedocs.org/en/dev-rtd/en/build/ (`docs/en/build.md`)
 - "Versions dev-rtd" points to http://nodemcu.readthedocs.org/en/dev-rtd/Building%20the%20firmware/ which is doubly wrong
 - "On GitHub View" points to https://github.com/marcelstoer/nodemcu-firmware/blob/dev-rtd/home/docs/checkouts/readthedocs.org/user_builds/nodemcu/checkouts/dev-rtd/docs/Building%20the%20firmware.md

I report it here (rather than e.g. with the RTD theme for MkDocs) because the content for that fly-out menu is provided by an RTD AJAX call to https://readthedocs.org//api/v2/footer_html/.

**Comment by agjohnson** [comment] 2015-12-29 05:09
This sounds like a duplicate of #1480, which would be fixed with #1634, though we require a mkdocs release. Feel free to reopen if that does resolve these issues.

**Closed by agjohnson** 2015-12-29 05:09 UTC

**Comment by marcelstoer** [comment] 2015-12-29 13:49
> This sounds like a duplicate of #1480 

Indeed, thanks a lot. Surprizes me that my earlier GitHub issues search didn't find the dup.

**Comment by agjohnson** [comment] 2015-12-29 19:19
Great. To be fair, the title of the original issue didn't describe the issue best -- I've updated it for future reference :)

**Comment by dnrce** [comment] 2016-01-12 04:15
AFAICT #1480 only covers half of this. I reported #1917 regarding the GitHub URLs.

**Comment by marcelstoer** [comment] 2016-01-12 06:08
True, thanks for reporting. That faulty GitHub link is even in the description of this issue :frowning:.

**Comment by agjohnson** [comment] 2016-01-12 18:03
Indeed, I missed this scanning too quickly. Someone can address this issue at #1917
