### ISSUE TITLE
Sphinx error: master file [..]/checkouts/latest/contents.rst not found

### ISSUE THREAD

**Issue by gr2m** [rtfd/readthedocs.org#2569] opened 2016-12-31 17:52 UTC
I’m still new to readthedocs.org and have no experience with either Python nor Sphinx, please excuse me if I’m doing something obviously wrong. I googled the error and have found other builds failing with the same error, but when I looked at their commits that lead to a successful build, the changes didn’t make sense to me.

## Details

* Project URL: https://readthedocs.org/projects/hoodie-test
* Build URL (if applicable): https://readthedocs.org/projects/hoodie-test/builds/4846469
* Read the Docs username (if applicable): gr2m

## Expected Result

I expected a new version of docs to be built at http://hoodie-test.readthedocs.io/en/latest/

## Actual Result

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hoodie-test/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hoodie-test/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/hoodie-test/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/hoodie-test/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/docs/checkouts/readthedocs.org/user_builds/hoodie-test/envs/latest/local/lib/python2.7/site-packages/sphinx/environment.py", line 622, in update
    self.doc2path(config.master_doc))
SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/hoodie-test/checkouts/latest/contents.rst not found

Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/hoodie-test/checkouts/latest/contents.rst not found
```

**Comment by agjohnson** [comment] 2017-01-05 06:59
This doesn't look to be a problem with RTD, so I'm going to close it. The error message states it is looking for a `contents.rst`, which doesn't exist. If you don't specify otherwise, Sphinx's default `master_doc` setting is `contents`. If you'd like to use `index` instead, you'll need to create a configuration file. I suggest you first explore http://www.sphinx-doc.org/en/1.5.1/tutorial.html as you should be getting the same errors locally, it might be easier to learn Sphinx this way.

**Closed by agjohnson** 2017-01-05 06:59 UTC

**Comment by XinArkh** [comment] 2019-04-20 13:16
Encountered the same problem here. 

I'm using sphinx 2.0.1. The generated structure by `sphinx-quickstart` command is built into html documentation successfully in my environment, while in `readthedocs.org` there occurs "contents.rst not found" error. 

I finally found it works by adding the following line in `conf.py` to explicitly assign [the master document](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=master_doc):

```python
master_doc = 'index'
```

I guess this issue is caused by the conflicts of the default sphinx version in readthedocs and the local environment.

I just record this solution here in case someone like me will be confused by this issue and have no idea about how to deal with it.

**Comment by stsewd** [comment] 2019-04-22 15:55
You can use a `requirements.txt` file to use the same version of sphinx you use locally https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by rahulgorai22** [comment] 2019-05-15 06:33
> Encountered the same problem here.
> 
> I'm using sphinx 2.0.1. The generated structure by `sphinx-quickstart` command is built into html documentation successfully in my environment, while in `readthedocs.org` there occurs "contents.rst not found" error.
> 
> I finally found it works by adding the following line in `conf.py` to explicitly assign [the master document](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=master_doc):
> 
> ```python
> master_doc = 'index'
> ```
> 
> I guess this issue is caused by the conflicts of the default sphinx version in readthedocs and the local environment.
> 
> I just record this solution here in case someone like me will be confused by this issue and have no idea about how to deal with it.

Worked for me !! Thanks

**Comment by edyasikpo** [comment] 2019-09-09 19:11
> ```python
> master_doc = 'index'
> ```

I have been struggling with this issue for hours. thank you for sharing the answer.

**Comment by adamj-codethink** [comment] 2020-06-25 20:37
I am also seeing this issue after follow the "getting started with sphinx" guide: https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html, it seems like a bug with these instructions?

**Comment by benjaoming** [comment] 2021-02-24 13:53
The confusion is well-stated by @adamj-codethink:

> I am also seeing this issue after follow the "getting started with sphinx" guide: https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html, it seems like a bug with these instructions?

The instructions are fine. The `sphinx-quickstart` for the latest versions 3.x of Sphinx will create a `conf.py` without any mentioning of `master_doc`, thus the default value `index` is used. It will work fine locally with Sphinx 3.x.

But [Read the Docs uses Sphinx 1.8.5](https://github.com/readthedocs/readthedocs.org/blob/master/requirements/pip.txt#L16) by default and since `master_doc` isn't specified, another default is used.

Having just onboarded a new user to Read the Docs, this problem came up again: Following standard documentation will land a broken Read the Docs project. Judging from the activity in this thread, it's a problem to many people. For instance the above comment:

> I have been struggling with this issue for hours. thank you for sharing the answer.

### Solutions?

User has to fix it: Either the user has to add `master_doc` in their configuration or configure the Read the Docs project to use a newer version of Sphinx. I don't think this is a good way forward for a documentation project :smile: 

Read the Docs fixing it: We can expect that people are now following guides with the latest version of Sphinx installed locally.

* New projects should be built with Sphinx 3.x as the default
* Read the Docs should force a default `master_doc="index"` if unset in the supplied `docs/conf.py`.

Any further thoughts on this?

**Comment by humitos** [comment] 2021-02-24 14:33
> Read the Docs fixing it: We can expect that people are now following guides with the latest version of Sphinx installed locally.
> 
>     * New projects should be built with Sphinx 3.x as the default

We are already onboard with this solution. @stsewd already created a PR with the new proposed policy for these external dependencies that Read the Docs relies on, and mentioned that RTD should always install the latest Sphinx version: https://github.com/readthedocs/readthedocs.org/pull/7859/files#diff-1d854732c488780cf89b325277dd80220a7e541647ccf1c18bdc372eb7b1a4d6R71

**Comment by stsewd** [comment] 2021-02-24 15:06
btw, we already install the latest sphinx version for new projects (created after Oct 20, 2020)

**Comment by benjaoming** [comment] 2021-02-28 13:46
It sounds great that the latest stable version of Sphinx will always be supported and is used for newer projects, that would fix this issue once and for all.

Can the Sphinx version pinned in `requirements/pip.txt` be clarified?

https://github.com/readthedocs/readthedocs.org/blob/29c23600d7ef2f2b63d90c900f0d13fff44eaec6/requirements/pip.txt#L13-L16

**Comment by stsewd** [comment] 2021-03-01 14:26
@benjaminp that dependency is for our intersphinx integration https://github.com/readthedocs/readthedocs.org/blob/29c23600d7ef2f2b63d90c900f0d13fff44eaec6/readthedocs/projects/tasks.py#L1365, those dependencies aren't used in the build process. We already fixed the issues with the theme, so we can update sphinx there.

**Comment by benjaoming** [comment] 2021-03-18 16:40
Thank you @stsewd - I understand now that this is controlled by the Feature flag `USE_SPHINX_LATEST` and that new projects need to have this Feature flag enabled. I see that this is the new default for readthedocs.org :+1: 

https://github.com/readthedocs/readthedocs.org/blob/3efaa7b946829898bf200ee2efaadac84bcdda9a/readthedocs/projects/models.py#L1591

I think self-hosted deployments have to define the feature flag default themselves in order to avoid this issue?

**Comment by stsewd** [comment] 2021-03-18 16:44
> I think self-hosted deployments have to define the feature flag default themselves in order to avoid this issue?

Yeah, that's correct. You can set the `default_true` and `future_default_true` atributes to `True` so it's aplied to all projects, old and future ones.
