### ISSUE TITLE
How to include outside header files in docs

### ISSUE THREAD

**Issue by lobachevzky** [rtfd/readthedocs.org#3324] opened 2017-11-27 14:29 UTC
## Details

* Project URL: https://readthedocs.org/projects/mujoco/
* Build URL (if applicable): https://readthedocs.org/projects/mujoco/builds/6318117/
* Read the Docs username (if applicable): ethanabrooks

## Expected Result

I want the build to succeed.

## Actual Result
```
build/mujoco/sim.c:569:21: fatal error: mjmodel.h: No such file or directory
compilation terminated.
```
This is because `mjmodel.h` comes from an outside directory. Referencing [this FAQ question](http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules), I included the following in my `conf.py`:

```
class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
            return MagicMock()

MOCK_MODULES = ['numpy', 'cython', 'mujoco', 'mjmodel']
sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)
```

But I still get the same error. Thank you for your help.

**Comment by stsewd** [comment] 2017-12-26 22:26
Hey, I just see your latest builds, and you only have a import error. Could you solve the other problem?

**Comment by stsewd** [comment] 2017-12-26 23:54
I just tested your docs on my local instance of rtd, looks like you have a package missing on your `docs/requirements.txt` file (`PyYAML==3.12`), also there is a problem catching an exception (IOError) on your `setup.py` file, and you shouldn't put an `input` function (rtd will kill the build for no responding). You can validate this checking for the `READTHEDOCS` environment variable (see http://docs.readthedocs.io/en/latest/faq.html#how-do-i-change-behavior-for-read-the-docs).

Anyway, I was able to build your docs with this:

- Add the missing package to the dependencies (probably this step isn't necessary).
- Uncomment this lines https://github.com/lobachevzky/mujoco/blob/master/docs/conf.py#L25-L31
- Uncheck the option `Install Project`.
- Change the python interpreter to 3.x

Here is the build https://readthedocs.org/projects/stsewd-mujoco/builds/6462237/
The docs http://stsewd-mujoco.readthedocs.io/en/latest/
My fork https://github.com/stsewd/mujoco/tree/rtd (`rtd` branch)

**Comment by lobachevzky** [comment] 2017-12-27 15:52
Thank you so much for your help with the project. So I implemented all four of your bullets and currently our my project looks essentially the same as your fork. Now I am getting the following mysterious error:

```
      File "/usr/lib/python3.5/signal.py", line 4, in <module>
        from enum import IntEnum as _IntEnum
    ImportError: cannot import name 'IntEnum'
```
Build: https://readthedocs.org/projects/mujoco/builds/6464422/

The error seems to be coming up before any code interacting with my project starts.

**Comment by stsewd** [comment] 2017-12-27 18:34
@lobachevzky I was able to build your docs (your current repo). Try reseting the environment https://readthedocs.org/wipe/mujoco/latest/

**Comment by lobachevzky** [comment] 2017-12-27 21:42
I reset the environment by clicking on that link and clicking 'Wipe Latest', but I still get the same error :/ Not sure what to do...

**Comment by stsewd** [comment] 2017-12-27 22:01
Don't worry, we will find a solution. I think the problem is the `enum` package, this isn't required to build the docs, on my fork I didn't have that https://github.com/stsewd/mujoco/blob/rtd/docs/requirements.txt.

**Comment by lobachevzky** [comment] 2017-12-27 22:21
That would make sense. Thanks for your help!

**Comment by humitos** [comment] 2017-12-28 02:27
Thank you people! I'm closing this one since you already found the solution.

**Closed by humitos** 2017-12-28 02:27 UTC
Labels: Support
