### ISSUE TITLE
Compilation failed but no failure indication is provided.

### ISSUE THREAD

**Issue by Paebbels** [rtfd/readthedocs.org#2629] opened 2017-02-03 14:10 UTC
## Details

* Project URL: http://poc-library.readthedocs.io/en/release/
* Build URL (if applicable): https://readthedocs.org/projects/poc-library/builds/4977100/
* Read the Docs username (if applicable): Paebbels

## Expected Result
A completed and error-free documentation generation :) -- just kidding.

I would expect an error message instead of good looking reports and a failed message with no failure indication, so I could investigate what's going on. Does our project exceed the compilation time?

## Actual Result
Build failed without any visible reason.

**Comment by skirpichev** [comment] 2017-02-07 17:50
Same here http://readthedocs.org/projects/diofant/builds/ in several recent builds.

**Comment by agjohnson** [comment] 2017-02-07 22:19
This is a duplicate of #2614. Closing here, feel free to follow up on the other ticket if you have anything that needs to be added.

**Closed by agjohnson** 2017-02-07 22:19 UTC
