### ISSUE TITLE
Searching shows raw data instead of inline text when using custom domain

### ISSUE THREAD

**Issue by barbara-sfx** [rtfd/readthedocs.org#2427] opened 2016-09-27 19:06 UTC
## Details
- Project URL: docs.signalfx.com
- Build URL (if applicable):
- Read the Docs username (if applicable): brsnyder
## Expected Result

Works at https://signalfx-product-docs.readthedocs-hosted.com/en/latest/search.html?q=time+range&check_keywords=yes&area=default

![image](https://cloud.githubusercontent.com/assets/17709550/18887686/ff03eb64-84a9-11e6-83fc-45c93e85ffb2.png)
## Actual Result

Doesn't work at http://docs.signalfx.com/en/latest/search.html?q=time+range&check_keywords=yes&area=default

![image](https://cloud.githubusercontent.com/assets/17709550/18887714/21b0d226-84aa-11e6-83bd-3cc96427c0e6.png)
## Notes

Sometimes shift-refresh fixes the problem, but today it isn't. Please fix this - our support people are encouraging users to go to the docs and this is just bad. 

Not to mention that the actual returned results are also better at the signalfx-product-docs.readthedocs-hosted.com site.

**Comment by AlmightyOatmeal** [comment] 2016-09-27 20:02
Here's a video of the weirdness in action before and after disabling caching and forced-reloads: [https://www.dropbox.com/s/cn23ed2k6uoujby/2016-09-27%20-%20Docs%20Issues.mp4?dl=0](https://www.dropbox.com/s/cn23ed2k6uoujby/2016-09-27%20-%20Docs%20Issues.mp4?dl=0)

**Comment by parsch** [comment] 2016-11-25 08:19
FYI: Had a similar problem, was able to resolve it, see https://github.com/rtfd/readthedocs.org/issues/839#issuecomment-262902446

**Comment by TimKam** [comment] 2016-12-23 14:41
For multi language documentation, I get a `No 'Access-Control-Allow-Origin' header is present` exception for all languages but the default language.

The search then falls back to the standard Sphinx search, which doesn't work properly in the latest Sphinx version RtD supports as of now.

**Comment by humitos** [comment] 2017-03-09 00:59
I wasn't able to reproduce the issue and it also seems to be a bug in Sphinx not in RTD. So, I'm closing this issue. Besides, it seems to be a duplicated of https://github.com/rtfd/readthedocs.org/issues/839#issuecomment-106102196

**Closed by humitos** 2017-03-09 00:59 UTC

**Comment by TimKam** [comment] 2017-03-09 07:17
@humitos The issue still occurs in multilingual documentation. For example: create an English project and reference a German project as its translation. The German search will return raw markup snippets of the *English* docs.
It's also not really a Sphinx issue, because RTD now implements its own custom search, see: http://docs.readthedocs.io/en/latest/features.html#search

**Comment by humitos** [comment] 2017-03-13 19:42
@TimKam can you provide an example of a project with this issue?
