### ISSUE TITLE
Make a nicer version page

### ISSUE THREAD

**Issue by mboersma** [rtfd/readthedocs.org#1001] opened 2014-10-28 17:11 UTC
We have many stale versions of our docs we want to purge. The instructions at https://docs.readthedocs.org/en/latest/builds.html#deleting-a-stale-or-broken-build-environment don't seem to work. For example, I visit http://readthedocs.org/wipe/deis/v0.9.0/ while logged in as the project owner, click the button, but the docs always remain at http://docs.deis.io/en/v0.9.0/. 

I have also marked the obsolete version not active and "private", but this does not seem to matter. We only want the last several versions of our docs to be available; the obsolete versions just confuse things.

**Comment by gregmuellegger** [comment] 2015-07-20 16:10
@ericholscher Has this feature already landed?

@wallrj we implemented PEP 440 support in #1384 that is already live. But I think we do not strip the post version numbers from the slug so far. The problem is that we would run into duplicated slugs then ... If you are still interested in the changes you describe then please open a separate ticket for it so that we can keep track.

**Comment by ericholscher** [comment] 2015-08-20 16:19
We have built a newer version page, closing this now.

**Closed by ericholscher** 2015-08-20 16:19 UTC
Labels: Enhancement
