### ISSUE TITLE
Builds appear to be stuck

### ISSUE THREAD

**Issue by frodsan** [rtfd/readthedocs.org#2255] opened 2016-06-04 13:47 UTC
## Details

* Project URL: https://readthedocs.org/projects/tynn/
* Build URL (if applicable): https://readthedocs.org/projects/tynn/builds/4069004/
* Read the Docs username (if applicable): frodsan

Builds from latest appear to be stuck.

Any idea how to fix/avoid this? Thanks in advance!

**Comment by tknuth** [comment] 2016-06-04 17:12
Mine seems to be stuck, too. The same applies for docs in the "recently updated" section. Is this a general problem?

**Comment by brianjking** [comment] 2016-06-04 18:09
Yeah, I'm also seeing this. Thanks for your help!

**Comment by advancedrei** [comment] 2016-06-05 01:28
I am also seeing the same issue. None of my builds have been compiling for the last 4 hours.

**Comment by cjw296** [comment] 2016-06-05 06:04
Same here at https://readthedocs.org/projects/xlrd/builds/:

<img width="875" alt="screen shot 2016-06-05 at 00 59 04" src="https://cloud.githubusercontent.com/assets/632049/15803877/6edd4da4-2ab9-11e6-9e8b-4e8c762d86bb.png">

**Comment by agjohnson** [comment] 2016-06-05 08:20
One of our web servers had disk issues, but the specific disk issue wasn't caught by our alerting. I've remounted the disk and builds seem to be resuming. Both API and web views would have intermittently thrown 502 errors, causing API requests to create build commands/etc to fail.

Will leave this open to monitor the issue, but almost certain builds will return to normal with this change

**Comment by jaraco** [comment] 2016-06-05 12:54
This symptom is different from what I saw in #2254, but possibly they share the same cause.

**Comment by brianjking** [comment] 2016-06-05 15:24
@agjohnson Thanks. I still have two old builds that are stuck, however, I manually started a new build and this completed as expected.

**Comment by agjohnson** [comment] 2016-06-07 21:40
@brianjking these builds will never complete, we should attempt some form of normalizing the build list, in the case an API call fails to create a build task for example. However, this is a separate issue from the one being described here

@jaraco correct, #2254 is a completely different issue.

Marking this as closed, as the immediate issue has been resolved. I'll create a separate issue to deal with the root cause of this issue.

**Closed by agjohnson** 2016-06-07 21:40 UTC
Labels: Operations, Priority: High

**Comment by dylanh724** [comment] 2024-06-06 14:44
Wait @agjohnson what was the root cause of this? I'm getting this in 2024

**Comment by humitos** [comment] 2024-06-06 15:30
@dylanh724 👋🏼 , please open a new issue explaining what you are experiencing.
