### ISSUE TITLE
Build failing because of a problem with Read the Docs

### ISSUE THREAD

**Issue by codegeschrei** [rtfd/readthedocs.org#4618] opened 2018-09-07 11:44 UTC
## Details

* Read the Docs project URL: [bigchaindb-python-driver](https://readthedocs.org/projects/bigchaindb-python-driver)
* Build URL (if applicable): [7746483](https://readthedocs.org/projects/bigchaindb-python-driver/builds/7746483/)
* Read the Docs username (if applicable): codegeschrei

## Expected Result

Build the docs

## Actual Result

There was no error during the build of the docs but the error in the picture occured

<img width="830" alt="screen shot 2018-09-06 at 18 13 20" src="https://user-images.githubusercontent.com/4203558/45217381-29c5a700-b2a4-11e8-9c1e-18c0a336ffee.png">

**Comment by stsewd** [comment] 2018-09-07 15:15
I was able to build your docs in my local instance, not sure what is happening on the servers :/

**Comment by codegeschrei** [comment] 2018-09-10 07:57
Thanks for looking in to it @stsewd 
Do you have any idea what I should do now?

**Comment by RichardLitt** [comment] 2018-09-10 22:37
@humitos Can you take a look?

**Comment by ttmc** [comment] 2018-09-11 08:53
Some more details:

- Builds of v0.5.1 docs are still working. We tried again today. See https://readthedocs.org/projects/bigchaindb-python-driver/builds/7766672/
- Builds of v0.5.1 docs are still failing for no apparent reason. See https://readthedocs.org/projects/bigchaindb-python-driver/builds/7766659/
- What changed between v0.5.1 and v0.5.2?
  - [Pull request #472](https://github.com/bigchaindb/bigchaindb-driver/pull/472/files) updated the `cryptoconditions` package in `setup.py` from cryptoconditions~=0.6.0.dev to cryptoconditions~=0.7.2. (To see what that means, see the [cryptoconditions changelog](https://github.com/bigchaindb/cryptoconditions/blob/master/CHANGELOG.rst).) It also updated python-rapidjson==0.0.11 to python-rapidjson==0.6.0
  - [Pull request #470](https://github.com/bigchaindb/bigchaindb-driver/pull/470/files) changed some code but no packages.

I suspect the root of the problem is that some packages aren't getting updated properly. Packages include Python packages and OS-level packages.

**Comment by humitos** [comment] 2018-09-11 11:00
I took a quick look into it (logs are not really helpful) and I think the problem is because of NULL chars in the install output. I'd need to take a deeper look to be sure, though.

If this is the problem, it's already fixed in #4591 but it's not already deployed.

@stsewd if you use PostgreSQL to build the docs, does it work?

**Comment by ttmc** [comment] 2018-09-11 12:15
We just merged a few things into our master branch, and now those docs (based on master) are building. See https://readthedocs.org/projects/bigchaindb-python-driver/builds/7767473/

I'm not sure if this is because of the changes we made, or something changed at ReadTheDocs.org.

**Comment by stsewd** [comment] 2018-09-11 15:37
@humitos I'll be investigating more

**Comment by stsewd** [comment] 2018-09-11 17:45
I can't replicate using postgres (10.5) with a commit previous to the null char fix

**Comment by ttmc** [comment] 2018-09-12 10:45
Update: As I write this,

- The v0.5.3 docs (== latest docs == master docs) are building fine on ReadTheDocs
- The v0.5.2 docs are failing to build on ReadTheDocs

**Comment by JoyMonteiro** [comment] 2018-09-19 09:05
The issue re-surfaced in our doc builds as well. It was building (HTML, not PDF) a few commits ago, but now even the HTML part is not going through.

https://readthedocs.org/projects/climt/builds/7807914/

**Comment by humitos** [comment] 2018-10-01 14:45
I just triggered `0.5.3` and `latest`.

Both failed because `NameError: name 'condition_details' is not defined` when executing some code under the ipython extension. This is not a RTD problem, so you should check it in your side.

> Note that `0.5.2` seems to not be active, so I can't trigger a build for it.

I'm closing this issue since it doesn't seem to be related to RTD, but please feel free to reopen if you consider. 

Also, let me know if you notice anything else and open a new issue. Thanks.

**Closed by humitos** 2018-10-01 14:45 UTC
Labels: Accepted, Bug, Needed: replication
