### ISSUE TITLE
rtfd.io (or .org) shortlinks do not support HTTPS

### ISSUE THREAD

**Issue by PeridexisErrant** [rtfd/readthedocs.org#2196] opened 2016-05-05 23:42 UTC
Specifically, chrome gives a certificate error on links such as https://pip.rtfd.io

This means that shortlinks are only usable by giving by https, which I'm not willing to do for all the links I post.

**Comment by agjohnson** [comment] 2016-05-16 19:40
Duplicate of #328

**Closed by agjohnson** 2016-05-16 19:40 UTC
