### ISSUE TITLE
sphinx autodoc for python doesn't show anything :(

### ISSUE THREAD

**Issue by DominiqueMakowski** [rtfd/readthedocs.org#2511] opened 2016-11-16 18:08 UTC
Hey,

I have [this python package](https://github.com/neuropsychology/Neuropsydia.py) that I'd like to automatically document using Sphinx. I've inserted docstrings in every functions and classes.

I made an account on ReadTheDocs, and did the setup accordingly (i.e., a docs/ dir with a conf.py file). Then, basically, I've tried almost everything: every combination of autodoc::, autofunction::, autoclass::; I tried using the same conf.py file as other packages which documented API (with specific changes made according to my case, of course); but it just doesn't work, the API page remains inexorably empty...

I just can't figure out what I'm doing wrong... 😢 

Here's the [link](https://github.com/neuropsychology/Neuropsydia.py/tree/master/docs) of the docs/ dir

## Details

* Project URL: http://readthedocs.org/projects/neuropsydia/
* Build URL (if applicable):
* Read the Docs username (if applicable):  DominiqueMakowski

## Expected Result

*Autodoc the module based on the docstrings inserted in every functions*

## Actual Result

*The API page remains empty*

**Comment by c-bata** [comment] 2016-12-07 06:15
+1 I bumped into the same problem.

**Comment by thw17** [comment] 2016-12-20 23:26
Has anyone managed to solve this?

I'm running into the same issue.  Everything is building correctly except the API page, on which only the first function on the alphabetically first submodule is visible.  Nothing in [this thread](https://github.com/rtfd/readthedocs.org/issues/1139) has helped.  I also tried moving all sphinx-apidoc output into an api directory (as some have suggested), this only adds the API structure (i.e., the submodule names, etc.), but still only the single function is visible. 

In all cases, everything builds correctly locally (e.g., `make html` locally), and the API is complete.  This seems to be specific to readthedocs.

**Comment by c-bata** [comment] 2016-12-21 01:30
In my case, the cause of sphinx autodoc not working is ReadtheDocs doesn't support Python 3.5 (refs #1990). My project uses `typing` module added from python3.5, so raised ImportError in running sphinx-build:

- build: https://readthedocs.org/projects/kobin/builds/4799776/

**Comment by humitos** [comment] 2017-03-02 17:31
@c-bata RTD supports Python 3.5 now, so you should be able to build your docs. Can you confirm that was your real issue?

**Comment by humitos** [comment] 2017-03-02 19:06
@DominiqueMakowski I think your issue is not related with a bug on RTD but how you are mocking pygame. I tried to build your own repo in a local venv and I got this:

```
/home/humitos/readthedocs/repositories/Neuropsydia.py/docs/api.rst:6: WARNING: autodoc: failed to import module u'neuropsydia'; the following exception was raised:
Traceback (most recent call last):
  File "/home/humitos/.virtualenvs/tmp-8daeadb00049b321/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/humitos/readthedocs/repositories/Neuropsydia.py/neuropsydia/__init__.py", line 4, in <module>
    from .core import *
  File "/home/humitos/readthedocs/repositories/Neuropsydia.py/neuropsydia/core.py", line 2, in <module>
    from .screen import screen, screen_width, screen_height, monitor_diagonal
  File "/home/humitos/readthedocs/repositories/Neuropsydia.py/neuropsydia/screen.py", line 7, in <module>
    screen = pygame.display.set_mode((0,0), pygame.SRCALPHA | pygame.FULLSCREEN | pygame.DOUBLEBUF | pygame.HWSURFACE)
TypeError: unsupported operand type(s) for |: 'Mock' and 'Mock'
/home/humitos/readthedocs/repositories/Neuropsydia.py/docs/api.rst:9: WARNING: autodoc: failed to import module u'neuropsydia.screen'; the following exception was raised:
Traceback (most recent call last):
  File "/home/humitos/.virtualenvs/tmp-8daeadb00049b321/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/humitos/readthedocs/repositories/Neuropsydia.py/neuropsydia/__init__.py", line 4, in <module>
    from .core import *
  File "/home/humitos/readthedocs/repositories/Neuropsydia.py/neuropsydia/core.py", line 2, in <module>
    from .screen import screen, screen_width, screen_height, monitor_diagonal
  File "/home/humitos/readthedocs/repositories/Neuropsydia.py/neuropsydia/screen.py", line 7, in <module>
    screen = pygame.display.set_mode((0,0), pygame.SRCALPHA | pygame.FULLSCREEN | pygame.DOUBLEBUF | pygame.HWSURFACE)
TypeError: unsupported operand type(s) for |: 'Mock' and 'Mock'
/home/humitos/readthedocs/repositories/Neuropsydia.py/docs/api.rst:12: WARNING: autodoc: failed to import module u'screen'; the following exception was raised:
Traceback (most recent call last):
  File "/home/humitos/.virtualenvs/tmp-8daeadb00049b321/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named screen
/home/humitos/readthedocs/repositories/Neuropsydia.py/docs/api.rst:14: WARNING: autodoc: failed to import module u'ask'; the following exception was raised:
Traceback (most recent call last):
  File "/home/humitos/.virtualenvs/tmp-8daeadb00049b321/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named ask
```

So, I did a quick search on google and I found this other project https://github.com/ntasfi/PyGame-Learning-Environment that uses pygame and autodoc and I checked its `docs/conf.py` where it does some _mock magic_.

I think should research over there. pygame seems to be a non easy library to mock :)

On the other hand, it seems the `autodoc` sphinx plugin doesn't make the sphinx command to fail and that's why the Build is marked as `Success` but it's not true. cc @agjohnson is there something we can do on these cases to detect that exception and mark the build as failed?

**Comment by c-bata** [comment] 2017-03-03 06:58
@humitos Thanks to support python3.5, my documentation was properly built by sphinx-autodoc :)
(this is my project: http://kobin.readthedocs.io/en/latest/api.html )

**Comment by DominiqueMakowski** [comment] 2017-03-03 11:00
Well first thank you a LOT guys for your help and for digging into my project 😄

So based on @humitos advices I looked into the the [other project](https://github.com/ntasfi/PyGame-Learning-Environment) I added some of their pygame-related lines into my [conf.py](https://github.com/neuropsychology/Neuropsydia.py/blob/dev/docs/conf.py#L23) (line 23, 24 and 27). 

Now the build fails (which is a good thing I guess 😆 ). Looking at the log, it seems that the problem lies within a particular object (the pygame's [surface](http://www.pygame.org/docs/ref/display.html#pygame.display.set_mode) (a screen window) created at the initialization of the module) that can't be mocked.

But still, I've no idea how to bypass this error, as the "screen" object is necessary for the other components to be initialized... 😞

Anyway thanks again!

Here's the compilation log's ending:
 
```python
...
File "/home/docs/checkouts/readthedocs.org/user_builds/neuropsydia/checkouts/latest/neuropsydia/screen.py", line 7, in <module>
    screen = pygame.display.set_mode((0,0), pygame.SRCALPHA | pygame.FULLSCREEN | pygame.DOUBLEBUF | pygame.HWSURFACE)
TypeError: unsupported operand type(s) for |: 'Mock' and 'Mock'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/neuropsydia/checkouts/latest/neuropsydia/screen.py", line 7, in <module>
    screen = pygame.display.set_mode((0,0), pygame.SRCALPHA | pygame.FULLSCREEN | pygame.DOUBLEBUF | pygame.HWSURFACE)
TypeError: unsupported operand type(s) for |: 'Mock' and 'Mock'
The full traceback has been saved in /tmp/sphinx-err-3my7x3za.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by humitos** [comment] 2017-03-03 16:39
@DominiqueMakowski the problem is because the `Mock` class doesn't have the `__or__` method and it's being used. So, another idea I have is to use the approach shown in the RTD FAQ regarding mocks and define the method `__or__` in that MagicMock class.

Just a very simple example:

```
>>> class A(object):
...   def __or__(self, other):
...     return 3
... 
>>> A() | A()
3
>>> 
```

Let me know if you were be able to make it :)

**Comment by DominiqueMakowski** [comment] 2017-03-04 11:55
@humitos I don't really understand, should I create a class in my conf.py, or in my module? Or define the __or__ method within another existing class? thanks!

**Comment by humitos** [comment] 2017-03-04 15:20
@DominiqueMakowski you have to create that class in your `conf.py` file, like here: http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

But, in your case, I think you could workaround the `|` (because of pygame) by defining the `__or__` in the class.

**Comment by their** [comment] 2017-03-13 21:39
Seeing the same behavior. Only a single module is built. Working with the pygame module, as well.

http://stackoverflow.com/questions/42740771/sphinx-and-readthedocs-io-only-one-of-four-documentation-modules-show-up-remote

Just hacked up a solution... commenting out all instances of `from pygame.locals import *` and making sure not to run pygame's while-events loop. Then build the project and get it onto readthedocs. Finally, when it is all running properly, revert to the previous code (uncomment the `from pygame.locals import *` and make sure pygame's while-events loop is once again called).

This of course is not a solution for working with webhooks... :cry:

**Comment by DominiqueMakowski** [comment] 2017-04-23 13:17
I've tried to follow your steps as best as I could. I created a [requirements.txt](https://github.com/neuropsychology/Neuropsydia.py/blob/master/requirements.txt) file in which I put all the dependencies. Then, I ticked the "install inside a virtualenv" box in the readthedocs settings and provided the requirements.txt file. I added the following lines in the [conf.py](https://github.com/neuropsychology/Neuropsydia.py/blob/master/docs/conf.py):

```python
import pygame
from pygame.locals import *

sys.modules['pygame'] = mock.Mock()
sys.modules['pygame.constants'] = mock.Mock()
```

But it doesn't work 😢  I looked at the [error](https://readthedocs.org/projects/neuropsydia/builds/5326963/) and it seems related to a wrong numpy version...

**Comment by their** [comment] 2017-04-23 17:51
Hi Dominique. Here is the built documentation: http://trumpocalypse.readthedocs.io/en/latest/. It mostly has the exact steps which were used.

Also, if it is of any use, here are the current software versions inside the virtualenv: [pip_freeze.txt](https://github.com/rtfd/readthedocs.org/files/949888/pip_freeze.txt).

**Comment by humitos** [comment] 2017-04-24 20:16
@DominiqueMakowski 

    numpy 1.12.1 is installed but numpy==1.11.2 is required by {'hrv'}

So, you have to pin numpy to that specific version since that's the one required for `hvr`. Another option, is to check if you can upgrade `hvr` to a more recent one.

**Comment by humitos** [comment] 2017-06-05 04:08
@DominiqueMakowski I'm closing this one, please feel free to reopen if you consider necessary.

**Closed by humitos** 2017-06-05 04:08 UTC
Labels: Support
