### ISSUE TITLE
Still showing .org under "Short URLs"

### ISSUE THREAD

**Issue by whit537** [rtfd/readthedocs.org#2260] opened 2016-06-08 21:10 UTC
Based on "[Securing Subdomains](https://blog.readthedocs.com/securing-subdomains/)," I would expect to see `foo.readthedocs.io` under "Shorter URLs" in the sidebar on project pages, but I still see `foo.readthedocs.org`. E.g.:

![screen shot 2016-06-08 at 5 01 41 pm](https://cloud.githubusercontent.com/assets/134455/15910852/d9e3ab6e-2d9a-11e6-9dfb-01837d9b68a5.png)

https://readthedocs.org/projects/gratipay/

[Looks like](https://github.com/rtfd/readthedocs.org/blob/9c73c8e01ff6d98af21b34926c6fbd89b0cee576/readthedocs/templates/core/project_detail_right.html#L85-L93) `PRODUCTION_DOMAIN` is [a config value](https://github.com/rtfd/readthedocs.org/blob/9c73c8e01ff6d98af21b34926c6fbd89b0cee576/readthedocs/settings/base.py#L36). Not sure how that interacts with the management interface for the site. I suspect fixing this could be more complicated than simply changing that value in `settings`, but maybe it *is* that simple. :-)

**Comment by ronakkhunt** [comment] 2016-07-14 07:43
Hi @agjohnson 
I just configured local setup would like to start with this bug.

**Comment by agjohnson** [comment] 2016-07-14 17:52
@ronakkhunt sure thing, feel free to open a PR and we can work from there. The change should be a minor template change. I believe -- without looking at it -- that the template just uses a hard-coded short URL.

**Comment by ronakkhunt** [comment] 2016-07-15 10:08
@agjohnson No it's not hard-coded. it using PRODUCTION_DOMAIN value from settings.

Snippet:
<p>
    <a href="http://{{ project.slug}}.{{ PRODUCTION_DOMAIN }}">{{ project.slug }}.{{ PRODUCTION_DOMAIN }}</a><br>
    {% if PRODUCTION_DOMAIN == "readthedocs.org" %}
    <a href="http://{{ project.slug}}.rtfd.io">{{ project.slug }}.rtfd.io</a>
    {% endif %}
  </p>

Changing PRODUCTION_DOMAIN value in not an option here.
I can hard-code "readthedocs.io", but what is this **if condition** for?

**Comment by agjohnson** [comment] 2016-07-15 16:14
@ronakkhunt the correct setting is `PUBLIC_DOMAIN`. The other instances of hardcoded domains can be changed from `.org` -> `.io`

**Comment by ronakkhunt** [comment] 2016-07-15 17:52
@agjohnson 
Okey, so final HTML block will be like this...
```html
  <p>
    <a href="http://{{ project.slug}}.{{ PUBLIC_DOMAIN }}">{{ project.slug }}.{{ PUBLIC_DOMAIN }}</a><br>
    {% if PUBLIC_DOMAIN == "readthedocs.io" %}
    <a href="http://{{ project.slug}}.rtfd.io">{{ project.slug }}.rtfd.io</a>
    {% endif %}
  </p>
```

Also I have added **PUBLIC_DOMAIN** in **context_processor.py** (or it can be added in context of view specifically)

Though I do not have production settings' file, I have tested it in local setup given **PUBLIC_DOMAIN** value in production setting is set as **readthedocs.io**.

**Comment by ronakkhunt** [comment] 2016-07-18 11:58
@agjohnson

**Comment by magnunleno** [comment] 2016-07-25 21:33
@ronakkhunt are you still looking at this issue? I'm considering to give it a try too.

**Comment by agjohnson** [comment] 2016-07-25 21:50
This looks fine, @ronakkhunt could you open a PR for this?

**Comment by ronakkhunt** [comment] 2016-07-26 05:59
Okey,
@agjohnson  Since this is not a bug, I am going to make PR from master branch.

**Comment by ronakkhunt** [comment] 2016-07-26 06:13
@agjohnson https://github.com/rtfd/readthedocs.org/pull/2335

**Comment by berkerpeksag** [comment] 2016-07-28 00:31
This was done in https://github.com/rtfd/readthedocs.org/commit/c968ff240e993fe50229098c10720637e16b11b2. Closing as 'fixed', thanks!

**Closed by berkerpeksag** 2016-07-28 00:31 UTC
Labels: Bug, Good First Bug, Needed: patch

**Comment by whit537** [comment] 2016-07-28 01:10
I'm still seeing the .org at https://readthedocs.org/projects/gratipay/. What's your release schedule like?
