### ISSUE TITLE
Installation of Django REST Framework 3.3.3 inside a Python 3 virtual environment is failing

### ISSUE THREAD

**Issue by tjanez** [rtfd/readthedocs.org#2101] opened 2016-03-30 08:50 UTC
## Issue

Our project depends on Django REST Framework. Since version 3.3.3 of the Django REST Framework was released (Mar 14 2016), `python setup.py install --force` build step fails with:
```
Running djangorestframework-3.3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-s4mu4_0o/djangorestframework-3.3.3/egg-dist-tmp-n86ore4k
warning: pypandoc module not found, could not convert Markdown to RST
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/resolwe/envs/latest/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/docs/checkouts/readthedocs.org/user_builds/resolwe/envs/latest/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/docs/checkouts/readthedocs.org/user_builds/resolwe/envs/latest/lib/python3.4/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/resolwe/envs/latest/lib/python3.4/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/resolwe/envs/latest/lib/python3.4/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/home/docs/checkouts/readthedocs.org/user_builds/resolwe/envs/latest/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-s4mu4_0o/djangorestframework-3.3.3/setup.py", line 86, in <module>
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
  File "/tmp/easy_install-s4mu4_0o/djangorestframework-3.3.3/setup.py", line 19, in read_md
    long_description = f.read()
  File "/home/docs/checkouts/readthedocs.org/user_builds/resolwe/envs/latest/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4874: ordinal not in range(128)
```

I tried to reproduce the problem locally by using the exact same commands that are used in the build log to create a new virtualenv, install dependencies with pip and finally run `python setup.py install --force`. Unfortunately, I wasn't able to reproduce the problem.

Any ideas how to debug this further?

## Details

* Project: resolwe
* Build #: 3822107

**Comment by agjohnson** [comment] 2016-04-11 17:38
It seems DRW has a readme file with non-ascii characters, but is reading the file using the ascii codec. Not sure of why this would be different on our systems, perhaps differing shell locales?

**Comment by mstajdohar** [comment] 2016-04-19 04:39
+1

**Comment by tjanez** [comment] 2016-05-27 16:52
Hi @agjohnson, thanks for your feedback!

I've investigated this further.

First I downloaded the latest Django REST Framework's README file:
```
wget https://raw.githubusercontent.com/tomchristie/django-rest-framework/master/README.md
```

Then I used IPython to explore the code that gave errors on RTD build server:

```
$ ipython3
Python 3.4.2 (default, Jul  9 2015, 17:24:30) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: readme = open('README.md', 'rb').read()

In [2]: decode_utf8 = readme.decode('utf8')

In [3]: decode_ascii = readme.decode('ascii')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-3-d78541429a36> in <module>()
----> 1 decode_ascii = readme.decode('ascii')

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4978: ordinal not in range(128)

In [4]: bytes(readme[4978:4981]).decode('utf-8')
Out[4]: '’'
```

Indeed, the README contains a non-ascii character.

Then I ran an interactive debugging session which confirmed that on my machine, `getprefferedencoding()` returns `UTF-8`, which explains why it can read the `README.md` without a problem:

```
$ cat << EOF > test.py
import ipdb; ipdb.set_trace()
open('README.md', 'r').read()
EOF

$ python3 test.py 
> /home/tadej/test.py(2)<module>()
      1 import ipdb; ipdb.set_trace()
----> 2 open('README.md', 'r').read()

ipdb> s
--Call--
> /home/tadej/.virtualenvs/temp-py3/lib64/python3.4/_bootlocale.py(23)getpreferredencoding()
     22     else:
---> 23         def getpreferredencoding(do_setlocale=True):
     24             assert not do_setlocale

ipdb> n
> /home/tadej/.virtualenvs/temp-py3/lib64/python3.4/_bootlocale.py(24)getpreferredencoding()
     23         def getpreferredencoding(do_setlocale=True):
---> 24             assert not do_setlocale
     25             result = _locale.nl_langinfo(_locale.CODESET)

ipdb> n
> /home/tadej/.virtualenvs/temp-py3/lib64/python3.4/_bootlocale.py(25)getpreferredencoding()
     24             assert not do_setlocale
---> 25             result = _locale.nl_langinfo(_locale.CODESET)
     26             if not result and sys.platform == 'darwin':

ipdb> n
> /home/tadej/.virtualenvs/temp-py3/lib64/python3.4/_bootlocale.py(26)getpreferredencoding()
     25             result = _locale.nl_langinfo(_locale.CODESET)
---> 26             if not result and sys.platform == 'darwin':
     27                 # nl_langinfo can return an empty string

ipdb> n
> /home/tadej/.virtualenvs/temp-py3/lib64/python3.4/_bootlocale.py(34)getpreferredencoding()
     32                 # interpreter.
     33                 result = 'UTF-8'
---> 34             return result

ipdb> n
--Return--
'UTF-8'
```

Could you check what `locale.getprefferedencoding()` returns on RTD build servers?
Maybe shell locate is not set correctly so that Python would use UTF-8 by default?

**Comment by berkerpeksag** [comment] 2016-07-15 14:45
Applications should not rely on platform's default locale settings. In this case, I think this is a bug in DRF and it looks like they have already fixed it in https://github.com/tomchristie/django-rest-framework/commit/b04bd8618ca956c2ceab36a8729cab822f0cff93.

**Comment by berkerpeksag** [comment] 2016-07-15 15:13
This is basically a duplicate of #1986.

**Closed by berkerpeksag** 2016-07-15 15:13 UTC
Labels: Support
