### ISSUE TITLE
Builds fail without explanation

### ISSUE THREAD

**Issue by vfaronov** [rtfd/readthedocs.org#3006] opened 2017-07-18 15:52 UTC
## Details

* Project URL: https://readthedocs.org/projects/httpolice/ (and others)
* Build URL (if applicable): https://readthedocs.org/projects/httpolice/builds/5704942/ (and others)
* Read the Docs username (if applicable): vfaronov

## Expected Result

Builds should succeed, or at least produce an explanation of why they failed.

## Actual Result

In the past few days* most of my builds have been failing without explanation. I start a build, it shows up as “Triggered” or “Cloning”, then I refresh the page and it’s already “Failed”. On the build page, all I see is:

![rtfd-fail](https://user-images.githubusercontent.com/300211/28326368-41d3c26c-6be9-11e7-96e6-7cc29243a755.png)

This is happening with various versions, various projects. Sometimes I can unbreak it by wiping the version, or by disabling it in *Admin* → *Versions* and enabling again. Other times I can’t. Right now the [httpolice](https://readthedocs.org/projects/httpolice/) project is stuck. I have not been able to discern a pattern.

\* “In the past few days” may not be relevant information because I hadn’t triggered a build for some time prior to that.

**Comment by towicode** [comment] 2017-07-19 23:54
This is happening to me too. 

Project URL:  https://readthedocs.org/projects/portalmehpc/
Build URL: https://readthedocs.org/projects/portalmehpc/builds/5713163/
Username: Toddwickizer

Here is an image:
[http://i.imgur.com/bBHyznB.png](http://i.imgur.com/bBHyznB.png)

Zero information at all. it builds locally just fine with make html. I am very new to RTD so any help would be great!

**Comment by EricWilbanks** [comment] 2017-07-20 02:40
Identical issue here. My last successful build was triggered July 8, 2017 1:15am and my next-most recent changes (today) result in the same Unexpected Error. 

Project URL: https://readthedocs.org/projects/fasealign/
Build URL: https://readthedocs.org/projects/fasealign/builds/5713532/ (most recent)
RTD Username: EricWilbanks

**Comment by dhermes** [comment] 2017-07-20 04:19
Same here.

-   Project URL: https://readthedocs.org/projects/bezier/
-   Build URLs
    -   https://readthedocs.org/projects/bezier/builds/5713807/
    -   https://readthedocs.org/projects/bezier/builds/5713690/
    -   https://readthedocs.org/projects/bezier/builds/5713589/
- RTD Username: dhermes

**Comment by willingc** [comment] 2017-07-20 04:56
Hi @agjohnson @ericholscher, I tried to troubleshoot these builds without much success. It looks like @towicode's build logs that it was passing 1 day ago but failing today. 

Interestingly, it looks like @vfaronov's project build is passing now.

I wonder if the 24 hour max age in #3005 introduced a weird caching issue for builds.

**Comment by vfaronov** [comment] 2017-07-20 12:02
@willingc 

> Interestingly, it looks like @vfaronov's project build is passing now.

As I mentioned, this issue seems to be intermittent or with non-obvious conditions. I just tried triggering stable and got the same failure: https://readthedocs.org/projects/httpolice/builds/5715813/

I’m not sure my issue is the same as that of others here, as in my builds there’s not even that one line of output about creating a virtualenv.

> I wonder if the 24 hour max age in #3005 introduced a weird caching issue for builds.

I first observed this issue 6 days ago, earlier than #3005.

**Comment by vfaronov** [comment] 2017-07-20 12:23
Something else I just noticed: [some](https://readthedocs.org/projects/httpolice/builds/5715901/) of my failed builds have the (correct) commit hash listed on their page:

![rtfd-fail-with-sha](https://user-images.githubusercontent.com/300211/28417043-3d96edd8-6d5f-11e7-9a6c-a2bfb53bf53a.png)

while [others](https://readthedocs.org/projects/httpolice/builds/5715851/) don’t even have that:

![rtfd-fail-without-sha](https://user-images.githubusercontent.com/300211/28417054-4bdcae5a-6d5f-11e7-9a4e-5e9879da33ac.png)

**Comment by dhermes** [comment] 2017-07-21 20:41
My two projects that were failing have started succeeding again ([e.g. 1][1], [e.g. 2][2])

[1]: https://readthedocs.org/projects/bezier/builds/5723242/
[2]: https://readthedocs.org/projects/google-cloud-python/builds/5719034/

**Comment by willingc** [comment] 2017-07-22 04:29
Thanks @dhermes. It looks like everyone's docs but @vfaronov's are building now.

@vfaronov Have you tried wiping and cleaning the builds that are failing?

**Comment by vfaronov** [comment] 2017-07-22 08:37
@willingc 

> Have you tried wiping and cleaning the builds that are failing?

Yes, I have.

**Comment by willingc** [comment] 2017-07-24 15:50
Recent PRs #3009 and #2979 appear to have resolved this issue. 

@vfaronov, your doc build is now reporting passing https://readthedocs.org/projects/httpolice/builds/5732769/ Do you wish to go ahead and close this issue out?

**Comment by vfaronov** [comment] 2017-07-24 16:19
@willingc Thank you! My affected projects and versions seem to be working right now. But, if you don’t mind, I’ll wait until tomorrow before closing this issue, just to be sure.

**Comment by vfaronov** [comment] 2017-07-25 20:49
@willingc I’m afraid the problem persists: https://readthedocs.org/projects/httpolice/builds/5740724/

**Comment by willingc** [comment] 2017-07-25 21:01
@vfaronov This recent failure may be unrelated as I am having some build failures currently. Will you check again in a few hours? Thanks.

**Comment by vfaronov** [comment] 2017-07-26 06:02
@willingc Still failing: https://readthedocs.org/projects/httpolice/builds/5742426/

**Comment by willingc** [comment] 2017-07-26 22:14
@vfaronov I spent some time looking at your source code. Your docs build environment and process are both a bit different than common sphinx builds on RTD. I spent about 30 minutes trying to work on getting your docs to build myself. I suspect that the reason your docs are not building is due to a regression introduced in either your code or RTD's code. I would recommend getting the docs to build correctly using a conda environment or requirements.txt file (one that is not in `tools` subdirectory) as well as a readthedocs.yml file in your root directory.

Good luck. The jupyterhub and nbgrader docs along with others from Project Jupyter are good examples.

**Comment by vfaronov** [comment] 2017-07-27 11:09
@willingc 

> Your docs build environment and process are both a bit different than common sphinx builds on RTD. 

I did recently add something unusual to the [HTTPolice](https://readthedocs.org/projects/httpolice/) project docs. And I started observing this issue about the same time.

But this issue now also affects previous versions of this project — such as [0.5.2](https://github.com/vfaronov/httpolice/releases/tag/0.5.2) (build [#5750046](https://readthedocs.org/projects/httpolice/builds/5750046/)) — which had [a straightforward Sphinx configuration](https://github.com/vfaronov/httpolice/blob/869d924174e3005ff2f8ef37437e17a67eeddcb6/doc/conf.py) that had not been touched in a while, and which did not experience this issue a few months ago. I even disabled “Install your project inside a virtualenv” and it’s still the same.

Do you think deleting the project from Read the Docs and creating it anew might help?

**Comment by vfaronov** [comment] 2017-07-27 11:25
Actually, the [first manifestation of the issue](https://readthedocs.org/projects/httpolice/builds/5688660/) was *before* I [started changing my Sphinx conf](https://github.com/vfaronov/httpolice/commit/1c53462a74f6b3cf0ff8476ce519a1e1bc214f97), so these recent changes can’t be the culprit.

**Comment by willingc** [comment] 2017-07-27 15:29
I wouldn't delete the project since it is serving your cached docs. I spent about an hour trying to get it to work yesterday. 

@ericholscher @agjohnson Is there a way to completely reset a build other than using **Wipe** in the version settings?

**Comment by leotsarev** [comment] 2017-07-28 15:15
Same for me http://readthedocs.org/projects/joinrpg/builds/5756878/

**Comment by willingc** [comment] 2017-07-28 16:36
@leotsarev Your issue is different. You should add a requirements.txt file.

**Comment by dair** [comment] 2017-07-28 17:16
@willingc I've added requirements.txt; no effect. I can download the project onto my Linux host, `pip install -r requirements.txt` and after that `make html` works fine. But still not on RTD unfortunately.

(Same project as @leotsarev's, https://readthedocs.org/projects/joinrpg/builds/5757539/)

**Comment by vfaronov** [comment] 2017-08-01 11:08
I was mistaken when I originally said that I had multiple affected projects. Of my projects, only [one](https://readthedocs.org/projects/httpolice/) seems to be affected by this issue. Other two were suffering from an [unrelated issue](https://github.com/rtfd/readthedocs.org/issues/2398), which had confused me.

**Comment by pierre-24** [comment] 2017-08-05 14:39
[Our project](http://readthedocs.org/projects/zds-site/builds/) seems affected since a month, without any explanation.

**Comment by willingc** [comment] 2017-08-05 23:00
@vfaronov It looks like your docs are passing now.

@pierre-24 In the RTD admin page for the project, are you building in a virtualenv using setup.py?

**Comment by vfaronov** [comment] 2017-08-05 23:05
@willingc 

> It looks like your docs are passing now.

No, they are failing intermittently, like before.

**Comment by pierre-24** [comment] 2017-08-06 11:18
@willingc Yes we are. When I [build a branch which was part of a recent pull request](https://readthedocs.org/projects/pierre-24/builds/5794320/) (mais in the end of July), it builds without any issue.

**Comment by pierre-24** [comment] 2017-08-09 18:23
So, now that I can check, [this project](https://readthedocs.org/projects/zds-site/) and [that one ](https://readthedocs.org/projects/pierre-24/) have the same configuration, and are based on the same github repo. The second one is just a fork of the first one. But the build of the first one systematically fails (no matter the version, the branch or the tag), while there is no problem with the second. And I really don't understand why.

**Comment by pierre-24** [comment] 2017-08-16 19:10
any news ?

**Comment by willingc** [comment] 2017-08-16 19:23
@pierre-24 I'm traveling for the next few weeks. Pinging @ericholscher @agjohnson re: any ideas on the first build???

**Comment by leotsarev** [comment] 2017-08-23 06:48
Sorry for bugging, but any news?

**Comment by leotsarev** [comment] 2017-09-11 09:34
Guys, what's the timeframe? Should we consider migrating out of RTD? What we can do to help investigating?

**Comment by agjohnson** [comment] 2017-09-15 19:45
I've addressed this in #3073. There is a hotfix out, folks should test their builds again

**Comment by vfaronov** [comment] 2017-09-17 13:04
Thank you @agjohnson, my project seems to be OK now. @leotsarev @pierre-24 what about yours?

**Comment by leotsarev** [comment] 2017-09-17 13:22
Last build passed. I'll play around and report if it is stable.
Anyways, thanks a lot, that's great.

**Closed** 2017-09-20 08:31 UTC
