### ISSUE TITLE
Search results show include directives instead of doc excerpts

### ISSUE THREAD

**Issue by srpearce** [rtfd/readthedocs.org#2405] opened 2016-09-08 17:44 UTC
## Details
- Project URLs:
  https://readthedocs.org/projects/edx-partner-course-staff/
  https://readthedocs.org/projects/open-edx-building-and-running-a-course/
  https://readthedocs.org/projects/edx-guide-for-students/
  https://readthedocs.org/projects/open-edx-learner-guide/
- Build URL (if applicable):
  http://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/
  http://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/
  http://edx.readthedocs.io/projects/edx-guide-for-students/en/latest/
  http://edx.readthedocs.io/projects/open-edx-learner-guide/en/latest/
- Read the Docs username (if applicable): edx
## Expected Result

When I search any of these docs for a term, the results list shows excerpts from the topics that contain that term.  

![screenshot 663](https://cloud.githubusercontent.com/assets/3493253/18360026/60b67c62-75ca-11e6-9452-0ded7f000a83.png)
## Actual Result

When I search any of these docs for a term, the results list shows **.. include** directives and paths rather than excerpts from topics that contain the search term.

![screenshot 662](https://cloud.githubusercontent.com/assets/3493253/18360015/5bbbf12e-75ca-11e6-8cd4-b7f975e695c7.png)

**Note**: We had this problem when we started using RTD, but many months ago we paid for an enhancement that allows non-alphanumeric characters in searches. Since we added the enhancement, we've seen excerpts from the docs when we perform searches. However, we noticed today that the search results have returned to showing only **.. include** directives and paths. We are expecting a notable increase in use of our documentation in September and October, so meaningful search results are important.

**Comment by humitos** [comment] 2017-02-23 20:07
@srpearce is this still happening to you? I can't reproduce the error.

If this is already fixed and you know where, please link the PR. Otherwise, I will close it as invalid.

**Comment by srpearce** [comment] 2017-02-24 15:37
@humitos It seems to have been resolved. Thanks.

**Comment by humitos** [comment] 2017-02-24 17:41
Thanks!

**Closed by humitos** 2017-02-24 17:41 UTC
Labels: Status: invalid
