### ISSUE TITLE
Support conda for builds

### ISSUE THREAD

**Issue by mrocklin** [rtfd/readthedocs.org#857] opened 2014-07-14 16:21 UTC
Read the Docs Conda Support
===========================

This will add the ability to generate documentation with conda environments on Read the Docs. This is mainly useful for libraries with large C dependencies, including many packages in the Scentific Python ecosystem.

Task List
------------

- [x] Add Project option to use conda
- [x] Abstract the "environment path" in the builders to respect conda & virtualenv
- [x] Ensure cleanup of conda environment in wiping & other env delete scenarios 
- [x] Ensure Python 2 & 3 support
- [x] Write tests for proper conda environment setup
- [x] Document conda support
- [ ] Write a topical guide for Choosing a Build Environment
- [ ] Optional: Investigate [pruning](https://github.com/conda/conda-env/pull/195)

Abilities
---------

You will be able to specify a conda environment.yml file,
and Read the Docs will install these dependencies in your build environment.

Considerations
--------------

Read the Docs will keep seperate virtualenv & conda directories:

* /user_builds/<slug>/env for pip
* /user_builds/<slug>/conda for conda

Users will be able to define a way to install packages for a project:

* None
* Pip
* Conda

Read the Docs will need to change it's build code so that we don't hard-code virtualenv paths. We'll need to vary our environment creation, as well as bin path's for executables, based on the backend environment. 

The other main thing is that we'll also need to install Sphinx & other build dependencies into the conda environment. We will continue to use pip for this, and it should be transparent, other than using the pip executable in the conda environment instead of the virtualenv.

It should also be noted that `miniconda` has a different install process from Python 2 and 3 -- also they recommend installing it from their bash scripts instead of pip. I hope that we will be able to use pip, as it will simplify our installation, and won't require an update to a bash script on version upgrades. We will have to see if we hit issues in testing. 

Cleanup
-------

Read the Docs will manage conda environment deletion on the removal of a project or version.

Documentation
-------------

We will need to add information about conda support to our documentation. We might want to add a topic guide around installing requirements, along with adding a specific reference for how to use & enable conda support.

Sponsorship
------------

This work is being funded by [Clinical Graphics](https://www.clinicalgraphics.com/) -- many thanks for their support of Open Source.

**Comment by faph** [comment] 2015-01-17 13:26
+1

I'd love to have conda support in RTD. In the same way that Travis CI does it. http://conda.pydata.org/docs/travis.html

**Comment by tswicegood** [comment] 2015-03-10 21:32
FWIW, if RTD used buildpacks like Heroku and Cloud Foundry, there's a [conda-buildpack][1] that can detect a Conda `environment.yml` file and spin that up.  That spec supports creating environments that have both Conda and pip packages in them.  If nothing else, its [`conda_compile`][2] script might serve as a good reference is someone wants to take a stab at implementing this in RTD.

[1]: https://github.com/conda/conda-buildpack
[2]: https://github.com/conda/conda-buildpack/blob/master/bin/steps/conda_compile

**Comment by jlyons871** [comment] 2015-03-10 21:33
I am currently working on a project which uses [numba](https://github.com/numba/numba) and am trying to upload the project onto RTD. This cannot currently be done as it requires the llvm compiler. Is it possibilt for RTD either to install llvm and include it in the system packages under the Advanced Settings, or add support for conda?

**Comment by ncoghlan** [comment] 2015-03-11 23:56
Using buildpacks or a container tech like Docker to do builds would require fundamentally redesigning the way ReadTheDocs works. On the other hand, that might not be a bad idea at some point, especially as Docker based public cloud services with a grants program for open source projects come online

Disclosure: I work for Red Hat, OpenShift Online has a grants program that includes open source projects in its scope, our next generation architecture is based on Docker & Kubernetes, and I personally believe that hosting a valuable service like RTFD would be a great way for us to support the community. So while porting to the *current* OpenShift architecture likely wouldn't make sense, porting to Docker/Kubernetes would open up both Google Container Engine and a future version of OpenShift Online as hosting options.

**Comment by Juanlu001** [comment] 2015-04-25 05:57
:+1: for the addition of conda, I am interested in hosting a package depending on numba too.

**Comment by pitrou** [comment] 2015-05-05 17:16
While conda isn't supported, I've tried at least to disable the setup.py running and I'm having this weird error:
https://github.com/rtfd/readthedocs.org/issues/1240

**Comment by cdeil** [comment] 2015-05-06 15:53
:+1: I know a few packages that need a more recent scipy or matplotlib for their docs build and `pip install` on readthedocs fails ... conda would be a very nice solution!

**Comment by chebee7i** [comment] 2015-06-14 17:25
Practically, won't this be necessary if you want to build older versions of your documentation that require older versions of NumPy, matplotlib, possibly with different APIs from whatever version of NumPy is installed system-wide?

**Comment by shoyer** [comment] 2015-06-14 18:32
@chebee7i practically speaking, matplotlib and numpy have strong backwards compatibility guarantees, so I'm not too worried about API changes for them. Though matplotlib has been talking about a 2.0 release with a new default colormap...

**Comment by chebee7i** [comment] 2015-06-14 19:19
@shoyer but functionality does change between versions and this can cause the documentation to be wrong, especially if you rely on buildtime-generated documentation through the sphinxext IPython directive. And I am thinking much more generally than matplotlib and numpy, but even extending to just pandas reveals very recent backwards compatibility changes.

**Comment by jakirkham** [comment] 2015-07-24 16:43
+1 for `conda` support.

**Comment by Carreau** [comment] 2015-09-24 00:55
+1, i'm currently trying to update old docs that use both Python, R and rpy2, I can almost trivially have everything working fine in a conda 2.7 env.

**Comment by jakirkham** [comment] 2015-09-24 16:02
Am I completely mistaken or does readthedocs allow us to use docker ( http://read-the-docs.readthedocs.org/en/latest/development/buildenvironments.html#configuration ) ( http://read-the-docs.readthedocs.org/en/latest/api/doc_builder.html#readthedocs.doc_builder.environments.DockerEnvironment )? If so, there are pre-existing images for miniconda and miniconda3 ( https://hub.docker.com/u/continuumio/ ), which could be used here.

**Comment by ericholscher** [comment] 2015-11-09 13:48
Went ahead and updated the description here to flush out the needed work. If folks have any thoughts feel free to comment here. I should be working to add conda support in the next few weeks.

**Comment by ankostis** [comment] 2015-11-09 15:26
+1

Just make sure you provide `conda` through some proxy, to speedup download and avoid extra charges..

**Comment by shoyer** [comment] 2015-11-10 03:17
I am so psyched that this is finally happening! Let me know if you need any help testing this out.

A few notes:
- I don't think you need separate miniconda/miniconda3 options. That simply sets the default Python version packaged with the installer. You can also simply set `python=3.5` (for example) in `environment.yml’. 
- Installling from the miniconda binary may not be so bad, given that the first step in the script should probably be `conda update conda`.

**Comment by Korijn** [comment] 2015-11-10 14:11
> [ ] Munge `name` property of `environment.yml` to proper RTD value

Turns out you can override the name in the command using the `-n` parameter. See the `create` command help here:

```
C:\Development\Projects>conda env create -h
usage: conda-env-script.py create [-h] [-f FILE] [-n NAME] [-q] [--force]
                                  [--json]
                                  [remote_definition]

Create an environment based on an environment file

Options:

positional arguments:
  remote_definition     remote environment definition / IPython notebook

optional arguments:
  -h, --help            Show this help message and exit.
  -f FILE, --file FILE  environment definition file (default: environment.yml)
  -n NAME, --name NAME  environment definition
  -q, --quiet
  --force               force creation of environment (removing a previously
                        existing environment of the same name.
  --json                Report all output as json. Suitable for using conda
                        programmatically.

examples:
    conda env create
    conda env create -n name
    conda env create vader/deathstar
    conda env create -f=/path/to/environment.yml
```

**Comment by ericholscher** [comment] 2015-11-12 08:47
@Korijn Great -- thanks for the clarification. I will update the ticket.

**Comment by ericholscher** [comment] 2015-11-25 19:45
I have a basic implementation working, and I'd love to test this against a repo that someone is using in the wild. @Korijn do you have a good repo that has an environment file checked into it?

**Comment by faph** [comment] 2015-11-28 22:04
If you're still looking for test repos, feel freel to pull from https://github.com/OpenHydrology/floodestimation. Does the environment.yml need to have sphinx etc in it?

**Comment by ericholscher** [comment] 2015-11-30 22:25
@faph Great, thanks. I don't think that it will need Sphinx specified. It will use the same order of operations that we support currently:

* Environment Creation
* Dependency Installation (Sphinx, Mkdocs, etc)
* User Package Installation

So the plan is to run `conda env update` inside of our environment, where we have already installed a base set of packages. This means you can specify a different version of Sphinx, etc. but we will have a default set that is used if they aren't specified.

**Comment by faph** [comment] 2015-12-01 09:10
Sounds sensible, thanks.

**Comment by ericholscher** [comment] 2015-12-01 23:48
@faph hmm, I'm getting a `Error: Invalid package specification: appdirs 1.4*` from conda now.

As far as I can tell, the format for the environment file isn't documented anywhere :/ I'm using `conda 3.18.3`, which I believe is up to date. Does that work locally for you?

**Comment by shoyer** [comment] 2015-12-02 00:06
There's some documentation for `environment.yml` here: https://github.com/conda/conda-env#environment-file-example

It looks like @faph provided you with an invalid file -- it's missing some equals signs. This version works:
```
name: env

channels:
- https://conda.anaconda.org/openhydrology

dependencies:
- python
- appdirs=1.4*
- sqlalchemy=0.9*
- numpy=1.9*
- scipy>=0.16
- lmoments3>=1.0.2
```

**Comment by faph** [comment] 2015-12-02 09:03
Sorry! Thanks. I'll also get this wrong between `meta.yml`, `environment.yml` and `conda install x`!

Will update in the repo.

**Comment by ericholscher** [comment] 2015-12-02 18:56
Hrm, I've run into another issue, where the `conda env update` command doesn't accept the `--prefix`` argument. It only accepts a name, which doesn't seem to let you override where that environment might be stored (it defaults to `$HOME/miniconda/envs`, but doesn't seem to allow overriding this path).

I'm looking into this more, but wonder if anyone has thoughts here.

**Comment by Korijn** [comment] 2015-12-02 19:06
You could do an additional call to `conda install` afterwards to make sure the right versions of sphinx etc are installed?

I'll provide a sample repo soon, sorry for the delay. :)

**Comment by shoyer** [comment] 2015-12-02 19:40
Suppose you have a conda environment installed at `$CONDA_ENV_PATH`.  In my tests, `$CONDA_ENVPATH/bin/conda env update` has some weird behavior: it both updates the conda environment the command is run from AND installs a new environment at the name provided in `environment.yml`. This must be a bug...

**Comment by faph** [comment] 2015-12-02 20:00
You should be able to set `envs_dir` in conda config. If you set that to your preferred path you should be able to create and update envs as per original plan. Just use --name instead of --prefix.

**Comment by ericholscher** [comment] 2015-12-02 22:15
Sounds like `CONDA_ENVS_PATH` is what I was looking for, for overriding where it looks for the named environment. This is a hacky solution, and I'd prefer to just use the `--prefix`, like in the conda env creation command, but that will at least give a path forward for now.

@shoyer Hmm, that definitely sounds like a bug.

I will hopefully have this at least to the point where I can post a Work in Progress PR in the near future.

**Comment by faph** [comment] 2015-12-03 13:03
Before creating the environment, you can just do:

`conda config --add envs_dirs path/to/envs`

Then you can just `conda create env --name rtd_env python sphinx`.

**Comment by jakirkham** [comment] 2015-12-21 20:39
> I will hopefully have this at least to the point where I can post a Work in Progress PR in the near future.

Sounds exciting, @ericholscher.

So, there are many ways to install stuff with `conda` and I'm trying to get a grasp on how this is going to work. I see the `environment.yml` file has been discussed. There is also a `bdist_conda` subcommand for `python setup.py` to build a `conda` package. Finally, some cases provide a `*.recipe` or otherwise named directory with a recipe and scripts to build the package with `conda-build`. In the last two cases, the package must then be explicitly installed after building, but it will pull all runtime dependencies with it. If there are other cases, I have missed feel free to add.

How do you think these cases should be handled? Is there some way for us to specify to use how we would prefer it to be installed. In the simplest case, it could be a shell script, but if you have some better ideas I would be interested to hear.

**Comment by faph** [comment] 2015-12-21 21:09
The most common approach seems to be to create first the environment with requirements (either using a full `environment.yml` file or requirements file) and then to install the package into that with `python setup.py install`. See for example http://conda.pydata.org/docs/travis.html

The alternative is first to build the package using the conda recipe (the folder that often has the word `recipe` in it). Then install that into a new environment using the `--use-local` option. I think this option is mostly used for people who want to test building the conda package (and optionally deploy it to say anaconda.org). I think this option is overkill for RTD. Also, the recipe sometimes lives in a different place/repo than the package's source code.

Imho RTD could just stick with the `environment.yml` file. It would be nice to be able to let the user specify the actual name of the file, for example if the requirements for building the docs are different than say testing, production.

**Comment by ericholscher** [comment] 2015-12-30 20:57
This has now been deployed. We are supporting the `environment.yml` file for now.

You can see more in the docs here: http://docs.readthedocs.org/en/latest/conda.html -- It would be great to have folks test this out. I ran into some issues during development with python version mismatches and some of the other interesting parts of conda. Let me know if it isn't working for folks so we can make it work better.

**Comment by faph** [comment] 2015-12-31 02:59
Excellent, many thanks!

I tried running it on one of my repos (develop branch) but I'm afraid it failed, see https://readthedocs.org/projects/floodestimation/builds/3601598/ .

Not sure If I need to do anything to trigger a conda build. I just supplied the `readthedocs.yml` (https://github.com/OpenHydrology/floodestimation/blob/develop/readthedocs.yml). I've still ticked the option to install the package itself with `setup.py`.

I'm asuming I should see some conda build steps in the output log if it's recognising the `conda.file` key.?

**Comment by ivoflipse** [comment] 2015-12-31 08:12
@faph the problem is that you only specified the openhydrology channel (apart from the default channel). None of these channels seem to contain the sqlalchemy you requested.

I just ran `conda search sqlalchemy` and it shows that 0.9.* only supports Python versions up to 3.4, so if the python3 running on readthedocs is Python 3.5, it won't find the default sqlalchemy package. 

This means you'll either have to pin your environment to python ==3.4 or build your own conda package for whatever version of sqlalchemy you intend to use and upload it to your openhydrology channel or lastly add the channel url to your channels list of someone who has the package you're after ([look here to find an appropriate one](https://anaconda.org/search?q=platform%3Alinux-64+type%3Aconda+sqlalchemy))

**Comment by ivoflipse** [comment] 2015-12-31 08:26
Scratch that, I misread where the error occurred. Given where it seems to call your code:
`"/home/docs/checkouts/readthedocs.org/user_builds/floodestimation/envs/develop/lib/python3.4/site-packages/floodestimation-0.7.1+3.g05e75eb-py3.4.egg/floodestimation/db.py"`
I think perhaps your environment is not activated ? Because your environment file specifies the name `env` and here it's running from `develop`. 

Upon closer inspection, none of the steps mention creating your conda environment, so I wouldn't know how your dependencies could be available in the `develop` environment.

Also is the pip install task supposed to install these packages in the user's environment? Because then I hope that doesn't cause issues if any of the dependencies happen to clash. But I must admit that I don't fully understand how RTD builds the docs.

**Comment by faph** [comment] 2015-12-31 13:14
Ok, I got a bit further this morning. Latest build (still failing) here: https://readthedocs.org/projects/floodestimation/builds/3602292/. At least it's now mentioning the conda install steps. So far it does:

1. Create conda environment with just python, named after my git branch `develop`. Note that it installs Python 2!
2. Conda install sphinx etc.
3. Pip install mkdoc, readthedocs-sphinx-ext, recommonmark (I always get nervous when doing pip installs in a conda environment, probably should try to build conda packages for this)
4. Conda env update, using my `environment.yml` file. (This throws some warnings from the system python in `/usr/local/lib/python2.7` although it completes without *errors*).
5. Run `sphinx-build`. Fails on missing `sphinx` package!

So it seems that some of the packages installed initially into the environment don't survive the various subsequent steps, possibly caused by a change from Python 2 to Python 3 and/or some pip installs halfway through.

Just a thought, would it be cleaner to let the user specify all dependencies, including sphinx? Since we've got the `conda.file` key in the RTD yaml config, it's no bother just to create a `environment-rtd.yml` file with the sphinx dependencies. This makes it explicit what's required and everything can get installed in one go with a clean `conda env create` from the environment file. We could create a rtd channel on anaconda.org containing all the sphinx dependencies including sphinx extensions to make is easier for people to specify the dependencies as conda packages without having to hunt for or build them.

**Comment by faph** [comment] 2015-12-31 13:19
@ivoflipse RTD is taking care of environment naming and activating, that bit seems to work. The conda environments seems to be at `/home/docs/checkouts/readthedocs.org/user_builds/{repo}/conda/{branch}`. With `{branch}` being the environment name which gets subsequently used in conda's `--name` argument.

I don't know where the conda root environment lives, but that should not affect the build process. Conda gets called ok.

**Comment by ivoflipse** [comment] 2015-12-31 14:16
I think it would be a good idea to have an RTD conda organization, which hosts all the packages for all supported platforms. That way you know it should always work for everyone with minimal effort. 

For debugging how everything is configured, you should try calling `conda info -a` which will show how everything is configured. Runing `conda list develop` will show you want is currently present in your environment. This would make it easier to debug whether everything is present or not.

But I think the culprit is that you forgot to call `source activate develop` before calling sphinx-build. I reckon that since it's in your environment's bin folder, you should be able to simply call:
`source activate develop`
`sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`
and have it build the docs.

**Comment by faph** [comment] 2015-12-31 15:10
Not sure who you mean with "you". I don't need to/cannot activate an environment, RTD should take care of that. You're probably right though that the command:

`python /home/docs/checkouts/readthedocs.org/user_builds/floodestimation/conda/develop/bin/sphinx-build ...`

calls the wrong Python. By the way, should they not drop `python` from the command altogether because `sphinx-build` is the executable itself? I'm not too familiar with Python entry points on Linux...

**Comment by ericholscher** [comment] 2015-12-31 18:57
@faph Ah -- I hit this issue in dev. Since you're specifying the Python version in your environment, we're installing "python" with conda -- then installing Sphinx with pip, and then re-installing python 3.4 from your environment.yml -- this means that python environment doesn't have the dependencies that we installed in it.

I'm not sure the best way to work around this, other than putting this in your YAML config:

```
conda:
   file: environment.yml
python:
   version: 3.4
```

Which will install the proper version of Python the first time, I believe. I also hit the issue with it not being installed properly. This file got the build working:

```
conda:
   file: environment.yml
python:
   version: 3.4
   setup_py_install: true
```

**Comment by faph** [comment] 2015-12-31 19:51
Perfect! Many thanks - this works. Very pleased to be able to drop my `numpy` and `scipy` mocking!

I like the RTD yaml config file by the way. 

I'm not so sure about the pre-installed packages though, whether that's the cleanest. Would it be worthwhile adding an option to the yaml config file to allow a "bare" environment, purely from the specified `environment.yml` file?

**Comment by ericholscher** [comment] 2015-12-31 19:55
Awesome -- We're excited about the YAML file as well :)

I think it makes sense to be able to run with a clean environment and just support the environment defined in the file. From what I can tell, you can't create a conda environment with an environment file with `conda create`, Perhaps we could do `conda env create -n <version> -f environment.yml` if you enable the bare option, instead of doing a `conda create`.

To be honest, I find all the CLI interfaces to conda a bit confusing :)

**Comment by faph** [comment] 2015-12-31 20:02
The only annoying thing with conda is the difference between plain `conda` and the `conda env` sub-command. Apart from that, it's pretty robust.

`conda env create -n <version> -f <config.conda.file>` would be awesome.

**Comment by jakirkham** [comment] 2015-12-31 21:08
Sorry if I'm not following (getting over a cold), can one not specify the `python` version in `environment.yml`?

**Comment by Korijn** [comment] 2016-01-01 09:22
Sure you can...

```
name: myenv
dependencies:
  - python ==3.5
```

**Comment by faph** [comment] 2016-01-01 11:26
@jakirkham Yes, but currently RTD pre-creates a conda environment with just python and sphinx etc. To make sure this pre-created environment has the correct version you MUST specify the python version (also) in `readthedocs.yml`.

**Comment by jakirkham** [comment] 2016-01-01 22:10
@faph, wouldn't specifying the Python version in `environment.yml` make sure it is properly upgraded or is there some other magic going on behind the scenes?

**Comment by faph** [comment] 2016-01-02 01:01
@jakirkham that's what I thought. But for some reason that's not working. Not sure if that's because of RTD first installing some sphinx dependencies with pip into the environment or whether the upgrade from Python 2 to 3 is not safe. Not sure. My wish list includes having the option to fully create the exact environment in one go from your own `environment.yml` without anything pre-installed by RTD.

**Comment by shoyer** [comment] 2016-01-04 01:17
We just hooked this up for xray, and it worked pretty much without a hitch!

On my first attempt, it still did the build with pip instead of conda. But after wiping the environment on that branch and resetting my advanced settings, the next time I did a build it used conda. I'm not quite sure what was going on there...

**Comment by faph** [comment] 2016-01-04 12:13
I had that a couple of times too. I did the same with wiping the RTD build. Does RTD cache the config or something?

**Comment by mrocklin** [comment] 2016-01-11 22:57
I'm having trouble with a project that needs to know where a conda installed .so file lives.  I have two conda packages, a compiled C++ library, `libhdfs3.so`, and a Python wrapper library, `hdfs3`.  The Python wrapper library tries to find the location of the `.so` file by finding the main conda directory and then adding `/lib`.  It finds the main conda directory by shelling out to `conda info` and then finding the text after default environment:

```
(py35)mrocklin@notebook:~$ conda info
...
  default environment : /home/mrocklin/Software/anaconda/envs/py35
...
```

```python
path = os.path.join(conda_dir, 'lib', 'libhdfs3.so')
```

Oddly when I do this in the RTD environment the resulting directory path to be `/usr/lib/libhdfs3.so` which makes me very confused.  Where is the conda directory here?  What is the result of calling `conda info` on a RTD machine?  Are we using the system Python or the conda Python during builds?

### Links

* [failing build](https://readthedocs.org/projects/hdfs3/builds/3628526/)
* [source on github](https://github.com/mrocklin/hdfs3)

**Comment by Juanlu001** [comment] 2016-01-12 07:17
Hi @mrocklin, I know very little about the RTD build process so I might be saying nonsense but I don't see the `activate` step in the failed build you linked. All the packages are getting installed in a conda environment called `latest` but, as far as I can see, it's never activated. This might be the cause of the failure, because in that case `conda info | grep 'default environment'` will return the root environment. Perhaps calling `/home/docs/checkouts/readthedocs.org/user_builds/hdfs3/conda/latest/bin/python` would be safer in this case? My two cents.

**Comment by Juanlu001** [comment] 2016-01-12 07:27
By the way, instead of reading `conda info` perhaps you could use the `sys.prefix` variable, which should point to the right locations when activating the environment. `ctypes.find_library` unfortunately won't work, see https://github.com/ioos/conda-recipes/issues/184#issuecomment-96245725 and https://github.com/ocefpaf/conda-recipes/blob/8f8c28e79a79a06ebfb98b4a3c099e92965cd595/rtree/find_libray.patch#L51

**Comment by Korijn** [comment] 2016-01-12 08:22
I think they're calling the conda environment's `python.exe` directly, which is indeed slightly incorrect since any other steps involved in the `activate` script are skipped (which can vary per environment).

**Comment by faph** [comment] 2016-01-12 08:26
For reference, the conda environment is named after the branch or document version and could be anything like `/home/docs/checkouts/readthedocs.org/user_builds/{reponame}/conda/{latest, develop, stable, ...}`

**Comment by jakirkham** [comment] 2016-01-12 14:08
Yeah, if an environment isn't activated, it is probably using the root `python`. Though, and I could be mistaken, there is no reason not to just installing everything into the root environment here.

**Comment by Korijn** [comment] 2016-01-12 15:34
I think `conda env create` is incapable of that, actually.

**Comment by jakirkham** [comment] 2016-01-12 15:37
I believe you are correct @Korijn. However, I think you could use `conda env update`, which shouldn't have an issue.

**Comment by faph** [comment] 2016-01-12 17:16
> Though, and I could be mistaken, there is no reason not to just installing everything into the root environment here.

One reason is for example Python 2 versus Python 3, i.e. you can have a standard/hard-coded root environment (managed by RTD) and let the user install exactly the documentation build packages in the environment you like. I believe the approach Continuum wants to take is to isolate conda itself as much as possible into an environment that ordinary users do not touch, i.e. consider it a standalone application. This way you can guarantee that conda works without interfering/being interfered by user packages.

**Comment by mrocklin** [comment] 2016-01-12 17:30
> I believe the approach Continuum wants to take is to isolate conda itself as much as possible into an environment that ordinary users do not touch, i.e. consider it a standalone application. 

That was the approach I was assuming was happening here.  It tends to be the assumed default among conda users.  The way that I would expect this to work is that the user supplies a conda environment for their build, this gets activated, and then RTD pushes the packages it needs on top of this environment.

**Comment by faph** [comment] 2016-01-12 17:40
I think that *is* roughly happening at RTD, but only the other way around. RTD *creates* a separate environment with sphinx pre-installed. Then it *updates* that environment with the user's supplied `environment.yml`.

Although there is no trace of conda's `activate` command in the build log, I assume the correct Python is on the PATH because docs builds do work (RTD calls `python /full/path/to/env/bin/sphinx-build`). Presumable conda's activate also puts the `bin` dir on the PATH; if that were to be used RTD could call `sphinx-build` directly?

**Comment by ericholscher** [comment] 2016-01-12 19:19
Seems like there's a lot of back and forth here, but no real consensus on what a proper solution is. Can anyone outline what the best course of action is for properly supporting these use cases? What we have now seems to work in the normal case, but there are edge cases where it isn't working, is my reading?

**Comment by jakirkham** [comment] 2016-01-12 19:26
Here is my real question. Is there a reason for installing into the root environment or is this just happening? If the former, what is the reason? If the latter, it is best to change the current behavior to create a clean new non-default environment as @mrocklin has said.

**Comment by shoyer** [comment] 2016-01-12 19:31
I'm pretty sure RTD is not installing into the root conda environment. However, it doesn't activate a new environment either. Instead, it simply uses the binaries in the new build specific environment that it created directly. In my mind, this is a pretty reasonable solution -- activating an environment really only makes sense in an interactive session or shell script.

**Comment by mrocklin** [comment] 2016-01-12 19:33
Hrm, I think of conda environments as being particularly useful in these cases, where you want a reliable software environment for build purposes.  Most build services within Continuum happen within a conda environment for predictability's sake.

**Comment by jakirkham** [comment] 2016-01-12 19:36
@ericholscher, is there code somewhere we can look at for this? I think it would answer a lot of questions.

**Comment by shoyer** [comment] 2016-01-12 19:38
As I said, it*is* being done in a fresh conda environment, the environment just isn't being activated -- the binaries in the environment are being called directly.

**Comment by mrocklin** [comment] 2016-01-12 19:43
Are there particular issues you foresee occuring if you activate the environment?

In this case the issue is that my library actively depends on the conda state in order to locate a shared object file.  Arguably this is a less-than-ideal way to find a shared library, but it's not the ugliest thing that people are going to try with rtd+conda.

**Comment by mrocklin** [comment] 2016-01-12 19:46
FWIW, I've also worked around this within my own library (I now allow the library to import if it can't find the .so file) so my immediate use case is gone.  Still though, I think that future corner cases will occur among conda users if the environment actually gets activated.  I think that this is common case (though I have less experience here than many.)

**Comment by mrocklin** [comment] 2016-01-12 19:47
Edit: *fewer* future corner cases will occur among conda users if the environment actually gets activated.

**Comment by jakirkham** [comment] 2016-01-12 19:48
Is this being run in a docker image? I can certainly propose strategies that would work around this. If there is code I can PR against, I can even provide a solution, but it is hard to do in the dark.

**Comment by shoyer** [comment] 2016-01-12 19:50
@jakirkham here is the PR that added conda support to RTD: https://github.com/rtfd/readthedocs.org/pull/1849

**Comment by jakirkham** [comment] 2016-01-12 19:51
Cool, thanks @shoyer.

**Comment by Carreau** [comment] 2016-01-12 20:04
> As I said, it *is* being done in a fresh conda environment, the environment just isn't being activated -- the binaries in the environment are being called directly.

We have the same issue in Jupyter, if you don't activate the environment, code that rely on command line utilities being on path will not work properly leading to weird behavior. So calling directly /full/path/to/python is problematic. And "shelling out need to use `sys.executable`" is not a satisfying answer as code might require non-python deps that conda can install like pandoc.

**Comment by jakirkham** [comment] 2016-01-12 20:12
So, I think running the activate script is probably too much to hope for (maybe I'm wrong). However, I have found this normally covers it. If I run `conda info` or pretty much any other `conda` command this seems works the same as activate. It can easily be added to whatever language we want. These are all environment variables.

* Set `$CONDA_DEFAULT_ENV` to the name environment we want.
* Set `$CONDA_ENV_PATH` to the path of the environment, which should be `<conda_installation>/envs/$CONDA_DEFAULT_ENV`
* Ensure `$CONDA_ENV_PATH/bin` is first in `$PATH`

**Comment by faph** [comment] 2016-01-12 20:34
@ericholscher I think all that is asked for is that the environment created gets added to the path, including the standard sub-dirs like `bin`, `lib` etc. In conda-land there is an `activate` script for that. To satisfy the crowds you may want to document the exact install steps including env variables. Just because now you've enabled conda, people are going to install the most exotic packages including non-Python stuff!

**Comment by jakirkham** [comment] 2016-01-12 20:41
Honestly, I have never needed to add `lib` or anything else other than `bin`.

`CONDA_DEFAULT_ENV` and `CONDA_ENV_PATH` seem to be important. The first seems unsurprising. I am not sure why the second is used (maybe if you have multiple conda installs). The rest of activate seems more about nice things for a user to have like `$PS1` and such that really don't seem important here, but I could be wrong.

**Comment by Juanlu001** [comment] 2016-01-12 20:48
I forked the project to experiment, and have several thoughts:

* I suggest adding the `-q` option to conda commands to remove progress bars (originally suggested to me at https://github.com/Juanlu001/fenics-recipes/issues/20#issuecomment-169640776
* Correct me if I'm wrong, but the actual code in the repository is not being installed. I made a modification but noticed that the code in RTD was unchanged - then realized that it's picking the package @mrocklin published to the blaze channel and after removal the build no longer works. It's therefore more difficult to me to iterate.

This is the code I was about to try by the way:

https://github.com/Juanlu001/hdfs3/commit/b004f0d53c76ee0aaf0521e9fcf0b9eb5bd71cd1

Answering @mrocklin question about `activate`, I've been exclusively using conda for more than a year and I don't foressee any particular issues arising. I think the best option is probably to just use it.

**Comment by ericholscher** [comment] 2016-01-12 20:51
We aren't running conda in an interactive session, so I'm not sure how we could "call" activate. If there are environment variables that should be supported, we could set them, but we're running these commands independently, so the variables set in the activate script wouldn't apply.

The code is here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/python_environments.py#L163

**Comment by jakirkham** [comment] 2016-01-12 20:56
> We aren't running conda in an interactive session, so I'm not sure how we could "call" activate.

Yeah, I wouldn't be surprised if this is a problem. The `activate` script is a long-ish bash script that needs to be sourced. Doesn't seem like that would mesh well with what you are doing. Fortunately, it doesn't seem to matter.

> If there are environment variables that should be supported, we could set them, but we're running these commands independently, so the variables set in the activate script wouldn't apply.

Right, so if we can just tack them onto whatever environment that is used when shelling out I think this would be fine.

> The code is here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/python_environments.py#L163

Thanks for the link. I have been looking at the code. I had a question that I put on the merged PR.

**Comment by pitrou** [comment] 2016-01-12 21:03
For the record, here is a diff of environment variables when I run `activate` here:
```
+PYTHONNOUSERSITE=1
-PATH=/home/antoine/.local/bin:/usr/local/cuda/bin:/home/antoine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+PATH=/home/antoine/35/bin:/home/antoine/.local/bin:/usr/local/cuda/bin:/home/antoine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+CONDA_ENV_PATH=/home/antoine/35
+CONDA_DEFAULT_ENV=/home/antoine/35
```

As you see there's not much to it. The most important is probably the appending of the conda environment's `bin` directory to the PATH.

**Comment by jakirkham** [comment] 2016-01-12 21:04
Interesting, I don't get this `PYTHONNOUSERSITE`. Which version of `conda` are you on?

**Comment by pitrou** [comment] 2016-01-12 21:10
```
$ conda --version
conda 3.19.0
```

PYTHONNOUSERSITE wouldn't be be very useful for RTD, though.

**Comment by pitrou** [comment] 2016-01-12 21:10
Oh, forget it. PYTHONNOUSERSITE is from my own `activate` wrapper :-)

**Comment by jakirkham** [comment] 2016-01-12 21:13
Ah, ok. In any event, I think we can safely ignore it here as there should be only this one Python install that we are worried about.

**Comment by ericholscher** [comment] 2016-01-12 21:47
Should be easy enough to support the conda PATH, as we already have the `bin_path` argument to our run call.

**Comment by jakirkham** [comment] 2016-01-12 21:51
I could be wrong, but I think we want to be able to pass environment variables as a kwarg to something like this ( https://github.com/rtfd/readthedocs.org/blob/aba714e82d218d60773955aec62a3df74173348d/readthedocs/doc_builder/backends/sphinx.py#L156 ).

**Comment by jakirkham** [comment] 2016-01-12 21:59
So, we have to change the environment of the build command then, yes?

**Comment by jakirkham** [comment] 2016-01-12 23:01
So, I tried my hand at a simpler PR ( https://github.com/rtfd/readthedocs.org/pull/1919 ). From what I have gleaned from my brief look at the code here (not an expert), this looks like a workable solution.

It probably could use a test or two, but I am a bit unfamiliar with the test suite here and will need guidance for that. Though, I imagine doing something like asserting the variables are there and checking the output of `conda info` would be a good start.

**Comment by jakirkham** [comment] 2016-01-14 20:32
Turns out this PR ( https://github.com/rtfd/readthedocs.org/pull/1924 ) ends up being a much better way to go about it.

**Comment by jakirkham** [comment] 2016-01-15 15:56
So, I think the active environment issue is fixed thanks to @ericholscher and @agjohnson, if people want to try.

**Comment by mrocklin** [comment] 2016-01-15 22:41
Verified that this works well for me.  Thank all!

**Comment by ericholscher** [comment] 2016-01-16 01:43
Great :)

If there are other issues, please create new tickets for them, as this one is quite old and the main issues seem to be resolved.

Woo!

**Comment by Juanlu001** [comment] 2016-01-16 14:50
I just built the docs for poliastro in rtd and it works like a charm :smile: Thanks to @mrocklin and Clinical Graphics for this!

**Comment by Juanlu001** [comment] 2016-01-22 14:21
Just a quick notice: right now RTD uses docutils 0.11, which is not yet available for Python 3.5 for linux.

http://readthedocs.org/projects/poliastro/builds/3655474/
```
Hint: the following packages conflict with each other:
  - docutils ==0.11
  - python 3.5*
```

Packages: https://anaconda.org/anaconda/docutils/files?version=0.11

**Comment by Juanlu001** [comment] 2016-01-22 14:22
(Sorry, my above comment was already reported as #1901)

**Comment by jakirkham** [comment] 2016-01-22 14:38
@Juanlu001, see ( https://github.com/rtfd/readthedocs.org/pull/1933 ).

**Comment by ericholscher** [comment] 2016-01-22 19:59
#1947 is the fix for that issue. I will get it merged & deployed today.

**Comment by tritemio** [comment] 2016-03-13 23:55
I tried the using conda environment with [fretbursts](https://github.com/tritemio/FRETBursts) to see if I can get rid of the mocking layer.

However, building the docs fails on RTD:

http://readthedocs.org/projects/fretbursts/builds/3813468/

unless I reintroduce the mocking for scipy:

http://readthedocs.org/projects/fretbursts/builds/3813474/

**Comment by agjohnson** [comment] 2016-03-15 18:19
@tritemio it would be best if you opened your issue as a bug, we won't be able to track it here. This was a feature addition that has been in production for a few months now.

Closing this issue. Please address bugs with additional tickets.

**Closed by agjohnson** 2016-03-15 18:19 UTC
Labels: Enhancement, Feature Overview

**Comment by tritemio** [comment] 2016-03-15 20:38
@agjohnson, it makes sense. I opened a new issue https://github.com/rtfd/readthedocs.org/issues/2074
