### ISSUE TITLE
"Edit on GitHub" for "stable" points to commit-id

### ISSUE THREAD

**Issue by htgoebel** [rtfd/readthedocs.org#3926] opened 2018-04-08 21:07 UTC
## Details

* Project URL: https://readthedocs.org/projects/pyinstaller/
* Build URL:http://pyinstaller.readthedocs.io/en/stable/
* Read the Docs username: htgoebel

## Expected Result

The link behind "Edit on Github" should point to the blob under the most current tag (here: v3.3.1):
https://github.com/pyinstaller/pyinstaller/blob/v3.3.1/doc/index.rst

## Actual Result

1. The link points to a blob under a commit-id:
https://github.com/pyinstaller/pyinstaller/blob/6ed6dd2f52f3d4409292a484e8f19a8ce1daef43/doc/index.rst
2.  Github is not able to show this blob (Error 404)

## Additional information

1. This commit-id is the one of the tag:
  ```
$ git rev-parse v3.3.1
6ed6dd2f52f3d4409292a484e8f19a8ce1daef43
```
2. latest stable version tag is v.3.3.1 with commit-id 5b84a8da71048fc888bc4240d653034394a76d32
3. tried wiping and rebuilding without success https://readthedocs.org/projects/pyinstaller/builds/7009974/

**Comment by stsewd** [comment] 2018-04-09 04:44
Thanks for reporting, this issue is a duplicate of #1820 

Also, RTD is moving to use `gitpython` instead of parsing the tags/branches manually, so I suppose that would fix the issue.

**Closed by stsewd** 2018-04-09 04:44 UTC
