### ISSUE TITLE
Outdated pip is causing builds with namespace packages to fail

### ISSUE THREAD

**Issue by theacodes** [rtfd/readthedocs.org#4127] opened 2018-05-22 18:21 UTC
* Read the Docs project URL: https://google-cloud-python.readthedocs.io
* Build URL (if applicable):

Recent failures:
- https://readthedocs.org/projects/google-cloud-python/builds/7229979/
- https://readthedocs.org/projects/google-cloud-python/builds/7225937/
- https://readthedocs.org/projects/google-cloud-python/builds/7225738/

Last successful build:
https://readthedocs.org/projects/google-cloud-python/builds/7225188/

It seems that this is due to https://github.com/pypa/setuptools/issues/885, which indicates that pip *and* setuptools need to be updated in the baseline environment.

**Comment by stsewd** [comment] 2018-05-22 18:52
The pip message is just a warning, so it shouldn't be the cause of the failure. I'm not sure why is this happening, I'll try to see if I can reproduce this on my local instance. Let us know if the build keeps failing.

**Comment by theacodes** [comment] 2018-05-22 20:06
The most recent few have failed. Here's one: https://readthedocs.org/projects/google-cloud-python/builds/7230941/

**Comment by theacodes** [comment] 2018-05-23 22:31
Seems like our recently builds today have consistently failed due to this: https://readthedocs.org/projects/google-cloud-python/builds/

Is there anything we can do to help? I'm happy to make the change to update pip/setuptools, I just don't know where to do it.

**Comment by stsewd** [comment] 2018-05-23 22:43
Maybe you can try wiping the environment, you can do this in the `Versions` section then `Edit` button.

What I can see is that the `pip` version comes from the docker image https://github.com/rtfd/readthedocs-docker-images/blob/9b0816d1b610373036ce16eb3653c99ca30e4207/Dockerfile#L92

So, the team needs to rebuild the image to get the latest versions, I think we should support upgrade pip before installing deps. I'm going to ask to the team.

**Comment by theacodes** [comment] 2018-05-23 22:50
Thanks, @stsewd! Clearing the environment seems to have helped.

Since we're using 'latest', it seems you'd need to rebuild the 3.x docker image from [here](https://github.com/rtfd/readthedocs-docker-images/blob/releases/3.x/Dockerfile).

**Comment by tswast** [comment] 2018-06-15 16:49
Adding `pip_install: true` to the config in `pandas-gbq` seemed to be the right fix for a similar error. https://github.com/pydata/pandas-gbq/commit/ee9955f81b454ff43b3c9c20e15d776444503ac8

**Comment by stsewd** [comment] 2018-10-31 17:11
Probably we can close this in favor of https://github.com/rtfd/readthedocs.org/issues/4823

**Comment by stsewd** [comment] 2018-11-28 00:54
Closing in favor of https://github.com/rtfd/readthedocs.org/issues/4823, but let me know if there are any other problems!

**Closed by stsewd** 2018-11-28 00:54 UTC
Labels: Support
