### ISSUE TITLE
ReadTheDocs + MkDocs Search Broken

### ISSUE THREAD

**Issue by sahilTakiar** [rtfd/readthedocs.org#2025] opened 2016-02-28 20:11 UTC
## Details

If this issue is for a specific project or build, include the following:
- Project: http://readthedocs.org/projects/gobblin/
- Build #: latest
- Version: readthedocs
- Documentation: http://gobblin.readthedocs.org/en/readthedocs/

When performing a trivial search on: http://gobblin.readthedocs.org/en/readthedocs/ or even https://mkdocs.readthedocs.org/en/stable/

I get re-directed to here: https://readthedocs.org//search/?q=mkdocs&check_keywords=yes&area=default&project=mkdocs&version=stable&type=file

It lists out a few search results but most are broken: http://mikasa-demo.readthedocs.org/en/stable/user-guide/styling-your-docs/?highlight=mkdocs

Based on https://github.com/mkdocs/mkdocs/pull/222 it should look something more like [this](https://camo.githubusercontent.com/c6cb60082d1407d22171c928f9380cd9e26acac2/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f31343235353231372f53637265656e73686f74732f53637265656e73686f74253230323031342d31312d32312d31382e34392e35302e4e6176696761746f722e706e67).

Any idea what is going on?

Related Issues: https://github.com/mkdocs/mkdocs/issues/848

Could this problem be related to: https://github.com/rtfd/readthedocs.org/issues/1487 or https://github.com/rtfd/readthedocs.org/issues/1633

**Comment by marcelstoer** [comment] 2016-02-29 19:37
@agjohnson I suggest you keep either this or #1487 open and resolve the other as a dup. You might as well keep only #1088 and close the others. #1633 is only partially related.

**Comment by agjohnson** [comment] 2017-03-04 04:53
Closing as a duplicate of #1487

**Closed by agjohnson** 2017-03-04 04:53 UTC
Labels: Mkdocs
