### ISSUE TITLE
Manage one checkout for all projects

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#1375] opened 2015-06-24 21:42 UTC
There would be a sizable win if we changed from having a checkout for every version of a project to having one central checkout, that gets cloned and then deleted into each version on build. This would save lots of bandwidth and disk space, because we could keep a much larger cache of clones.

The main space issue is actually around the virtualenvs, but this would be a good start to addressing this.

**Comment by humitos** [comment] 2019-01-22 10:37
We already implemented #4939 that forces git to download only the latest 50 commits. It's not exactly the same as what this issue proposes but it's related.

Considering that we are removing all the checkouts at the end of the day if not recently updated, I suppose that by having only one checkout for all the versions we are not going to gain too much space here.

**Comment by stsewd** [comment] 2019-03-01 01:27
This would be useful if we save the one checkout in one server/location, right now we have several builders and it wouldn't make much difference if we save one checkout per builder.

**Comment by humitos** [comment] 2019-03-04 10:14
We are talking about having volatile servers in the middle term because different reasons (disk costs, reproducibility, etc), so I think this issue is not valid anymore. I'm closing it here.

**Closed by humitos** 2019-03-04 10:14 UTC
Labels: Accepted, Improvement
