### ISSUE TITLE
The search feature does not work properly on MkDocs builder.

### ISSUE THREAD

**Issue by qqbuby** [rtfd/readthedocs.org#2679] opened 2017-03-02 09:01 UTC
## Details

* Project URL: http://xmkdocs.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/xmkdocs/builds/5093791/
* Read the Docs username (if applicable): qqbuby@gmail.com

## Expected Result

I just put some keyword (e.g. 'mkdocs' ) in the search box on the top-left side, but the search results that presents to me were not what I expected.

e.g.

![image](https://cloud.githubusercontent.com/assets/7823985/23500059/8fb1ca8e-ff69-11e6-8557-b33246699363.png)

## Actual Result

Like the `Sphinx` doc builder.

URL: http://socorro.readthedocs.io/en/latest/search.html?q=section&check_keywords=yes&area=default

![image](https://cloud.githubusercontent.com/assets/7823985/23500134/dffa4ff2-ff69-11e6-834b-5307d22cd908.png)

**Comment by agjohnson** [comment] 2017-03-04 04:54
Closing this as a duplicate of #1487

**Closed by agjohnson** 2017-03-04 04:54 UTC
