### ISSUE TITLE
Overriding layout.html 

### ISSUE THREAD

**Issue by miohtama** [rtfd/readthedocs.org#1722] opened 2015-10-01 22:41 UTC
I am using RTD.org theme with Sphinx. I manage to override  `layout.html` locally using the Sphinx default `_templates` override path.

              html_theme = "sphinx_rtd_theme"

              html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

              # Add any paths that contain templates here, relative to this directory.
              templates_path = ['_templates']

However when deployed on RTD.org changes do not appear there.

What (special) actions I need to take on `conf.py` et. al. so that my custom `layout.html` is picked up on RTD.org deployment instead of the default RTD.org one?

**Comment by agjohnson** [comment] 2015-10-05 17:43
We recently started outputting the `conf.py` that we use, after appending our changes to the file. You can see the output in the build output page, under `cat conf.py`. This might offer some more clues. This may be a result of us clobbering the `html_theme_path`, where we should be appending.

**Comment by miohtama** [comment] 2015-10-05 17:52
Thanks! Will check this out.

**Comment by miohtama** [comment] 2015-10-09 13:28
The build page layout is broken. I think I cannot read `cat build.py` - should I open a new issue for this? FF / OSX..

<img width="977" alt="screen shot 2015-10-09 at 16 27 48" src="https://cloud.githubusercontent.com/assets/49922/10394898/c04c6810-6ea2-11e5-8927-242d5dc29ec5.png">

**Comment by miohtama** [comment] 2015-10-09 13:31
Ok could read it with Chrome.

I think it unconditionally inserts RTD internal templates at the front of my templates:

    #Add RTD Template Path.
    if 'templates_path' in globals():
        templates_path.insert(0, '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx')
    else:
        templates_path = ['/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx', 'templates', '_templates',
                          '.templates']

Any way to fix this? Can I include conf.py code after RTD.org mangles conf.py?

**Comment by ericholscher** [comment] 2016-01-30 00:45
This is a dupe of #152

**Closed by ericholscher** 2016-01-30 00:45 UTC
Labels: Triage: Support
