### ISSUE TITLE
Deleting ownerless project

### ISSUE THREAD

**Issue by KathleenLabrie** [rtfd/readthedocs.org#1470] opened 2015-07-22 03:03 UTC
Since there are no other 'contact us'-like avenue, I will post my question here.

A while ago I created a project pointing to a URL on my machine behind a firewall.  The project is now ownerless, yet I know it's mine.  I would like to delete but since I'm not assigned as an owner, I can't delete it.   The dead project is 'gemini_python', at https://readthedocs.org/projects/gemini-python/

I just want to clean up the mess.

**Comment by ericholscher** [comment] 2015-08-26 07:25
This is a dupe of #1408 -- I've gone ahead and deleted the specific project now.

**Closed by ericholscher** 2015-08-26 07:25 UTC
Labels: Support
