### ISSUE TITLE
Citations compilation according to bibtex file

### ISSUE THREAD

**Issue by mattberjon** [rtfd/readthedocs.org#2601] opened 2017-01-21 09:33 UTC
## Details

Hi,

I'm using Sphinx to compile a thesis and host it on ReadTheDocs. The build works and finishes correctly but the bibliography and all the references/citations are not properly compiled in the document. When I compile it locally, I don't have errors and can see the bibliography.

My project relies on:

- [sphinxcontrib-bibtex][l1]
- [pybtex][l2]

* Project URL: [auditory-motion-perception on Github][l3]
* Build URL (if applicable): [#4923632][l4]
* Read the Docs username (if applicable): mattberjon

## Expected Result

Locally, I don't have particular issue but sometimes I need to edit the conf.py to force the compilation to generate the bilbiography and links.

## Actual Result

I would like to see the bibliography and the related links pointing to the bilbiography in the ReadTheDocs build.

[l1]: http://sphinxcontrib-bibtex.readthedocs.io/
[l2]: http://pybtex.org/
[l3]: https://github.com/mattberjon/auditory-motion-perception
[l4]: https://readthedocs.org/projects/auditory-motion-perception/builds/4923632

**Comment by humitos** [comment] 2017-02-23 01:57
@mattberjon I just tried downloading your project from github and compiling the documentations and I got a bunch of this errors:

```
/tmp/auditory-motion-perception/lab.rst:146: SEVERE: Title level inconsistent:

The room
++++++++
```

and 

```
/tmp/auditory-motion-perception/lab.rst:58: WARNING: citation not found: Guillon2009
```

Besides, once it finished, the documentation was built but there is no bibliography at all under `bibliography.html`

**Comment by mattberjon** [comment] 2017-02-23 09:02
@humitos thanks a lot for pointing out these errors, I just corrected them. Nevertheless, it doesn't change my issue on hands. If the bibliography doesn't come out on your side, the problem could come from the the bibtex plugin I'm using and not from rtd.

**Comment by humitos** [comment] 2017-02-23 13:15
@mattberjon have you ever seen the bibliography when building in your own computer? If no, I will close the issue since it doesn't seem to be related with RTD but with `bibtex` or some configuration in your end.

**Comment by mattberjon** [comment] 2017-02-23 13:24
@humitos as explained, I can see the bibliography locally, but sometimes it doesn't work on the first compilation and end-up with the same issue as you had such as `citation not found`. When this happen, it seems that by forcing the compilation (by changing the conf.py for example) the compilation is successful and I can see the bibliography.

I have difficulties to know if the issue is on rtd side or on the plugin. If you think the probability is toward the plugin, I would be gladly close this issue and open one on the plugin's repo.

**Comment by humitos** [comment] 2017-02-23 13:40
I see. I updated your repo and re-run the `make html` and I don't see the bibliography, but as you said, changing the `conf.py` a little and re-running `make html` made the bibliography appears there.

It seems that the plugin needs to be ran twice for some reason (maybe it creates a file with the link and in the second it uses it, or something like that since at first it fails because doesn't find the citations)

I would say that this is not related to RTD since we can reproduce the same error our own local computers. I would ask for help at the plugin people and link this issue for reference.

Thanks!

**Closed by humitos** 2017-02-23 13:40 UTC
Labels: Support

**Comment by mattberjon** [comment] 2017-02-23 16:39
Thanks for your help guys, I'm going to follow your suggestions.
