### ISSUE TITLE
Server Error 500: https://readthedocs.org//api/v2/command/ in multiple builds

### ISSUE THREAD

**Issue by cjw296** [rtfd/readthedocs.org#2002] opened 2016-02-17 22:01 UTC
This looks like it started today with no changes on my part:

https://readthedocs.org/projects/python-workfront/builds/3738463/

What's going on here?

**Comment by agjohnson** [comment] 2016-02-17 23:45
I've noticed a spike in these errors as well lately, it seems the issue is intermittent. I haven't tracked down the exact error behind the 500 yet.

**Comment by cjw296** [comment] 2016-02-18 06:59
Surely there must be a log for whatever served that 500 that someone could check?

**Comment by evhub** [comment] 2016-02-21 19:07
Getting the same "Fail.  Check back in a bit!" error right now when I go to <https://readthedocs.org/dashboard/>. Console reads "Failed to load resource: the server responded with a status of 500 (OK)".

**Comment by oTree-org** [comment] 2016-03-06 02:56
I'm getting this also: http://readthedocs.org/projects/otree/builds/3789435/

**Comment by ael-code** [comment] 2016-03-06 12:35
Same here http://readthedocs.org/projects/libreant/builds/3790889/

**Comment by boris-il-forte** [comment] 2016-03-06 16:08
same here http://readthedocs.org/projects/rele/builds/3791331/

**Comment by isaacovercast** [comment] 2016-03-06 18:27
Same: https://readthedocs.org/projects/ipyrad/builds/3791505/

**Comment by drvinceknight** [comment] 2016-03-06 20:27
Same here: https://readthedocs.org/projects/axelrod/builds/3791751/

**Comment by adrianschlatter** [comment] 2016-03-06 20:55
and here: https://readthedocs.org/projects/tanuna/builds/3791852/

**Comment by hjacobs** [comment] 2016-03-06 22:30
Same here: https://readthedocs.org/projects/planb/builds/3792022/
Re-triggered the build multiple times --- it always fails, can't see any error in the console.

How can we help?

**Comment by er1iang** [comment] 2016-03-07 00:22
Same here:  http://readthedocs.org/projects/hfut-stu-lib/builds/3791724/

**Comment by WJCode** [comment] 2016-03-07 13:45
We had this issue with our docs too but I was able to manually trigger a successful build a short while back. There were 6 builds that had failed just before the successful build.

**Comment by boris-il-forte** [comment] 2016-03-12 18:30
and the issue is back again:
https://readthedocs.org/projects/rele/builds/3811276/

**Comment by dominiktraxl** [comment] 2016-03-12 18:52
Same here: https://readthedocs.org/projects/deepgraph/builds/3811300/

**Comment by Silmathoron** [comment] 2016-03-12 20:02
I'm also experiencing the [same bug](http://readthedocs.org/projects/nngt/builds/3811370/)

**Comment by ttmc** [comment] 2016-03-12 21:04
We're getting the same error for the latest builds of http://bigchaindb.readthedocs.org/en/develop/

**Comment by spencerpbartz** [comment] 2016-03-12 21:27
Experiencing the same bug. Need a fix immediately as this is customer-facing.

**Comment by prjemian** [comment] 2016-03-12 22:00
One successful build in last hour, then two that failed

**Comment by kmarsteller** [comment] 2016-03-13 00:43
No good builds in past 12 hours.  [OpenMDAO](https://readthedocs.org/projects/openmdao/builds/
)

**Comment by bobsummerwill** [comment] 2016-03-13 02:01
Ditto.   See http://readthedocs.org/projects/ethereum-homestead/builds/.

Happy to do whatever I can to help with troubleshooting this issue, because we have a major milestone on Monday and need our documentation up :-)

**Comment by ttmc** [comment] 2016-03-13 07:20
Our latest build passed. Did something change or is this an intermittent problem?

**Comment by bobsummerwill** [comment] 2016-03-13 07:38
I just had a success too, @ttmc, which makes me happy.

It also makes me wonder the same as you.    Fluke?   Or fix?

**Comment by WJCode** [comment] 2016-03-13 08:16
We also had failed build but our latest build passed. It seems like an intermittent problem. 

Anything we can do to help?

**Comment by agjohnson** [comment] 2016-03-14 17:55
This issue still only appears intermittently, and not necessarily dependent on load, though I do notice a spike during time when we see higher resource contention. Testing some more changes to our infrastructure today, hoping this resolves the issue.

**Comment by Korijn** [comment] 2016-04-04 16:39
Same here, all day today.

**Comment by lfurtkevicova** [comment] 2016-05-03 14:09
Same today https://readthedocs.org/projects/gislab-documentation/builds/3966576/

**Comment by ericholscher** [comment] 2017-03-09 22:37
I believe this issue was fixed by splitting out API and web servers out into different pools. It hasn't been reported in almost a year, so I'm going to close this.

**Closed by ericholscher** 2017-03-09 22:37 UTC
Labels: Bug, Operations
