### ISSUE TITLE
rst-versions footer cannot be expanded when using sphinx_rtd_theme

### ISSUE THREAD

**Issue by Coconutcoo** [rtfd/readthedocs.org#4132] opened 2018-05-23 00:20 UTC
## Details

* Read the Docs project URL: http://gather-documentation.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/gather-documentation/builds/7231904/
* Read the Docs username (if applicable): coconutcoo

## Expected Result

When clicking the injected rst-versions footer ![image](https://user-images.githubusercontent.com/15087570/40396618-e89ff334-5e25-11e8-8175-acbe66c54eea.png) while using sphinx_rtd_theme, the footer should expand and show content.

## Actual Result

Page load causes the DOM to crash with the following error:
```
Uncaught TypeError: Cannot read property 'enable' of undefined
    at HTMLDocument.<anonymous> ((index):288)
    at f (jquery-2.0.3.min.js:3)
    at Object.fireWith [as resolveWith] (jquery-2.0.3.min.js:3)
    at Function.ready (jquery-2.0.3.min.js:1)
    at HTMLDocument.ge (jquery-2.0.3.min.js:1)
```

Line 288 is a script added during the RTD build, that seems to be for the Sphinx RTD theme:

```
<script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
</script>
```

SphinxRtdTheme.Navigation is supposedly undefined, and SphinxRtdTheme contains only one element; StickyNav.
Removing the script, or replacing "Navigation" with "StickyNav" fixes this issue and allows the footer to be expanded as expected.

I wasn't really sure whether this was an issue to open here or on the sphinx theme's Github, but since building locally with this theme, the footer isn't injected, I think this is the correct place.

**Comment by stsewd** [comment] 2018-05-23 02:08
At first, I wasn't able to replicate this on your project, then I clear the cache and was able to replicate this. So, I think this is due to a recent update.

**Comment by Coconutcoo** [comment] 2018-05-23 02:17
Should've clarified in the post what I've tried;

Clean install of Sphinx (sphinx-quickstart) and Alabaster theme, build on RTD, worked correctly. 
Clean Sphinx install, RTD theme, build on RTD, did not work correctly.

Both of these had the same set of my .rst files and images, and with no other changes to the conf.py file than the theme this issue arises.

**Comment by dillonsvincent** [comment] 2018-05-23 08:13
I am also experiencing this issue, i'm not able to reproduce locally.

**Comment by davidfischer** [comment] 2018-05-23 12:45
@dillonsvincent, do you have a project url? It would really help to investigate.

**Comment by tylerbutler** [comment] 2018-05-23 14:29
@davidfischer I am seeing this on my project as well. URL is https://wopi.readthedocs.io/

**Comment by tylerbutler** [comment] 2018-05-23 14:31
Could this be related to #3925?

**Comment by tylerbutler** [comment] 2018-05-23 14:32
This bug also seems to break the 'hamburger' menu on mobile devices (or devices with a small viewport). Tapping it does nothing.

**Comment by LewisSmallwood** [comment] 2018-05-23 15:59
I believe it crashes jquery / disables the DOM as soon as the error occurs so any onclick events, etc don't get called

**Comment by davidfischer** [comment] 2018-05-23 16:08
> Could this be related to #3925?

It definitely is.

There is a problem where Read the Docs was getting too clever trying to speed up docs by centralizing the theme JavaScript. However, it ran into problems with a version mismatch. There was supposed to be short term fix for this but it doesn't appear to be working correctly.

**Comment by davidfischer** [comment] 2018-05-23 16:31
This looks like there was a problem building the static assets correctly in the last deploy. I should have this fixed relatively shortly.

**Comment by dillonsvincent** [comment] 2018-05-23 17:16
@davidfischer https://atra.readthedocs.io/ https://github.com/dillonsvincent/docs
Are all effected sites going to need to rebuild after the fix?

**Comment by davidfischer** [comment] 2018-05-23 17:43
I believe this issue is resolved. I'm running a few tests but I believe this should be fixed. You may need to reload without cache (I'm working on that too).

**Comment by davidfischer** [comment] 2018-05-23 17:51
Yes, the static assets didn't get built correctly and old static assets were used.

I'm glad we got this sorted out.

**Closed by davidfischer** 2018-05-23 17:51 UTC
Labels: Bug

**Comment by gasman** [comment] 2018-05-31 14:51
I'm now seeing this error on http://docs.wagtail.io/en/v2.1/ - not sure when it started.

**Comment by stsewd** [comment] 2018-05-31 15:03
@gasman yeah, this was from yesterday, the team is working on that right now
