### ISSUE TITLE
Build fails for new project

### ISSUE THREAD

**Issue by Randrian45** [rtfd/readthedocs.org#3732] opened 2018-03-05 13:33 UTC
## Details

* Project URL: http://open-gpias.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/open-gpias/builds/6841210/
* Read the Docs username (if applicable): randrian

## Expected Result

*A description of what you wanted to happen*

ReadTheDocs should clone the repository and build the documentation.

## Actual Result

*A description of what actually happened*

ReadTheDocs clones the repository without problems, but then crashes without giving a proper error message. I just receive:

There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6841210).

All the output of the commands ReadTheDocs executed was without errors:

hg clone https://bitbucket.org/randrian/open_gpias .
hg update --clean default
hg tags
hg branches

**Comment by stsewd** [comment] 2018-03-06 02:37
I can't see your builds, I think it's because your project privacy level. I'll try to reproduce it on my local installation.

**Comment by stsewd** [comment] 2018-03-06 03:28
Sorry that you are having this problem on your new project, seems like a unicode error. This is because of this [file](https://bitbucket.org/randrian/opengpias/src/d7390c85f4e66f57c57707bf7c1fef120d825f88/open_gpias/GUI%20Playlist/schaue%20p%C3%BClaylist%20an.py?at=default&fileviewer=file-view-default). Any possibility that you can rename the file? Otherwise you need to wait for https://github.com/rtfd/readthedocs-build/issues/27 gets fixed.

**Comment by stsewd** [comment] 2018-03-06 04:28
I found a fix https://github.com/rtfd/readthedocs-build/issues/27#issuecomment-370658598, lets wait to get a reply on the other issue :)

**Comment by Randrian45** [comment] 2018-03-06 07:47
Thank you. I have removed the Unicode character in the filename and now it works :-). But nevertheless, it would be good to fix the bug, or at least provide a meaningful error message.

**Comment by RichardLitt** [comment] 2018-03-06 17:09
That would be a great idea for a PR! Would you be able to file that, @Randrian45?

**Comment by stsewd** [comment] 2018-03-06 22:02
@Randrian45 while trying to fix the issue https://github.com/rtfd/readthedocs-build/pull/45#issuecomment-370939759 I came up with some questions, hope you can help me with that. What OS did you use when creating the file? What is the default encoding of that OS?

Also, could you create a file outside mercurial with some especial characters and run this script? `python2 test.py` and tell me if that fails. Just to test if this isn't related to a corrupted mercurial file.

```python
# test.py
import os


def find_all(path, filenames):
    path = os.path.abspath(path)
    for root, dirs, files in os.walk(path, topdown=True):
        dirs.sort()
        for filename in filenames:
            if filename in files:
                yield os.path.abspath(os.path.join(root, filename))


def find_one(path, filenames):
    for _path in find_all(path, filenames):
        return _path
    return ''

find_one(
    u'/path/to/a/dir/with/a/file/created/by/you/outside/mercurial/with/special/chars/',
    ('readthedocs.yml', '.readthedocs.yml')
)
```

**Comment by Randrian45** [comment] 2018-03-07 11:31
I did not create the file myself but received it from a colleague over the mercurial repository. I asked him what OS he did use, and he said that it probably was Windows 7, I think with German settings, or at least a german keyboard layout.
When I try to run your script on my computer, I do not get any fails when the directory contains files with special characters.

**Comment by stsewd** [comment] 2018-03-07 14:42
@Randrian45 do you also use Windows?

**Comment by Randrian45** [comment] 2018-03-07 15:21
Yes, I also use Windows, but Windows10, with German settings.

**Comment by humitos** [comment] 2018-03-07 16:05
I'd say that the file is corrupted: it's supposed that its name is in one encoding but it's in another. So, we try to read it's from the filesystem and it fails on decoding it.

We should probably have a try/except block for this and skip the corrupted files.

**Comment by stsewd** [comment] 2018-06-15 18:38
Closing as we can't replicate. Probably it was a corrupted file as mention in https://github.com/rtfd/readthedocs.org/issues/3732#issuecomment-371187950. And we have a test for this too (passing).

**Closed by stsewd** 2018-06-15 18:38 UTC
Labels: Bug
