### ISSUE TITLE
Is the Sphinx "download" role supported?

### ISSUE THREAD

**Issue by andy-maier** [rtfd/readthedocs.org#3391] opened 2017-12-11 08:07 UTC
## Details

* Project URL: https://readthedocs.org/projects/pywbem
* Build URL (if applicable): https://readthedocs.org/projects/pywbem/builds/6347888/
* Read the Docs username (if applicable): andi0661

## Expected Result

The source of this project uses the Sphinx "download" role for a script file:
```
Download the :download:`pywbem_os_setup.sh </pywbem_os_setup.sh>` script...
```

When building the documentation locally, this works. I expected this to also work in RTD.

This works by copying the file to be downloaded into the `_downloads` directory in the output tree and generates a link to that file in the text shown above. See [Sphinx documentation of the download role](http://www.sphinx-doc.org/en/stable/markup/inline.html#role-download).

The corresponding portion from the Sphinx build log (of the local build, using Sphinx 1.6.5) is:
```
writing additional pages... search
copying images... [100%] images/pywbemcomponents.png
copying downloadable files... [100%] pywbem_os_setup.sh
copying static files... done
copying extra files... WARNING: html_extra_path entry u'/home/maiera/Projects/pywbem/repos/pywbem/docs/_extra' does not exist
done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 9 warnings.
```

## Actual Result

In RTD, no link is generated in the source text shown above. 

The corresponding portion from the RTD Sphinx build log (see link above) is:
```

writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
done
copying readthedocs static files... done
copying searchtools... done
copying extra files... WARNING: html_extra_path entry u'/home/docs/checkouts/readthedocs.org/user_builds/pywbem/checkouts/latest/docs/_extra' does not exist
done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 3 warnings.
```

This RTD log misses the "copying images" and "copying downloadable files" parts.

Are download roles supposed to work on RTD?
Can I do anything in the setup to make them work?

**Comment by stsewd** [comment] 2017-12-26 03:08
You should use a relative path to your current file. With this the problem is solved

```
  - :download:`pywbem_os_setup.sh <../pywbem_os_setup.sh>` on this documentation site...
```

![download](https://user-images.githubusercontent.com/4975310/34345847-2bd1fd3a-e9c0-11e7-8986-a0e9478717a1.png)

**Comment by stsewd** [comment] 2017-12-26 03:25
Also I was having troubles with the builds because of a missing dependency on your `rdt-requirements. txt` file. This is missing `pbr>=1.10.0`.

**Comment by humitos** [comment] 2017-12-26 18:47
@andy-maier I'm closing this one because a solution was posted here. Feel free to re-open it if you consider. Thanks!

**Closed by humitos** 2017-12-26 18:47 UTC
Labels: Support
