### ISSUE TITLE
Deleted project still appears.

### ISSUE THREAD

**Issue by KevinBrolly** [rtfd/readthedocs.org#1579] opened 2015-08-21 13:31 UTC
Hello,

I deleted a project (aliss-engineclub) a while ago but it is STILL active on readthedocs.  The first time you visit the docs (https://aliss-engineclub.readthedocs.org/en/latest/) they will appear!  Subsequent refreshes will occasionally bring up the "You've found something that doesn't exist." page, but a few more refreshes and the docs will be back.

How do you permanently delete a project from readthedocs so that it will no longer appear?  Is this a bug that deleted projects are not actually getting deleted?

**Comment by gregmuellegger** [comment] 2015-08-22 12:54
Thanks for the report. I assume that's a bug on our side. The project's html and everything was successfully deleted from one webserver, but the web02 and web03 are still containing your data. That makes it to appear randomly on refresh, depending on which webserver you are redirected by the load balancer.

I'm working on a fix for this.

Regardless, we need to delete the leftovers from web02 and web03.
@agjohnson, are you able to do this?

**Comment by agjohnson** [comment] 2015-08-26 06:41
I've removed the files from web02/03. I'll leave this open as it is tracking a bug fix.

**Comment by ericholscher** [comment] 2015-08-26 07:22
This is a duplicate of #1408 -- closing as a dupe. It should also have been solved with #1584 I believe.

**Closed by ericholscher** 2015-08-26 07:22 UTC
Labels: Bug, Operations

**Comment by abulovic** [comment] 2015-10-16 11:40
Hi,
I also removed my project, both from github and readthedocs. When can I expect it to not appear any longer on the web?
