### ISSUE TITLE
Allow canonical tag to be selectively overridden

### ISSUE THREAD

**Issue by begriffs** [rtfd/readthedocs.org#3474] opened 2018-01-04 17:24 UTC
## Details

Some pages in our docs contain content that is duplicated with our blog. I've modified our Sphinx template to include a canonical link on these pages pointing back to their source. For instance here is one such page:

https://docs.citusdata.com/en/v7.1/articles/hll_count_distinct.html

If you view the source you can see two canonical links, one that is ours and one added by Read the Docs.

## Expected Result

I added
```html
<link rel="canonical" href="etcetc" />
```
as the very last statement in the template `<head>` element, hoping that our tag would appear underneath – and hence override – the canonical link that Read The Docs adds to each of our pages.

## Actual Result

When serving pages Read The Docs injects its own canonical link below mine, making it impossible for mine to have the final say. I don't want to disable RTD's canonical links entirely because they are good for SEO among docs page versions. I think it would suffice if RTD would simply inject its canonical link at the top of `<head>` rather than the bottom.

**Comment by begriffs** [comment] 2018-01-22 19:46
I tried another trick: overriding the `extrahead` block in my page template.

```jinja
{% block extrahead %}
  {{ super() }}

  {# Last in <head> to override any canonical link that RTD adds #}
  {% if pagename in canonical_urls %}
    <link rel="canonical" href="{{ canonical_urls[pagename] }}" />
  {% endif %}
{% endblock %}
```

But even this is not enough. RTD injects the following code after mine in the document head:

```html
<link rel="canonical" href="http://docs.citusdata.com/en/v7.2/" />
<link rel="stylesheet" href="https://media.readthedocs.org/css/readthedocs-doc-embed.css" type="text/css" />
<script type="text/javascript" src="_static/readthedocs-data.js"></script>

<script type="text/javascript">
  READTHEDOCS_DATA['page'] = 'index'
  READTHEDOCS_DATA['source_suffix'] = '.rst'
</script>
<script type="text/javascript" src="_static/readthedocs-dynamic-include.js"></script>
```

Short of disabling canonical links on all pages, I don't think there is a workaround to customize one for individual pages. Any ideas?

**Comment by begriffs** [comment] 2018-03-26 20:16
Just a nudge on this one. Is it difficult to have RTD add its own canonical link earlier in the document `<head>`?

**Comment by stsewd** [comment] 2018-03-26 21:47
@begriffs after digging a little I found that you weren't really using the official rtd theme on the v1.7 verison, but a custom one. So, this behavior is from that theme https://github.com/citusdata/citus_docs/tree/v7.1/_themes/citus/layout.html#L75

**Comment by begriffs** [comment] 2018-03-26 22:22
@stsewd thanks for taking the time to look into this.

The interesting thing is that the problem still exists on the newest version of the docs. This version uses the stock `sphinx_rtd_theme` theme.

* Example page with two canonical links - https://docs.citusdata.com/en/latest/articles/hll_count_distinct.html
* Now using standard sphinx_rtd_theme - https://github.com/citusdata/citus_docs/blob/master/conf.py#L114-L115
* I add my custom link with - https://github.com/citusdata/citus_docs/blob/master/_templates/page.html#L14-L17

**Comment by stsewd** [comment] 2018-03-27 02:50
mmm, this is very strange, the html from your docs are very different from the one I get on my local installation, I'm not sure why. I can't replicate the issue, rtd always show only one canonical link.

**Comment by begriffs** [comment] 2018-03-27 02:58
On some of the pages I intentionally add my own canonical link, so I'd expect those pages to have two such links. I was just hoping that my link would come last in the html so it would override the one provided by RTD.

**Comment by stsewd** [comment] 2018-03-27 03:02
Anyway, looks like you can't override the `extrahead` from the `page.html` :/ what about creating a custom theme that inherits from the rtd? http://www.sphinx-doc.org/en/stable/theming.html#creating-themes

Or maybe did you try this https://github.com/rtfd/readthedocs-sphinx-ext/blob/master/readthedocs_ext/template-meta.py?

**Comment by begriffs** [comment] 2018-04-23 22:42
Is there a way for my pages to set a variable (`custom_canonical_url` or something) that readthedocs-insert.html.tmpl can read and use if present?

**Comment by humitos** [comment] 2018-04-27 20:31
@begriffs isn't this what you want? http://www.sphinx-doc.org/en/stable/config.html#confval-html_context

**Comment by humitos** [comment] 2019-05-23 11:41
We do have a feature flag to disable Read the Docs to override the context: [`DONT_OVERIDE_SPHINX_CONTEXT`](https://docs.readthedocs.io/en/latest/guides/feature-flags.html).

That way, you can define `canonical_url` with the value you want and it will be used at https://github.com/rtfd/readthedocs-sphinx-ext/blob/master/readthedocs_ext/_templates/readthedocs-insert.html.tmpl#L17

@begriffs please, let us know if you want us to enable it in your project.

**Comment by humitos** [comment] 2019-06-10 11:45
I'd say that we should close this issue. The user has not responded in some time and we do have a way of override the canonical URL via the `html_context` after enabling a Feature Flag.

I do not see anything actionable from our side and I do not consider this a bug.

**Comment by stsewd** [comment] 2019-06-10 17:28
@humitos did you try with this project? Because we inject this from the extension, also is unexpected that specific headers in the rst file are overridden

**Comment by humitos** [comment] 2019-06-10 17:34
> @humitos did you try with this project? 

No, the user that report the issue is not active anymore and this does not seem to affect other users.

> Because we inject this from the extension, also is unexpected that specific headers in the rst file are overridden

This is a completely different problem to solve, in case we want it.

**Comment by begriffs** [comment] 2019-06-10 22:28
Manuel Kaufmann wrote:
> > @humitos did you try with this project? 
> 
> No, the user that report the issue is not active anymore and this does
> not seem to affect other users.

Hi, original bug reporter here. I do care about this issue, and have
seen some email updates about it, but haven't had a lot of time to look
into it.

Please do enable the feature flag which allows our project to override
headers that Read The Docs would ordinarily set. Any reason why that's
not the default behavior for all projects?

**Comment by humitos** [comment] 2019-06-11 09:09
> Please do enable the feature flag which allows our project to override headers that Read The Docs would ordinarily set.

This is done. Please, test it and let us know.

> Any reason why that's not the default behavior for all projects?

Changing this default is a bigger task: we need to check that any project breaks.

**Closed** 2019-06-25 09:23 UTC
Labels: Bug, Needed: more information
