### ISSUE TITLE
all builds failed "Server Error 500: https://readthedocs.org//api/v2/command/"

### ISSUE THREAD

**Issue by ups216** [rtfd/readthedocs.org#2046] opened 2016-03-06 15:31 UTC
all builds were working yesterday and started failing today, I have 2 projects under 2 different accounts, both failed. 

error message

Server Error 500: https://readthedocs.org//api/v2/command/

**Comment by agjohnson** [comment] 2016-03-09 02:29
This is known issue, there is a duplicate ticket with similar issues. It seems a load based issue with our api endpoints. Closing this here.

**Closed by agjohnson** 2016-03-09 02:29 UTC

**Comment by ups216** [comment] 2016-03-13 06:12
@agjohnson it happened again today. looks like this issue happens during the weekend? is there any scheduled job somewhere affecting the site?

**Comment by ups216** [comment] 2016-03-13 08:03
it's working again now

**Comment by agjohnson** [comment] 2016-03-14 17:53
Nope, the issue is completely intermittent, more dependent on load. I've made some changes to our infrastructure today, am seeing if that has any effect on this.

Tracking the issue at #2002
