### ISSUE TITLE
ImportError: No module named 'recommonmark'

### ISSUE THREAD

**Issue by NYKevin** [rtfd/readthedocs.org#1359] opened 2015-06-18 18:48 UTC
This looks pretty similar to #1254, though the [error message](https://readthedocs.org/builds/nbtparse/2980385/) is slightly different:

    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/nbtparse/envs/version-0.6.0/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
        opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
      File "/home/docs/checkouts/readthedocs.org/user_builds/nbtparse/envs/version-0.6.0/lib/python3.4/site-packages/sphinx/application.py", line 126, in __init__
        confoverrides or {}, self.tags)
      File "/home/docs/checkouts/readthedocs.org/user_builds/nbtparse/envs/version-0.6.0/lib/python3.4/site-packages/sphinx/config.py", line 277, in __init__
        execfile_(filename, config)
      File "/home/docs/checkouts/readthedocs.org/user_builds/nbtparse/envs/version-0.6.0/lib/python3.4/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
        exec_(code, _globals)
      File "conf.py", line 256, in <module>
        from recommonmark.parser import CommonMarkParser
    ImportError: No module named 'recommonmark'

    Exception occurred:
      File "conf.py", line 256, in <module>
        from recommonmark.parser import CommonMarkParser
    ImportError: No module named 'recommonmark'
    The full traceback has been saved in /tmp/sphinx-err-5pct0g0e.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

This might be a Sphinx bug, but I'm not really sure how to determine that.

I commented on the old bug yesterday, but since it didn't get reopened, I assumed it would be best to open a brand-new bug.

**Comment by gregmuellegger** [comment] 2015-06-19 10:38
Might be a failed deploy again like in #1254.

**Comment by agjohnson** [comment] 2015-06-19 16:05
This is actually a duplicate of the Alabaster encoding bug at #1350

**Closed by agjohnson** 2015-06-19 16:05 UTC
Labels: Operations

**Comment by NYKevin** [comment] 2015-06-19 23:29
@agjohnson I don't understand.  The error message is entirely different, and I don't even have a `README.rst` file.  In what sense is this a duplicate?

**Comment by agjohnson** [comment] 2015-06-20 19:09
It does look related to me, are you using python3.4 locally? Here's the root failure, emitted on your build during the doc_build stage:

```
Collecting sphinx==1.3.1
  Using cached Sphinx-1.3.1-py2.py3-none-any.whl
Collecting Pygments==2.0.2
  Using cached Pygments-2.0.2-py3-none-any.whl
Collecting virtualenv==1.10.1
Collecting setuptools==1.1
Collecting docutils==0.11
Collecting mkdocs==0.13.3
  Using cached mkdocs-0.13.3-py2.py3-none-any.whl
Collecting mock==1.0.1
Collecting pillow==2.6.1
Collecting readthedocs-sphinx-ext==0.5.4
  Using cached readthedocs_sphinx_ext-0.5.4-py2.py3-none-any.whl
Collecting sphinx-rtd-theme==0.1.8
  Using cached sphinx_rtd_theme-0.1.8-py2.py3-none-any.whl
Collecting recommonmark==0.1.1
  Using cached recommonmark-0.1.1-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx==1.3.1)
Collecting alabaster<0.8,>=0.7 (from sphinx==1.3.1)
  Using cached alabaster-0.7.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-gruum2jy/alabaster/setup.py", line 13, in <module>
        readme = f.read()
      File "/home/docs/checkouts/readthedocs.org/user_builds/nbtparse/envs/version-0.6.0/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15684: ordinal not in range(128)
    
    ----------------------------------------
```

which means recommonmark wasn't installed during that phase and would throw the error you see above. It's a problem with us not cascading failures up to the builder at that stage.

**Comment by NYKevin** [comment] 2015-06-20 20:01
@agjohnson Now I'm extremely confused.  In the requirements section, I see this:

    Collecting alabaster==0.7.4 (from -r doc_reqs.txt (line 1))

But above that, I see this:

    Collecting alabaster<0.8,>=0.7 (from sphinx==1.3.1)
      Using cached alabaster-0.7.5.tar.gz

According to [PEP 440](https://www.python.org/dev/peps/pep-0440/#version-matching), this is not a permissible substitution.  I said `==0.7.4`; Pip should not be using 0.7.5.

Is Read The Docs on the latest Pip?  If so, can you help me gather information so I can file a bug report with the Pip developers?
