### ISSUE TITLE
PDF builds do not do enough pdflatex runs

### ISSUE THREAD

**Issue by jfbu** [rtfd/readthedocs.org#2857] opened 2017-05-20 07:50 UTC
## Details

* Project URL: http://readthedocs.org/projects/sphinx/
* Build URL (if applicable): e.g. http://readthedocs.org/projects/sphinx/builds/5413951/

The issue shows for 1.6.1. The PDF is missing "Index" both in the PDF bookmarks and table of contents.  As explained below I will push (after posting this to get the reference of this issue) a workaround for 1.6.2. 

## Expected Result

PDF contains in its bookmarks an "index" entry and also in the Table of contents.

## Actual Result

No  "index" entry in PDF bookmarks nor in PDF table of contents.

## Analysis

RTD does only one pdflatex run after makeindex. This is not enough.

For Sphinx own docs I will push a commit with this in `conf.py`:
```
latex_elements = {
    'printindex': r'''
\IfFileExists{\jobname.ind}
             {\footnotesize\raggedright\printindex}
             {\begin{sphinxtheindex}\end{sphinxtheindex}}
''',
}
```
This malaxes LaTeX into inserting an "index" entry in the auxiliary `.toc` file on first run.

However, better solution would be for RTD builds to do pdflatex twice after makeindex. The more general  approach could be to use [Latexmk](http://personal.psu.edu/jcc8/software/latexmk/). 

Relates: #1583, https://github.com/sphinx-doc/sphinx/issues/3742

**Comment by maryroseMXXXVI** [comment] 2018-02-03 05:09
Why do you want me  to think by my self if I can work with you

**Comment by agjohnson** [comment] 2018-09-19 21:47
Duplicate of #4454

**Closed by agjohnson** 2018-09-19 21:47 UTC
Labels: Improvement, Needed: design decision
