### ISSUE TITLE
downgrade Shapely?

### ISSUE THREAD

**Issue by ggdhines** [rtfd/readthedocs.org#2070] opened 2016-03-14 13:53 UTC
I currently get a build error due to importing Shapely (a Python geometry library). 
Collecting shapely (from -r /home/docs/checkouts/readthedocs.org/user_builds/zooniverse-aggregation/checkouts/latest/requirements.txt (line 10))
/home/docs/checkouts/readthedocs.org/user_builds/zooniverse-aggregation/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached Shapely-1.5.13.tar.gz
    Complete output from command python setup.py egg_info:
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-sXZwWN/shapely/setup.py", line 38, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-build-sXZwWN/shapely/shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "/tmp/pip-build-sXZwWN/shapely/shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']

```
----------------------------------------
```

Not sure if this is the exact reason why but the top Google hit suggests a problem with Shapely and Heroku - https://github.com/Toblerity/Shapely/issues/322. This is still an option issue so would it be possible to downgrade Shapely to less than 1.5.10? Happy to submit a PR if someone can point me in the right direction of where to look (and confirm that this is the best solution).

Cheers

**Comment by agjohnson** [comment] 2016-03-14 17:50
Shapely isn't a dependency of ours, you'll need to address it in your own confguration. The issue is it's trying to install the package and can't find the linked library -- because it isn't installed. See our FAQ in our docs for mocking out dependencies for missing C libraries.

**Comment by ggdhines** [comment] 2016-03-15 11:43
Hi, I've added the following code at the end of my conf.py file:
from mock import Mock as MagicMock
class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
            return Mock()

MOCK_MODULES = ['shapely','pandas']
sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)

and am still getting the same error.

**Comment by agjohnson** [comment] 2016-03-15 18:01
Because you're still trying to install the modules, if all you've done is added mocking.

**Comment by ggdhines** [comment] 2016-03-15 18:31
Then your FAQ needs to be more detailed - how am I still trying to install Shapely? In my setup.py for the project, I make no mention of Shapely in "install_requires". The only place where Shapely gets mentioned other than "import shapely" is in the requirements.txt file.

**Comment by agjohnson** [comment] 2016-03-15 19:09
Feel free to update them. A `requirements.txt`, if found, is installed by default. You can either specify a separate file which doesn't exist, or a requirements file without the unnecessary dependencies.

**Comment by jacebrowning** [comment] 2016-09-20 23:08
> You can either specify a separate file which doesn't exist

That doesn't seem to work either:

```
Could not open requirements file: [Errno 2] No such file or directory: 'unused.txt'
```

**Comment by jacebrowning** [comment] 2016-09-20 23:13
It seems a little strange to me that ReadTheDocs needs to install all of my project's dependencies (rather than just the documentation packages it needs to build the site).

I ended up getting my site to build by only installing my documentation dependencies: `requirements/dev.txt`.

**Comment by humitos** [comment] 2017-05-30 05:36
Is there something to do here?

I'm closing this issue. Please, feel free to reopen if you consider.

**Closed by humitos** 2017-05-30 05:36 UTC
Labels: Support
