### ISSUE TITLE
Seaching camel-case words returns invalid results

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4492] opened 2018-08-08 15:03 UTC
Entering a `ReadTimeout` (camel-case) is interpret as `read timeout`.

I found a way to reproduce this issue in `requests` project:

* `read timeout` (separated words), returns 2 hits: https://requests.readthedocs.io/en/master/search/?q=read+timeout

![captura de pantalla_2018-08-08_11-57-04](https://user-images.githubusercontent.com/244656/43845349-30737c58-9b02-11e8-9870-4029a34a95e9.png)

* `ReadTimeout` (one word), returns the exact 2 hits: https://requests.readthedocs.io/en/master/search/?q=ReadTimeout

![captura de pantalla_2018-08-08_11-58-07](https://user-images.githubusercontent.com/244656/43845418-54edc2a0-9b02-11e8-8e71-31147d220024.png)

Although, in the second example, it should return something about https://requests.readthedocs.io/en/master/api/#requests.ReadTimeout as https://requests.readthedocs.io/en/master/search/?q=TooManyRedirects does.

![captura de pantalla_2018-08-08_11-58-54](https://user-images.githubusercontent.com/244656/43845481-798bd732-9b02-11e8-8308-354cf2d902bc.png)

Finally, `readtimeout` (lower case) returns exactly the result that I would want for `ReadTimeout` (camel case): https://requests.readthedocs.io/en/master/search/?q=readtimeout

![captura de pantalla_2018-08-08_11-59-59](https://user-images.githubusercontent.com/244656/43845528-989476a2-9b02-11e8-9a29-c045126eed43.png)

**Comment by humitos** [comment] 2018-08-08 15:05
I noted two more things here:

1. the results that you can see in the images, all of them are in _Italic_ but the last one is highlighted in yellow
1. only the last image has reStructuredText on its response

**Comment by invinciblycool** [comment] 2018-09-08 09:54
@humitos Tried reproducing this but the search results vary in my local deployment where I have built the docs of `requests` using the Github URL of my fork.

Search query `read timeout`:

![image](https://user-images.githubusercontent.com/24691797/45252836-e68a3780-b37a-11e8-80a3-65fbb19b530d.png)

Search query `ReadTimeout`:

![image](https://user-images.githubusercontent.com/24691797/45252847-06216000-b37b-11e8-9c8d-7edbd26d5119.png)

Search query `readtimeout`:

![image](https://user-images.githubusercontent.com/24691797/45252857-23562e80-b37b-11e8-8d14-c758471f4777.png)

Am I missing something?

**Comment by stsewd** [comment] 2018-09-10 18:44
I think you need to setup elastic search on your local instance

**Comment by invinciblycool** [comment] 2018-09-10 18:45
I have the exact version as mentioned in the docs setup already.

**Comment by humitos** [comment] 2018-10-01 09:29
@safwanrahman were you able to test this out with the new changes you were making to the whole search? Did you notice any difference with current production version?

**Comment by safwanrahman** [comment] 2018-10-02 02:59
@humitos I did not get chance, I will look into it as soon as we deploy.

**Comment by safwanrahman** [comment] 2018-10-02 03:05
I suspect its related to the Domain object indexing. `requests.ReadTimeout` is a domain object. As we are not indexing domain object separately, it will not work on the upgraded search also.
It will  be fixed with #4289

**Comment by ericholscher** [comment] 2019-01-24 16:38
Believe this should be fixed with the new search deploy.

**Comment by safwanrahman** [comment] 2019-01-28 18:01
>Believe this should be fixed with the new search deploy.
Yeah! I have tested and it seems to be fixed with the latest search deploy!

**Closed by safwanrahman** 2019-01-28 18:01 UTC
Labels: Accepted, Bug
