### ISSUE TITLE
Import UI showing deleted repositories

### ISSUE THREAD

**Issue by jaraco** [rtfd/readthedocs.org#3252] opened 2017-11-13 14:36 UTC
Months ago, I deleted the `cherrypy-mig-test-N` repos from my GitHub account. I created these projects to test migration of issues from Bitbucket to GitHub and they no longer serve any value.

Yet RTD seems to still see them:

![image](https://user-images.githubusercontent.com/308610/32730742-09c3bcf0-c856-11e7-9332-14e20e662e36.png)

I've clicked the refresh button above, but those repos still appear. Perhaps RTD needs to be filtering on undeleted repos or perhaps it has a cache somewhere that needs to be cleared.

**Comment by agjohnson** [comment] 2017-11-13 17:44
Yeah, we don't have a mechanism to sync these two lists currently. This is a duplicate of #2412, so will close here. Feel free to follow up on #2412.

**Closed** 2017-11-13 17:44 UTC
Labels: Status: duplicate
