### ISSUE TITLE
Where to commit .mo files?

### ISSUE THREAD

**Issue by techtonik** [rtfd/readthedocs.org#1747] opened 2015-10-09 07:24 UTC
https://docs.readthedocs.org/en/latest/localization.html#single-project-in-another-language

This tells to commit `.mo` files. Where to commit them?

**Comment by agjohnson** [comment] 2015-10-10 21:25
You commit the `.mo` files in your repo with your docs. These files should be in the path specified in your Sphinx conf `locale_dirs`.

**Comment by agjohnson** [comment] 2015-10-10 21:27
Closing as duplicate of #1746

**Closed by agjohnson** 2015-10-10 21:27 UTC
Labels: Support
