### ISSUE TITLE
build results page is broken in Firefox

### ISSUE THREAD

**Issue by chadwhitacre** [rtfd/readthedocs.org#2261] opened 2016-06-08 21:34 UTC
## Details
- Project URL: http://gratipay.readthedocs.io/
- Build URL (if applicable): https://readthedocs.org/projects/gratipay/builds/4082966/
- Read the Docs username (if applicable): whit537
- Environment: Firefox 46 on Mac OS
## Expected Result

Helpful build output (similar to Travis, etc.).
## Actual Result

Cryptic build output:

![screen shot 2016-06-08 at 5 32 24 pm](https://cloud.githubusercontent.com/assets/134455/15911768/257562da-2d9f-11e6-930c-1de7a58dd5f7.png)

**Comment by whit537** [comment] 2016-06-08 21:35
If I click on the Morse code, I do get some log output:

![screen shot 2016-06-08 at 5 35 02 pm](https://cloud.githubusercontent.com/assets/134455/15911806/60cf1768-2d9f-11e6-8d1f-5cae2f6a67da.png)

**Comment by whit537** [comment] 2016-06-09 15:17
Killing the `margin-bottom` on `.build-command-run span` turns the Morse code into ASCII. :)

![screen shot 2016-06-09 at 11 15 35 am](https://cloud.githubusercontent.com/assets/134455/15934982/9bfa22f8-2e33-11e6-8a03-f4c5e574d0d6.png)

**Comment by whit537** [comment] 2016-06-09 15:22
Looks fine in Chrome.

![screen shot 2016-06-09 at 11 21 51 am](https://cloud.githubusercontent.com/assets/134455/15935177/6acadc94-2e34-11e6-9c78-3784b54ace84.png)

**Comment by agjohnson** [comment] 2016-06-24 23:48
There might be an issue for this already, but yes, this seems to only affect firefox for whatever reason. I don't fully understand why `margin-bottom` reduces the line-height to nothing here, but if it works, feel free to send over a PR. I can test more later, I'll want to verify it doesn't cause problems on other browsers as well.

**Comment by shubheksha** [comment] 2016-08-01 19:40
@agjohnson - I've made the proposed fix, but I am unsure regarding how to test it locally. Could you please guide me a little so that I can submit a PR?

**Comment by agjohnson** [comment] 2016-08-02 19:30
@shubheksha sure thing! have you hit any particular problem getting set up? We have install docs available at:
http://docs.readthedocs.io/en/latest/install.html

The above change breaks in Chrome on OSX, so I'm mostly concerned that we test other browsers with a fix for this issue.
![screen shot 2016-08-02 at 12 30 03 pm](https://cloud.githubusercontent.com/assets/1140183/17342184/dd437cfc-58ac-11e6-8eba-da2ac6ab8c45.png)


If you're stuck on installation, feel free to open up a PR, I'm happy to take a look.

**Comment by shubheksha** [comment] 2016-08-02 19:39
@agjohnson, I've a local installation up & running, didn't face any issues with it!
I've removed the specified CSS property so that it works on Firefox, but I am unsure how can I locally test changes to ensure that it doesn't break in other browsers on a different OS before submitting a PR. Or should I go ahead & submit it anyway?

**Comment by agjohnson** [comment] 2016-08-02 19:50
Yeah, feel free to submit a PR, I can follow up there. I use SauceLabs + ngrok to test design changes against major browsers. I'm already set up for testing here, I can try to provide some feedback if you don't have any way to test Chrome/Safari/etc

**Comment by benjaoming** [comment] 2016-11-14 13:28
On FF 49, current `master` branch displays like this, which looks fine? I mean, maybe 2 pixels are missing...

![screenshot from 2016-11-14 14-26-08](https://cloud.githubusercontent.com/assets/374612/20266485/8ed6d886-aa76-11e6-9e3f-3debfcd99c6a.png)

**Comment by jaraco** [comment] 2017-05-01 11:55
> On FF 49, current master branch displays like this...

@benjaoming That's interesting that apparently it was working on Firefox for some unreleased version. I still have the rendering issue on FF 53 (Mac). Can you confirm you have the issue as well on released versions of FF?

**Comment by jaraco** [comment] 2017-05-01 12:06
I've ended up installing this greasemonkey script to fix the issue for me locally:

```
// ==UserScript==
// @name        Fix RTD 2261
// @namespace   fix-rtd-2261
// @include     https://readthedocs.org/projects/*/builds/*
// @version     1
// @grant       GM_addStyle
// ==/UserScript==

GM_addStyle("div.build-command div.build-command-run > span, div.build-command div.build-command-output > span { margin-bottom: 0 }");
```

**Comment by benjaoming** [comment] 2017-05-02 13:15
> Can you confirm you have the issue as well on released versions of FF?

@jaraco being a regular user of RTD, looking at the build status page, I haven't seen the issue show up since back when I wrote about FF49 in November '16. I'm now using FF53 and had all the intermediate releases.

**Comment by jaraco** [comment] 2017-05-02 16:55
Confirmed. I loaded a clean install of Firefox on my Windows partition and it renders the build status page just fine. So now the question is - what is it about my legacy install that's continuing to render the page unreadable? I suppose I may never know, but perhaps an uninstall/reinstall will help (I'm guessing not because it will likely re-use the settings after reinstall, but it's worth a try).

**Comment by benjaoming** [comment] 2017-05-02 17:04
@jaraco - not sure if it is feasible to persue this any further. You could try to refresh all the assets as well. In Firefox, it's typically SHIFT+F5 to completely reload a page.

**Comment by benjaoming** [comment] 2017-05-02 17:05
You could also try to restart your FF without Extensions?

**Comment by jaraco** [comment] 2017-05-02 17:08
Restarting with Add-Ons disabled doesn't help - still renders improperly. There's another option when restarting that will Refresh Firefox. I'll try that.

**Comment by jaraco** [comment] 2017-05-02 17:14
Refresh Firefox did not help (though it did wipe out my Greasemonkey user scripts).

**Comment by hwine** [comment] 2017-08-02 17:33
I can reproduce the improper rendering on both FF 56 (currently "Nightly") and FF 55 (current "Beta") with fresh installs & profiles (i.e. no extensions or history)

I also opened webcompat/web-bugs#8626 in the hopes a guru can help with a solution.

**Comment by karlcow** [comment] 2017-08-08 07:45
There is a recommended solution here 
https://github.com/webcompat/web-bugs/issues/8626#issuecomment-320273328

`overflow: hidden` seems to have been hidden, but the 

* `margin-bottom: -16px` 
* `display: block;`

needs to be removed.


```css
div.build-command div.build-command-run > span, div.build-command div.build-command-output > span {
	/* display: block; */
	/* margin-bottom: -16px; */
	font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
	white-space: pre;
	overflow-x: scroll;
	overflow-y: hidden;
}
```

with these modifications (left on Gecko, right on Blink):

<img width="441" alt="capture d ecran 2017-08-08 a 16 45 03" src="https://user-images.githubusercontent.com/505230/29061468-02ac34ea-7c59-11e7-983d-b3a96298ce68.png">

**Comment by stevekm** [comment] 2017-11-17 20:15
Still broken in Firefox 57 as well
![screen shot 2017-11-17 at 3 14 14 pm](https://user-images.githubusercontent.com/10505524/32967035-1057cf00-cbaa-11e7-9cdd-60069b875760.png)
[source page](https://readthedocs.org/projects/test-a-sphinx-wiki-v1/builds/6285167/)

**Comment by hwine** [comment] 2017-11-17 23:12
@stevekm unfortunately, afaik no one has created a PR yet.

**Comment by jaraco** [comment] 2017-11-18 00:46
> no one has created a PR yet.

Please see #2630.

**Comment by hwine** [comment] 2017-11-18 01:59
Thanks @jaraco! If folks want to add a reaction to my [nudge on #2630](https://github.com/rtfd/readthedocs.org/pull/2630#issuecomment-345409685), that might be the best way to show support.

**Comment by jaraco** [comment] 2017-11-18 14:21
From [this comment](https://github.com/rtfd/readthedocs.org/pull/2630#issuecomment-345417337): 

> FF quantum looks as I would expect

Weird that [occasionally people report](https://github.com/rtfd/readthedocs.org/issues/2261#issuecomment-260334149) new builds of Firefox not having this issue. Yet at the same time those Firefox versions aren't working for others. Here are screenshots illustrating that the issue persists on my install of Firefox 57 (aka Quantum).

![image](https://user-images.githubusercontent.com/308610/32981028-a7e8df86-cc3f-11e7-87f6-517213473991.png)

![image](https://user-images.githubusercontent.com/308610/32981025-9a365d28-cc3f-11e7-8451-4902e5293216.png)

Interestingly, opening RTD on my Windows box, I don't see the issue.

**Comment by jaraco** [comment] 2017-11-18 14:38
A clean install of Firefox 57 on another mac VM also doesn't exhibit the issue.

![image](https://user-images.githubusercontent.com/308610/32981467-4127d7de-cc44-11e7-9c71-12f4eb766083.png)

**Comment by jaraco** [comment] 2017-11-18 14:46
Yet, even when running Firefox on my main workstation in a brand-new clean profile, the issue persists.

**Comment by benjaoming** [comment] 2017-11-18 14:56
Might be a randomly occurring issue in Firefox' rendering engine. So instead of looking for errors in the CSS/JS code, we should find an entirely different way of displaying these message boxes?

**Comment by jaraco** [comment] 2017-11-18 15:07
Yes, maybe. For completeness, I tried more troubleshooting steps to attempt to get a proper rendering on my workstation. Unfortunately, I was unable to get Firefox to render the page properly in any of these scenarios:

1. Run in safe mode.
2. Run in a new, clean profile.
3. Remove and reinstall Firefox.
4. Create a new user account on the mac and run from there.

Surprising that (4) doesn't render properly but running in a clean install on a VM does.

**Comment by jaraco** [comment] 2017-11-18 15:08
> Might be a randomly occurring issue

I should say, though, the rendering has never worked for me on this machine except when the Greasemonkey hack is in place.

**Comment by jaraco** [comment] 2017-11-18 15:29
I should say too, the Greasemonkey hack doesn't seem to be working either, probably due to the GM4 update.

I did try uninstalling Adobe Acrobat and Adobe Flash Player, since those likely would have installed system-wide behavior, but even after removing those, the page continues to render improperly.

**Comment by stevekm** [comment] 2017-11-18 17:34
Like jaraco mentioned, this has never appeared to be 'random' for me, it's never worked in any version of Firefox on any Mac I've tried

**Closed** 2018-02-09 01:00 UTC
Labels: Bug, Design, Needed: patch
