### ISSUE TITLE
Option to build and preview PRs

### ISSUE THREAD

**Issue by jakirkham** [rtfd/readthedocs.org#3886] opened 2018-03-31 03:34 UTC
Would be great to have an option to build PRs and preview the results. Also would be good to have RTD builds included as a status check on commits.

**Comment by stsewd** [comment] 2018-03-31 03:49
Duplicate of https://github.com/rtfd/readthedocs.org/issues/1340

**Comment by RichardLitt** [comment] 2018-04-02 23:47
Thank you, @jakirkham.

**Closed** 2018-04-02 23:47 UTC
