### ISSUE TITLE
On GitHub: View / Edit points to wrong url

### ISSUE THREAD

**Issue by HelloZeroNet** [rtfd/readthedocs.org#1422] opened 2015-07-09 22:09 UTC
The View / Edit links are broken on the panel that appears when clicking on bottom left arrow.

Example:
http://zeronet.readthedocs.org/en/latest/faq/
 - Points to: https://github.com/HelloZeroNet/Documentation/blob/master/docs/Frequently%20asked%20questions.md
 - It shoud: https://github.com/HelloZeroNet/Documentation/blob/master/docs/faq.md

**Comment by ericholscher** [comment] 2015-08-20 16:40
CLosing as a dupe of #1483

**Closed by ericholscher** 2015-08-20 16:40 UTC
Labels: Mkdocs
