### ISSUE TITLE
3 week old Build Stuck Cloning 

### ISSUE THREAD

**Issue by gtalarico** [rtfd/readthedocs.org#3126] opened 2017-09-27 23:47 UTC
## Details

* Project URL: 
rpw.readthedocs.org

* build Url:
http://readthedocs.org/projects/rpw/builds/5939317/

## Expected Result
Doc Builds or fails

## Actual Result
Build is stuck

###rpw.readthetocs.org

![image](https://user-images.githubusercontent.com/9513968/30943071-aa15063c-a3bc-11e7-9b51-1d316489f6c4.png)

![image](https://user-images.githubusercontent.com/9513968/30943082-ba8e18f0-a3bc-11e7-9e02-73e01e3f2e0b.png)

**Comment by safwanrahman** [comment] 2017-10-14 06:46
Currently its failing because of some import error in your repository!
```
Traceback (most recent call last):
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/envs/latest/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/envs/latest/lib/python2.7/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/envs/latest/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/envs/latest/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 50, in <module>
    from rpw import __version__
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/checkouts/latest/rpw/__init__.py", line 36, in <module>
    import rpw.db
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/checkouts/latest/rpw/db/__init__.py", line 10, in <module>
    from rpw.db.element import Element
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/checkouts/latest/rpw/db/element.py", line 14, in <module>
    from rpw.utils.mixins import CategoryMixin
  File "/home/safwan/readthedocs/user_builds/revitpythonwrapper/checkouts/latest/rpw/utils/mixins.py", line 3, in <module>
    from rpw import revit, db, DB
ImportError: cannot import name db
```

**Comment by RichardLitt** [comment] 2017-10-14 16:54
@safwanrahman Thanks for the help (here and elsewhere)! @gtalarico can you try to fix that import error?

**Comment by gtalarico** [comment] 2017-10-14 17:03
Thanks for looking into this @safwanrahman and @RichardLitt 
To clarify, I am aware there was build failure (circular imports) and I pushed a subsequent revised build that fixed it.

The reason why I reported is because typically when a build fails, it usually shows `Failed` as in the image below. But on this one the status shows stuck on `Cloning` even though it failed.
I would expect the status to show `Failed` after it hit the import error.

![image](https://user-images.githubusercontent.com/9513968/31577602-cd71612c-b0df-11e7-8dc7-b9a1a5108656.png)

**Comment by safwanrahman** [comment] 2017-10-14 18:29
Thanks @gtalarico. It seems like a terrible problem that can not be reproducable locally. Need to get server log to investigate the issue. Need to know why the task keep showing that its closing.
@agjohnson Can you provide more information about the build?

**Closed** 2017-12-14 20:59 UTC
Labels: Bug
