### ISSUE TITLE
local running readthedocs throws import error on lxml

### ISSUE THREAD

**Issue by AvdN** [rtfd/readthedocs.org#2028] opened 2016-02-29 14:52 UTC
## Details

I tried installing read the docs locally in a virtualenv based on 2.7.10. This virtualenv was build
using pyenv.
The server could be started, but on every access an ImportError would be thrown:

```
        from pyquery import PyQuery
    File "/home/venv/rtd/lib/python2.7/site-packages/pyquery/__init__.py", line 12, in <module>
        from .pyquery import PyQuery
    File "/home/venv/rtd/lib/python2.7/site-packages/pyquery/pyquery.py", line 8, in <module>
        from lxml import etree
ImportError: /home/venv/rtd/lib/python2.7/site-packages/lxml/etree.so: undefined symbol: PyUnicodeUCS2_DecodeLatin1
```

After recreating the virtualenv with the system python (2.7.6 on Linux Mint 17.3) this error
goes away. It seems that the python you use for read-the-docs requires building with `--enable-unicode=ucs4` (not tested, assumption based on comparing the output of `sysconfig.get_config_vars('CONFIG_ARGS')`)

If this issue is for a specific project or build, include the following:
- Project: 
- Build #:

**Comment by agjohnson** [comment] 2016-02-29 18:42
We don't support Linux Mint, so you're bound to run into issues. Not sure there is anything actionable by the core team.

**Comment by AvdN** [comment] 2016-02-29 19:05
@agjohnson Interesting you don't support Linux Mint and that is the thing that works.

Obtaining Python 2.7, installing it and creating a virtualenv with that, **as described in the developer documentation** and that that is what doesn't work. So the problem here is faulty or incomplete documentation on the developer process.

Linux Mint is Ubuntu 14.04 with a different desktop, but has takes the python*.deb packages from Ubuntu 14.04. Is Ubuntu not supported either? Which Linux distribution is, if any?
I can set up another machine, with whatever it takes to run this. The Linux Mint version at least allows to import projects, but they never go beyond the "being scheduled" stage. But that is more than you get when following the instructions to the letter.

**Comment by agjohnson** [comment] 2016-02-29 19:21
That is, the core team only supports our production platform -- that is, Ubuntu 14.04 and soon 16.04. Attempting installation on platforms outside our production platform is out of scope for us, as we don't have the resources.

**Comment by AvdN** [comment] 2016-02-29 21:13
I installed Ubuntu and got this to work, but the documentation has several holes that would probably deter less experienced Pythonistas that might want to help out

If you start from gettting Python, then on Ubuntu 14.04 you also have to do

**Comment by agjohnson** [comment] 2016-02-29 21:42
Is there any particular reason you chose to hand compile Python? This shouldn't be necessary.

**Comment by AvdN** [comment] 2016-02-29 21:52
It says to obtain Python 2.7 at the top of the Developer instructions. And since the system python is outdated I used my more up-to-date pyenv built (that wouldn't work). Anyway the system python (on Linux Mint nor on a clean Ubuntu 14.04) has pip nor virtualenv installed. So you would have to go through some hoops keeping those clean and still create a virtualenv.

I redid the above compile on my Linux Mint system (and replaced the pyenv version) and now things install **and** adding my yaml repository results in a succesful  built (just as on the real RTD site).

**Comment by AvdN** [comment] 2016-02-29 21:58
I actually came to look at this because I wanted to locally test my first project to upload to RTD before using the real thing a few times trying to iron out my errors. In did give up and uploded the project to the RTD site and "only" needed an iteration or two. My main worry was that my documents are under `_docs` and I wanted to know if the `conf.py` in there would be found (the systems does, the documentation in one location says only `doc`, `docs` and the system root are searched, in another that the checked out tree is crawled).

**Comment by AvdN** [comment] 2016-02-29 22:00
An official sanctioned Dockerfile for this would probably make sense for other people that might want to try things out before bothering the real site.

**Comment by agjohnson** [comment] 2016-02-29 22:01
Explaining how to install Python 2.7 would be out of the scope of our developer documentation, it should be enough to `apt-get install python` on Ubuntu systems, local development on OSX can use `brew install python` or whatever -- there is nothing in RTD that requires the latest release of Python. Similarly, on Ubuntu, `python-pip` and `python-virtualenv` are enough to get a virtualenv going, where up to date versions are used via our requirements.

If you are only looking to test the output as RTD would output your docs, we're working on breaking out our build steps into a separate module, which would give reproducible output. Still a ways off there though.

**Comment by agjohnson** [comment] 2016-02-29 22:05
There are a few community attempts at docker setups. It's not something we would use, and so with limited bandwidth for support by the core team, our efforts wouldn't go towards supporting it. We likely would not officially support anything like this for that reason.

**Comment by AvdN** [comment] 2016-02-29 22:13
Ok, when I have time I'll look at why the system 2.7 did install but not build the project on my Linux Mint. I could retry that with Ubuntu but I rather work on my development machine like I can now, that also gives me an environment to try and fix things if I find errors, so I should be all set.

Thanks for you feedback, if you ever need help with switching from  PyYAML to support YAML 1.2  (released 2009), just let me know http://yaml.readthedocs.org/en/latest/overview.html

**Comment by agjohnson** [comment] 2017-06-08 00:31
Closing this due to inactivity. Feel free to bring up any changes to YAML support you'd like to see --
 we'd be glad to have the help!

**Closed by agjohnson** 2017-06-08 00:31 UTC
Labels: Community Effort, Support
