### ISSUE TITLE
Project not building

### ISSUE THREAD

**Issue by mhoeber** [rtfd/readthedocs.org#1242] opened 2015-04-30 13:11 UTC
This project had been building, but multiple attempts have been hung for days.  We don't know why, it builds locally fine.

https://readthedocs.org/builds/edx-platform-api/

**Comment by agjohnson** [comment] 2015-05-02 20:37
Hrm, this looks to be an uncaught error state somewhere in the build process -- the virtualenv error output might have something to do with this. I'll look into the build output to see if that doesn't turn up anything.

**Comment by ericholscher** [comment] 2015-05-02 21:33
The build eats up all the memory allocated to it on our build system and gets OOM killed. This is likely a bug in Sphinx or some bad interaction. Are you doing anything odd in these doc builds?

**Comment by mhoeber** [comment] 2015-05-04 12:53
Thanks @ericholscher   I don't think anything is odd.  It was working fine.  We added one new API module which must be causing it, though I don't know why it would.  I'll experiment with that.

**Comment by mhoeber** [comment] 2015-05-05 15:52
@agjohnson @ericholscher   after a lot of trial and error, we know there's something in this file that is causing the build to hang:  https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/user_api/accounts/views.py

At this point we're stuck and will comment out the one autoclass call to this file.  We've mocked all the imports, and it builds fine locally. I don't know what's different in here, but without it RTD builds the project fine. Thanks

**Comment by ericholscher** [comment] 2015-05-27 21:00
Great. Closing this ticket since the issue is fixed.

**Closed by ericholscher** 2015-05-27 21:00 UTC
