### ISSUE TITLE
RTD semi-randomly "sanitizes" my Sphinx conf.py, leading to failure related to local extension discovery

### ISSUE THREAD

**Issue by zmwangx** [rtfd/readthedocs.org#2734] opened 2017-03-19 10:26 UTC
## Details

* Project URL: https://readthedocs.org/projects/storyboard
* Build URL (if applicable): https://readthedocs.org/projects/storyboard/builds/5168349/
* Read the Docs username (if applicable): zmwangx

## Expected Result

Compare the build https://readthedocs.org/projects/storyboard/builds/5168349/ (a failed build) to https://readthedocs.org/projects/storyboard/builds/5168073/ (a successful build). Both builds were for the exact same commit, except the former is for latest and the latter is for stable.

In the successful build, if you check `cat conf.py`, you'll see that my `conf.py` is used, which, in particular, includes the following excerpt:

```py
sys.path.insert(0, os.path.abspath('../numpydoc'))
extensions = [
    'sphinx.ext.autodoc',
    'numpydoc',
    'sphinx.ext.coverage',
    'sphinx.ext.doctest',
    'sphinx.ext.autosummary',
]
```

Here the inserted path is responsible for surfacing the `numpydoc` extension. This `conf.py` is expected.

## Actual Result

Instead, in the failed build, the `conf.py` appears "sanitized":

```py
needs_sphinx = '1.1'

extensions = ['sphinx.ext.autodoc', 'sphinx.ext.pngmath', 'numpydoc',
              'sphinx.ext.intersphinx', 'sphinx.ext.coverage',
              'sphinx.ext.autosummary', 'matplotlib.sphinxext.plot_directive']

...

###########################################################################
#          auto-created readthedocs.org specific configuration            #
###########################################################################

...
```

In particular, my path insertion

```py
sys.path.insert(0, os.path.abspath('../numpydoc'))
```

is gone, so the `numpydoc` extension can no longer be located, resulting in an error

```
ExtensionError: Could not import extension numpydoc (exception: No module named numpydoc)
```

What's extremely frustrating is, as you can see, my `conf.py` gets "sanitized" semi-randomly, even when the exact same revision is built multiple times. The "sanitization" happens the great majority of the time. I guess it depends on the build server?

Anyway, I wish there were a way to tell RTD to respect my `conf.py`.

**Comment by humitos** [comment] 2017-03-19 20:13
I think this is a bug in RTD.

Let me explain it a bit what is happening for me:

* the success building is using your own `conf.py` because RTD finds it and it also adding the specific RTD configurations at the end of your `conf.py` (this method is always called: https://github.com/humitos/readthedocs.org/blob/7f941040c155c87f9c774c0984fc60c068b024fe/readthedocs/doc_builder/backends/sphinx.py#L55)

* the fail building is using a template `conf.py` since RTD is not being able to find your own. So, it creates a common `conf.py` based on a template (https://github.com/humitos/readthedocs.org/blob/7f941040c155c87f9c774c0984fc60c068b024fe/readthedocs/templates/sphinx/conf.py.conf#L1) and then adds the same portion for RTD specific configurations

There is something that I don't fully understand yet that is the template that I linked is not equal to the _sanitized_ version of your `conf.py`. So, it seems that there is something else at that point.

As workaround by now, are you specifying the `Python configuration file` from the `Advanced settings`? Can you try that and let me know?

![captura de pantalla_2017-03-19_14-51-19](https://cloud.githubusercontent.com/assets/244656/24084341/679a0c64-0cb6-11e7-9d69-96b46c3af17b.png)

**Comment by zmwangx** [comment] 2017-03-19 20:33
@humitos 

> Let me explain it a bit what is happening for me:

You're absolutely right. I didn't read the two `conf.py`s carefully when I submitted this issue.

> As workaround by now, are you specifying the Python configuration file from the Advanced settings? Can you try that and let me know?

Thanks, I added `docs/source/conf.py` as "Python configuration file" and at least the last build succeeded: https://readthedocs.org/projects/storyboard/builds/5169712/. It's kind of weird RTD can't find `docs/source/conf.py` though; it's one of the few standard Sphinx configurations.

**Comment by humitos** [comment] 2017-03-21 01:09
@zmwangx hi

We found the issue here. The problem is that as you didn't set the `Python configuration file` RTD tries to find it one automatically for you as I said before. The problem here, is that you have two files named `conf.py` in your repo:

```
[20:03] humitos: storyboard> find ./ -name conf.py
./docs/scipy-sphinx-theme/conf.py
./docs/source/conf.py
```

So, the problem here is that RTD success when _your_ `conf.py` is picked and fails when the one from `scipy-sphinx-theme` is picked. This is because how RTD find is implemented.

Anyway, this is not a bug on RTD as I supposed but a misconfiguration of the project. Even if RTD picks always the same it couldn't know which one is the correct.

On the other hand, to avoid this kind of confusion I created #2735 to show the full path of the `conf.py` used so it will be easier to see and fix it by the user as you already did on your project settings.

I'm closing this one, feel free to reopen if you consider.

**Closed by humitos** 2017-03-21 01:09 UTC
Labels: Bug

**Comment by zmwangx** [comment] 2017-03-21 01:11
Thanks.

> show the full path of the conf.py used so it will be easier to see and fix it by the user as you already did on your project settings.

Yeah that would be very helpful.
