### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Simont3** [rtfd/readthedocs.org#2854] opened 2017-05-19 09:22 UTC
## Details

* Project URL: https://readthedocs.org/projects/awftp/
* Build URL: https://readthedocs.org/projects/awftp/builds/5443784/
* Read the Docs username (if applicable): simont3

## Actual Result

Error

Failed to import project: Failed to get code from 'https://gitlab.com/simont3/awftp.git' (git fetch): 128 Stderr: error: unable to create temporary file: No space left on device fatal: failed to write object fatal: unpack-objects failed

**Comment by abompard** [comment] 2017-05-19 16:28
Duplicate of #2853?

**Comment by geerlingguy** [comment] 2017-05-19 18:59
Agreed, we should consolidate the error reporting to that issue.

**Comment by humitos** [comment] 2017-05-22 17:48
Thanks for report this issue. It was something temporal and it was already fixed. It should be working now. Please let us know if the issue persists.

**Closed by humitos** 2017-05-22 17:48 UTC
