### ISSUE TITLE
Failing to mock duplicity._librsync

### ISSUE THREAD

**Issue by kwloafman** [rtfd/readthedocs.org#2387] opened 2016-08-26 12:26 UTC
## Details
- Project URL: https://readthedocs.org/projects/duplicity/
- Build URL (if applicable): https://readthedocs.org/projects/duplicity/builds/4332094/ + more
- Read the Docs username (if applicable): FirstPrime 
## Expected Result

Successful dummy import of duplicity._librsync
## Actual Result

import of still fails.

I tried the example in your FAQ.  It works with lockfile, but does not work with a nested module.  duplicity needs to remain imported, just to dummy out _librsync, without changing the code of librsync if possible.  I have read the answers on the net, but none of them seem to involve mocking out a complete submodule.  Is that even possible?

...Thanks,
...Ken

**Comment by kwloafman** [comment] 2016-08-27 15:48
Just to follow up, I have tried mocking with:

- _librsync
- duplicity._librsync
- duplicity.librsync._librsync

separately and together.  I have tried the autodoc_mock_imports option on the above as well.  I've used mock.Mock() and mock.MagicMock() in combination with above to no success.  Can anyone point me to an answer that works on the net?  

I think I have gone through all of the bogus ones mentioning [python, mock, package, module] and tried them all with no luck.  There are a lot of answers out there, but ferreting out the real answers seems to be impossible.

**Comment by humitos** [comment] 2017-03-09 01:11
I think there are no a generic solution for this. The one listed in the FAQ seems to be one that works in the most common cases but there are some libraries that requires more research. `pygame` is one of them as listed in https://github.com/rtfd/readthedocs.org/issues/2511#issuecomment-284003753 and this one is another _special_ case.

Please, if you find the solution share it here.

**Comment by kwloafman** [comment] 2017-03-09 15:36
The solution was like this, in librsync.py:

if os.environ.get('READTHEDOCS') == 'True':
    import mock
    import duplicity
    duplicity._librsync = mock.MagicMock()

and this in setup.py:

if not os.environ.get('READTHEDOCS') == 'True':
    ext_modules=[Extension("duplicity._librsync",
                           ["duplicity/_librsyncmodule.c"],
                           include_dirs=incdir_list,
                           library_dirs=libdir_list,
                           libraries=["rsync"])]

...Thanks,
...Ken

**Comment by humitos** [comment] 2017-03-09 18:54
Thank you a lot. Since the issue is solved I'm closing this one. Feel free to reopen it if you have any issue.

**Closed by humitos** 2017-03-09 18:54 UTC
Labels: Support
