### ISSUE TITLE
CSS format issue

### ISSUE THREAD

**Issue by Len-PGH** [rtfd/readthedocs.org#4249] opened 2018-06-15 17:05 UTC
## Details

* Read the Docs project URL:
http://fusionpbx-documentation.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):
https://github.com/Len-PGH/fusionpbx-docs.git
https://github.com/fusionpbx/fusionpbx-docs
https://github.com/LEN-PGH/fusionpbx-docs
Using theme https://github.com/rtfd/sphinx_rtd_theme
## Expected Result

*A description of what you wanted to happen*
Want the build to build like it normally does

## Actual Result

*A description of what actually happened*

CSS looks to be broken.
http://docs.fusionpbx.com
http://docs.techlacom.com

Happens on both sites.  Last build with no issue was Wednesday the 13th.

**Comment by stsewd** [comment] 2018-06-15 17:10
I think this is because of an update in theme, I'll try to see if I can reproduce this (also you can try to specify the latest version of the theme).

**Comment by Len-PGH** [comment] 2018-06-15 17:13
Where do I find the version of the theme and sphinx?

**Comment by davidfischer** [comment] 2018-06-15 17:19
> Where do I find the version of the theme and sphinx?

They will be in the [build output](http://readthedocs.org/projects/fusionpbx-docs/builds/7349909/).

**Comment by davidfischer** [comment] 2018-06-15 17:20
Looks like it is using the latest version of the theme (0.4.0) with Sphinx 1.7.4.

**Comment by stsewd** [comment] 2018-06-15 17:22
Seems like you are using a custom theme 

https://github.com/Len-PGH/fusionpbx-docs/blob/d44f3545d85eedf9a4df8e43ef37cdeeaff36ecc/source/conf.py#L39

https://github.com/Len-PGH/fusionpbx-docs/tree/master/source/_themes/sphinx_rtd_theme

**Comment by davidfischer** [comment] 2018-06-15 17:28
Thanks for the tip @stsewd. So what happened is that:

- The latest sphinx_rtd_theme is installed but *not* used because you have duplicated an old version of the theme into your project directory.
- Older versions of the theme relied on Read the Docs always using the same CSS (bundled with readthedocs.org) rather than the CSS that is bundled with the theme. This is necessary to allow the theme to be updated independently. Previously, whether you were using the 0.2.5 theme or the 0.3.1 theme, you always go the same CSS.
- So the version detection that checks whether to include the CSS finds the latest theme. However, your copied theme overrides the change to use the CSS bundled with the theme.

I see a couple solutions:

- Remove most or all of the duplicated theme from your project and rebuild. Only override the bits you need. This is probably the best solution.
- Pin to a previous version of the theme.

**Comment by Len-PGH** [comment] 2018-06-15 17:31
Theme has been the same since starting to use read the docs. I'm happy to do whatever needs done but trying to understand why this just happened this week with constant builds  and after 2 years?

**Comment by stsewd** [comment] 2018-06-15 17:43
@Len-PGH that is explained above

> Older versions of the theme relied on Read the Docs always using the same CSS (bundled with readthedocs.org) rather than the CSS that is bundled with the theme.

RTD update that in the latest deploy.

**Comment by davidfischer** [comment] 2018-06-15 17:43
> I see a couple solutions:

Another solution is to update your duplicated theme although I suspect you can just remove it.

> trying to understand why this just happened this week

We made a change this week to increase the default version of the RTD theme used with Read the Docs. If there wasn't an overridden version of the theme in your project, this would have been transparent to you. The newest version of the theme bundles CSS a little differently and in the build process we detect the theme version to decide whether to Read the Docs should include some global CSS (the old, suboptimal way) or rely on the theme's CSS. This version detection failed on your project because it has the latest theme but you have overridden the theme with an old version that isn't installed.

Compare the layout of the theme [duplicated in your project](https://github.com/Len-PGH/fusionpbx-docs/blob/3034d87/source/_themes/sphinx_rtd_theme/layout.html#L37-L39) vs what is in the [theme now](https://github.com/rtfd/sphinx_rtd_theme/blob/4b45725/sphinx_rtd_theme/layout.html#L43-L44). There are a number of improvements we made in the theme but those changes relied on upgrading the CSS independently of Read the Docs.

**Comment by Len-PGH** [comment] 2018-06-15 18:00
Thank you for the help. I just moved the theme folder and ran a build and css is back.  I really appreciate everyone's help!

**Closed** 2018-06-15 18:04 UTC
Labels: Support
