### ISSUE TITLE
Builds get stuck in "Cloning" state

### ISSUE THREAD

**Issue by cajus** [rtfd/readthedocs.org#2047] opened 2016-03-07 11:47 UTC
## Details

I wanted to migrate the project documetation to readthedocs, so I initially just added the github repository to RTD. It never leaves the "Cloning" state without any further information.
- Project: https://readthedocs.org/projects/qooxdoo-test
- Build #: lastest

**Comment by bonigarcia** [comment] 2016-03-07 12:29
The same is happening to me in the following project:

https://readthedocs.org/projects/kurento/

... for the stable and latest build.

Please help

**Comment by SeanTAllen** [comment] 2016-03-09 04:15
I am seeing the same thing

https://readthedocs.org/projects/ponyc

**Comment by Thesephi** [comment] 2016-03-16 19:13
Confirming the same thing. Further information for reference:

- my project is hosted on a gitlab instance, and set to be publicly-accessible
- i can clone the project via http successfully (without any authentication)
- my repo contains only 1 file: `README.md`

**Comment by barbara-sfx** [comment] 2016-03-22 18:56
Same here. My repo is private, if that makes a difference.

**Comment by severb** [comment] 2016-04-01 12:57
Same here: https://readthedocs.org/projects/ringpop/builds/.

**Comment by barbara-sfx** [comment] 2016-04-01 19:07
Making my private repo public fixed the problem for me. I am now waiting for a beta invite to readthedocs.com, which supports private docs.

**Comment by Phyks** [comment] 2016-04-02 14:50
Same here https://readthedocs.org/projects/libbmc/build. My project is public.

**Comment by timofeymukha** [comment] 2016-05-12 11:27
Experiencing kind of the same issue.
https://readthedocs.org/projects/eddylicious/

The repo is on bitbucket and is open.
However my project did work fine up to a point, and then the problems with cloning started.
Now, sometimes (like 1 out of 5) the docs would build. otherwise stuck in cloning.

As an example: 

Cloning version latest (html)13 minutes ago
Cloning version latest (html)1 hour, 3 minutes ago
Cloning version latest (html)1 hour, 5 minutes ago
Passed version latest (html)3 hours, 32 minutes ago
Cloning version latest (html)3 hours, 33 minutes ago
Passed version latest (html)3 hours, 38 minutes ago
Cloning version latest (html)17 hours, 12 minutes ago
Cloning version latest (html)18 hours, 30 minutes ago
Passed version latest (html)1 day, 13 hours ago
Cloning version latest (html)1 day, 19 hours ago
Cloning version latest (html)1 day, 19 hours ago

**Comment by rthompsonj** [comment] 2016-05-17 22:03
I too am encountering issues with a repo stuck in the "cloning" state.  I have wiped my build. deleted, recreated, tried a new name, everything I can think of and it just sits at "cloning".

https://readthedocs.org/projects/caesar/builds/

**Comment by agjohnson** [comment] 2016-05-19 23:33
Okay, so a wide array of things going on here. The underlying issue is that we're not reporting build failures correct at exceptions during this phase, so I'll address that with this report.

If you are noticing this stuck behavior, there are a number of things that could be the cause:

* The repo you are trying to connect is private -- the community site will not support these repositories
* You typoed your repo URL
* There are network issues connecting to your repo -- rate limiting perhaps?
* We've noticed a spike in these issues when having memory issues on our build servers, the issue is intermittent

@severb ringpop seems to randomly fail on submodules, not sure why. Github rate limiting these requests perhaps? It might be best to track this separately.

**Comment by justincely** [comment] 2016-06-02 03:17
I just hit this in one of my projects and my solution was similar to @rthompsonj.  My issue was an incorrect path for the file attribute in readthedocs.yml.  After fixing that, from a path that didn't exist, everything worked fine.

**Comment by prolic** [comment] 2016-06-18 09:20
same here: https://readthedocs.org/projects/humusamqp/builds/4114297/

docs are public

**Comment by agjohnson** [comment] 2016-06-18 19:24
@prolic your problem is you set your repository URL to a non-resolvable address `https://prolic/HumusAmqp`

**Comment by prolic** [comment] 2016-06-19 03:52
Damn, my fault. Did not recognize this. Thanks!!!
Am 19.06.2016 03:24 schrieb "Anthony" <notifications@github.com>:

**Comment by Myoldmopar** [comment] 2016-07-21 11:45
I seem to be having this problem as well now.  Things worked great for so long, with one random cloning state a few months ago, but worked since then.  I came back to work on the project and now it won't get past cloning.  https://readthedocs.org/projects/common-pipe-redo/builds/

**Comment by benjaoming** [comment] 2016-10-23 14:25
Same issue here. I have changed nothing in my setup, and now all branches seem to fail their builds. I have an oddly stuck process from 2 weeks ago, wondering if this where the issue comes from?

Project: https://readthedocs.org/projects/ka-lite/builds/

![screenshot from 2016-10-23 16-24-35](https://cloud.githubusercontent.com/assets/374612/19626967/51858ff8-993d-11e6-91e9-0b5155bac17b.png)

**Comment by jagophile** [comment] 2016-11-07 16:41
I am also having this problem. It was working fine and now I've had a build stuck in cloning for 5 days.

Project: https://readthedocs.org/projects/atomdb/
Github: https://github.com/AtomDB/pyatomdb

Any help appreciated.

![cloning](https://cloud.githubusercontent.com/assets/7048277/20066277/fddc294a-a4de-11e6-80b2-60acb4d420c4.png)

**Comment by blaisep** [comment] 2016-11-07 17:47
Hi @jagophile ,
I have this happen from time to time. The usual steps I take are:
    * Does it build cleanly when I run Sphinx locally?
    * When I run Sphinx locally are there any new warnings from the last working build?
    * Do you get any console feedback when you click on the stuck entry in the  _Project->Builds_ listing? (Usually, this problem happens before that console is started)
    * Next, try doing a _Project->Versions->Wipe_ for the relevant version.

In a perfect world we would have better error reporting and exception handling during that crucial transition between the triggering of the build and the setup of the build vm.

**Comment by benjaoming** [comment] 2016-11-07 20:29
@blaisep 

My project builds fine locally, the problem is that nothing can happen because `git clone` fails:

```
Error
Failed to import project: Failed to get code from 'https://github.com/learningequality/ka-lite.git' (git clone): 1
```

Clicking *Wipe* doesn't help.

**Comment by jagophile** [comment] 2016-11-07 21:26
THanks for the information. The step that "worked" for me was,
eventually, *Project->Versions->Wipe.
*The build now fails as I need to include a C module via ctypes. But that's
a different issue (and it seems a known one, that I am now trying to work
around)

I'm pretty sure I tried the wipe thing last week when this hung initially,
but maybe not?

Anyway, seems to be working-ish for now.

Adam

**Comment by benjaoming** [comment] 2016-11-14 10:26
@cajus - could you try changing your Git project path in Settings from `https://githib.com/cajus/qooxdoo` to `https://githib.com/cajus/qooxdoo.git` and building again?

**Comment by benjaoming** [comment] 2017-04-26 07:59
Please note that as of PR #2497, better error messages have been displaying. For my case, it got solved and wasn't actually a problem in the RTD build, just the lack of feedback.

I would suggest to close this issue and instead focus on individual cases now that error messages are available instead of *stuck in "Cloning" state*.

**Comment by humitos** [comment] 2017-05-30 05:53
I took a look at all of the project mentioned in this issues and most of them are:

* deleted (from github or RTD)
* wrong git url (using git@github.com into submodules)
* last builds are passing successfully

@agjohnson do you think there is something we need to do for this issue or we can close it?

If anyone from this issue has an update on the report I would appreciate. Thanks.

**Comment by benjaoming** [comment] 2017-05-30 09:11
@humitos good summary.. see my comment above.. even if people have updates, it'd be better to open up new issues to reach a level of clarity that someone can work out a fix for (and nobody wants to do PRs that don't close issues).

**Comment by stanislaw55** [comment] 2017-12-28 16:41
Hello, 
currently  I'm trying to setup local instance of RtD, using Docker to build docs (`DOCKER_ENABLE = True` in `local_settings.py`). However, no matter in which way I clone my repo, it still gets stuck in 'Cloning' state. 

Updating git to version `2.1.5.1` doesn't change a thing.

Any help appreciated

**Comment by stanislaw55** [comment] 2017-12-29 15:13
AFAICS, ReadTheDocs can clone my repo, and it does that, I can see it in `user_builds`. Next step is to create container and build docs inside it. That's the point where it enters 'Cloning' state. Here are mine four last output lines before 'Cloning'

```
[29/Dec/2017 09:03:50] readthedocs.doc_builder.environments:487[29310]: INFO Creating container
[29/Dec/2017 09:03:50] readthedocs.doc_builder.environments:487[29310]: INFO Creating container
[29/Dec/2017 09:03:50] readthedocs.core.views.hooks:58[29310]: INFO (Version build) Building dummy:latest
[29/Dec/2017 09:03:50] readthedocs.core.views.hooks:58[29310]: INFO (Version build) Building dummy:latest
```

**Comment by stanislaw55** [comment] 2018-01-05 10:06
Nevermind, I've solved that problem. ReadTheDocs doesn't care about actual docker version. All you have to do is to set `DOCKER_VERSION` to `1.18` in `local_settings.py` 

End... that's it. It works.

**Comment by humitos** [comment] 2018-01-22 16:19
I'm closing this issue.

Feel free to create new issues (and link this one) in case there is something that it's not working as you expects.

For the stale states, a PR was merged that should mark them as `failed`: https://github.com/rtfd/readthedocs.org/pull/3312

Thanks you all!

**Closed by humitos** 2018-01-22 16:19 UTC
Labels: Bug
