### ISSUE TITLE
redirecting from a deprecated project to a new one?

### ISSUE THREAD

**Issue by jputrino** [rtfd/readthedocs.org#2294] opened 2016-07-11 16:17 UTC
## Details

* Project URL: f5-openstack-lbaasv2.readthedocs.io | f5-openstack-lbaasv2-driver.readthedocs.io
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): jputrino

## Expected Result

I'd like the first project URL to redirect to the second project URL. The first project was deprecated and today I deleted it; I'd like that URL to redirect to the second URL so users who have the old URL bookmarked can find the documentation.

## Actual Result

N/A

**Comment by berkerpeksag** [comment] 2016-07-17 13:13
Thanks for the report. This is more or less a duplicate of #1440.

**Closed by berkerpeksag** 2016-07-17 13:13 UTC
