### ISSUE TITLE
Build failing randomly

### ISSUE THREAD

**Issue by ShubhamRathi** [rtfd/readthedocs.org#2591] opened 2017-01-15 18:59 UTC
## Details

* Project URL: https://readthedocs.org/projects/opnfvdocsdemo
* Build URL (if applicable): https://readthedocs.org/projects/opnfv/builds/4900987/
* Read the Docs username (if applicable): 

Builds are failing without any apparent reason. On the same commit ID, build failed once and was success later:
Failure: https://readthedocs.org/projects/opnfvdocsdemo/builds/4909528/
![failure](https://cloud.githubusercontent.com/assets/7323949/22061148/b3d9f95a-dd99-11e6-8fec-e9e2fac7c536.png)
Success: https://readthedocs.org/projects/opnfvdocsdemo/builds/4911183/
![success](https://cloud.githubusercontent.com/assets/7323949/22061149/b3dc9624-dd99-11e6-9e5b-b2c1bd943873.png)

This is happening for multiple projects of mine. Whats the issue?

**Comment by ShubhamRathi** [comment] 2017-01-17 18:56
I rolled back my repository to a previous stable state when the documentation was building successfully. Even there the build fails with the same message. What should I be doing? 
https://readthedocs.org/projects/opnfvdocsdemo/builds/4909239/

**Comment by Cadair** [comment] 2017-01-26 10:43
I am having the same issue but, it's all mu builds: https://readthedocs.org/projects/sunpy/builds/

**Comment by ShubhamRathi** [comment] 2017-01-26 14:02
I have raised this issue at all levels with RTD, there isnt any response yet.

**Comment by Cadair** [comment] 2017-02-02 20:26
@ShubhamRathi are you using conda or pip to install your env?

**Comment by agjohnson** [comment] 2017-02-02 20:47
This is a timeout of the celery task that isn't caught as an exception and is a duplicate of #2614.

Our standard build time limit is 10 minutes, I can increase these limits for these projects.

**Comment by Cadair** [comment] 2017-02-02 21:13
@agjohnson Ah right! I think you had previously increased our build time, it seems to have gone back to 10 mins.
If you could bump it that would be very helpful, we do send some donations your way. Thanks a lot.

**Comment by agjohnson** [comment] 2017-02-02 21:27
I bumped both up to 30m and triggered some builds, let me know if that doesn't work though!

**Comment by wtbarnes** [comment] 2017-02-03 16:37
This is happening to me as well: http://readthedocs.org/projects/chiantipy/builds/4979518/ 
and seems to be the same issue as everyone who has posted (i.e. builds > 10 min).

**Comment by ShubhamRathi** [comment] 2017-02-03 17:31
@agjohnson : Yep! This has solved the problem. May I request the same fix be applied to my main project (http://readthedocs.org/projects/opnfv/) which is also having the same issue. 
The project whose time you have bumped up (OPNFVDocsDemo) to 30 m is a mirror of my actual project (OPNFV). Please increase the time to 30 m of my [main project](http://readthedocs.org/projects/opnfv/) too. 
Thanks!

**Comment by KelSolaar** [comment] 2017-02-16 08:50
I might have the same issue on my project too: https://readthedocs.org/projects/colour/builds/

**Comment by singingwolfboy** [comment] 2017-02-16 16:53
I'm also having this problem: https://readthedocs.org/projects/flask-dance/builds/5036074/

**Comment by KelSolaar** [comment] 2017-02-18 20:50
@agjohnson, @ericholscher: Sorry for the annoyance but I'm bumping this as it is postponing the release of a new version of our package, the cumulated build time was around 480 seconds when it stopped executing the next command, the pattern is very similar to @wtbarnes.

**Comment by SteveDoyle2** [comment] 2017-02-22 00:01
I am having this issue as well  https://readthedocs.org/projects/pynastran-git/builds/5057069/

I added up all the times and it comes out to 413 seconds.  It then seems to hang for 171 seconds.  The total build time is 584 seconds, which is slightly less than 10 minutes.

I noticed there is an option for disabling PDF and EPUB.  Is there a way to also disable the json format?  I only really need/want HTML and disabling that option should allow me to cut 3 minutes off the build time.

**Comment by humitos** [comment] 2017-02-23 23:08
@ericholscher @agjohnson what the position taken here? I understand that RTD can't support very long builds since limited resources and it should have a limit, but do users can ask for more time on some of specific projects? If yes, what's the correct way of doing it?

**Comment by humitos** [comment] 2017-02-24 00:25
Answering to myself: http://docs.readthedocs.io/en/latest/builds.html#build-process

> We can increase build limits on a per-project basis, if you provide a good reason your documentation needs more resources.

On the other hand, the documentation says 15 minutes but reading the issues it seems it's only 10.

**Comment by ethanwhite** [comment] 2017-02-24 16:04
@agjohnson Would it be possible to bump the build time on https://readthedocs.org/projects/retriever as well (see #2668). Not sure why it's taking so long to build since our local builds are quick.

**Comment by ericholscher** [comment] 2017-03-09 01:40
We've fixed the bug that was limiting this to 10 minutes, and it should be properly set for 15 now. Let me know if that doesn't fix this issue.

**Comment by humitos** [comment] 2017-04-19 00:19
I'm closing this one since nobody report the same issue in about a month. Please, feel free to open a new issue linking this one if you consider.

Thank you all!

**Closed by humitos** 2017-04-19 00:19 UTC
