### ISSUE TITLE
Edit/View on Github links nonsensical and include build path

### ISSUE THREAD

**Issue by tigerhawkvok** [rtfd/readthedocs.org#2072] opened 2016-03-15 05:07 UTC
## Details
The links appear to be pointing to a version of the canonical directory in ReadTheDocs itself.

Therefore, [on this page](https://amphibian-disease-tracker.readthedocs.org/en/latest/APIs/), instead of the Github links pointing to

https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/documentation/APIs.md

The "edit" and "view" link point, respectively, to

https://github.com/AmphibiaWeb/amphibian-disease-tracker/edit/documentation/home/docs/checkouts/readthedocs.org/user_builds/amphibian-disease-tracker/checkouts/latest/APIs.md

and

https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/documentation/home/docs/checkouts/readthedocs.org/user_builds/amphibian-disease-tracker/checkouts/latest/APIs.md

The entire string `/home/docs/checkouts/readthedocs.org/user_builds/amphibian-disease-tracker/checkouts/latest` should be removed from both links.

* Project: amphibian-disease-tracker
* Build #: [Reported at 3817603](https://readthedocs.org/projects/amphibian-disease-tracker/builds/3817603/)

**Comment by agjohnson** [comment] 2016-03-15 18:10
Closing this as a duplicate of #1917

**Closed by agjohnson** 2016-03-15 18:10 UTC
