### ISSUE TITLE
Build fails searching for docs/requirements.txt

### ISSUE THREAD

**Issue by rb2745** [rtfd/readthedocs.org#3140] opened 2017-10-03 16:07 UTC
## Details

* Project URL: http://onap.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/onap/builds/6069511/
* Read the Docs username (if applicable): 

## Expected Result
Build succeeds using etc/requirements.txt (file in repo) and as specified in advanced settings 

*A description of what you wanted to happen*
Build to succeed using the requirements in etc/requirements.txt as it has until today.
-or- 
A confirmation that there has been a change that requirements must always be in the docs folder.

## Actual Result
Build fails with message -
Could not open requirements file: [Errno 2] No such file or directory: 'docs/requirements.txt'

Wiping the build environment and resubmitting the advanced settings with etc/requirements specified does not fix the problem.

**Comment by safwanrahman** [comment] 2017-10-14 06:32
I can successfully build your project locally with `etc/requirements.txt` in requirements. Maybe something is missing in production

**Comment by rb2745** [comment] 2017-11-14 17:25
I duplicated the requirements.txt file in the docs folder to continue.   

This worked until today 11/14/17 about 6am EST, now all builds are failing with an error message:

_Error
Problem parsing YAML configuration. Invalid "requirements_file": path docs/requirements.txt does not exist_

**Comment by agjohnson** [comment] 2017-11-16 07:10
Closing this as a duplicate. We put a hotfix out today and a proper fix coming shortly.

**Closed by agjohnson** 2017-11-16 07:10 UTC
Labels: Bug

**Comment by Benjamin-Lee** [comment] 2018-07-17 00:08
This is happening to me; I [am having the same problem](https://readthedocs.org/projects/squiggle/builds/7495565/), especially since there is a [`docs/requirements.txt`](https://github.com/Lab41/squiggle/tree/master/docs) file in the repo.

**Comment by davtoh** [comment] 2018-07-17 01:09
hi, same issue over here. I already tried relative paths of all sort and even the direct link to the requirements.txt file on the root of the project.

case: https://readthedocs.org/projects/intelligent-tracker/builds/7495674/
project: https://github.com/davtoh/intelligent-tracker

**Comment by stsewd** [comment] 2018-07-17 02:20
@davtoh please see #4378 for more details

**Comment by rb2745** [comment] 2018-07-17 10:52
The problem reported at the top of this thread was caused by an algorithm at read the docs that searched throughout a repository looking for a configuration yaml file, finding one or more files that were not related to a configuration and trying to use them as  configuration.     The problem was resolved by providing a configuration yaml file in the root of repository.   For example: https://gerrit.onap.org/r/gitweb?p=doc.git;a=blob;f=readthedocs.yml;h=6e6b9af07e6d523a60342e76bf181288bf826c63;hb=HEAD

**Comment by davtoh** [comment] 2018-07-17 16:01
ok, updating the repo with the yaml file prevents it from having this error. Maybe it could be useful to inform the user about the used yaml file and suggest to use readthedocs.yml in case of conflict?

**Comment by stsewd** [comment] 2018-07-17 16:12
@davtoh the problem is a bug, users don't need to have a readthedocs.yml file, but I think is the recommended way of using rtd now.

**Comment by nomeata** [comment] 2018-09-07 14:40
Had to do
```
$ cat readthedocs.yml 
requirements_file: null
```
to fix this problem.
