### ISSUE TITLE
Connecting with github returns a redirect_uri_mismatch

### ISSUE THREAD

**Issue by lfalvarez** [rtfd/readthedocs.org#1533] opened 2015-08-03 14:41 UTC
Hey there I'm getting an error when trying to connect with my github account 
![screenshot from 2015-08-03 11 39 13](https://cloud.githubusercontent.com/assets/585757/9039822/6669faf4-39d4-11e5-8b51-5c80495c6822.png).

Is this just me? what can I do to make it work?

**Comment by gregmuellegger** [comment] 2015-08-03 15:59
This should be fixed with the next deployment (fixed with #1530).
Thanks for the report!

(it's a duplicate of #1520)

**Closed by gregmuellegger** 2015-08-03 15:59 UTC

**Comment by lfalvarez** [comment] 2015-08-03 16:01
:+1: thanks!
