### ISSUE TITLE
Document Django Management Commands

### ISSUE THREAD

**Issue by saadmk11** [rtfd/readthedocs.org#5772] opened 2019-06-06 16:04 UTC
## Details

We should Document Django management commands for Readthedocs which are not currently documented.

The Documentation Could be something similar to this: https://docs.readthedocs.io/en/latest/settings.html

ref: https://github.com/rtfd/readthedocs.org/pull/5750#discussion_r290873570

**Comment by stsewd** [comment] 2019-06-06 18:40
This is a duplicate of https://github.com/rtfd/readthedocs.org/issues/1526

**Closed by stsewd** 2019-06-06 18:40 UTC
Labels: Needed: documentation
