### ISSUE TITLE
Button 'Sync your GitHub projects' seems to have no effect

### ISSUE THREAD

**Issue by lexnederbragt** [rtfd/readthedocs.org#1727] opened 2015-10-04 09:05 UTC
Hi,

I am trying to add a newly created github repo via https://readthedocs.org/dashboard/import/github. The new repo did not (yet) appear in the list, so I clicked the 'Sync your GitHub projects' button, but nothing seems to happen. Mac OX 10.10.5 Chrome, Firefox and Safari all have this problem.

**Comment by agjohnson** [comment] 2015-10-05 17:34
This is a duplicate of #1670

**Closed by agjohnson** 2015-10-05 17:34 UTC
