### ISSUE TITLE
"Sync your GitHub projects" button not working

### ISSUE THREAD

**Issue by cmeeren** [rtfd/readthedocs.org#1670] opened 2015-09-21 14:05 UTC
On https://readthedocs.org/dashboard/import/github, the sync button is not working. Nothing is happening in any browser. FYI, when I look at the button in the developer tools in Firefox, I see no event listeners or other handlers.

**Comment by eserozvataf** [comment] 2015-09-21 15:17
same here

**Comment by onyxfish** [comment] 2015-09-22 13:47
I'm seeing this as well.

**Comment by agjohnson** [comment] 2015-09-22 17:44
Confirmed, not sure what the case is here though. I'm working on an update that will fix a lot of UX issues around project import currently, so that should solve this issue

**Comment by gregmuellegger** [comment] 2015-09-25 13:17
Will be fixed by #1695

**Comment by xolox** [comment] 2015-09-26 12:40
Here's a nasty workaround: Use the web developer tools of your web browser to transform an existing not-yet-imported project into the project that you really want to import (which is not showing up in the interface due to the project being just created and the sync button not working). Just change all of the references to the project you want to import and click the "Create" button. Worked for me :-) (TM).

**Comment by cmeeren** [comment] 2015-09-26 13:57
That's absolutely horrible! I love it.

**Comment by ftomassetti** [comment] 2015-10-03 09:44
Why is this closed? I am still seeing the issue

**Comment by agjohnson** [comment] 2015-10-03 17:14
Looks open to me :)

**Comment by mhhf** [comment] 2015-10-03 21:12
same here. Can't really use it until its fixed :(

**Comment by ocelotl** [comment] 2015-10-05 03:45
Looks broken to me too...

**Comment by agjohnson** [comment] 2015-10-05 17:53
As previously stated, this will be fixed by #1695. We know the button is broken currently.

**Closed** 2015-10-05 18:23 UTC
Labels: Bug

**Comment by agjohnson** [comment] 2015-10-06 17:00
The new interface is out, try refreshing your list of repos
