### ISSUE TITLE
RTFD doesn't delete all files when a project is removed

### ISSUE THREAD

**Issue by tiran** [rtfd/readthedocs.org#454] opened 2013-09-04 12:25 UTC
A couple of months ago I removed my project $SPAM from RTFD. The URL

   https://$SPAM.readthedocs.org/

shows an error page just like I expect. But

   https://$SPAM.readthedocs.org/en/latest/

still has all pages and images. It seems like RTFD doesn't remove all files of a deleted project. 

Christian

PS: I'd rather not post the true value of $SPAM because I don't want to draw attention to outdated docs.

**Comment by tobias47n9e** [comment] 2015-05-27 09:46
Has any progress been made for redirects or purging old pages? I also had to restructure my documentation, but Google now seems to rank the non-existing pages higher than the existing pages.

**Comment by ericholscher** [comment] 2015-08-20 16:32
CLosing as dupe of #1408

**Closed by ericholscher** 2015-08-20 16:32 UTC
Labels: Enhancement
