### ISSUE TITLE
Clicking the [+] button in the dashboard import has no effect

### ISSUE THREAD

**Issue by jaraco** [rtfd/readthedocs.org#2393] opened 2016-08-30 14:15 UTC
Originally reported in #2392, using Firefox 48.0.1 and the 'jaraco' account in RTD, I've associated that account with Github and refreshed the projects and am attempting to import github:jaraco/calendra (on page 9). When I click the plus button next to the project, nothing happens. There are no errors in the Console (either in the navigation leading up to the click or when the click is invoked).

**Comment by ethernomad** [comment] 2016-10-01 06:46
Same here. It works on Chromium.

**Comment by agjohnson** [comment] 2016-11-01 00:59
Closing this as a duplicate of #1773

**Closed by agjohnson** 2016-11-01 00:59 UTC
